/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5769944494911920373L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY\",\"namespace\":\"org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi\",\"fields\":[{\"name\":\"SELLING_ROTATION_CATEGORY_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"SLLNGRTTNCTGY_CODE\",\"type\":[\"null\",\"string\"]},{\"name\":\"SLLNGRTTNCTGY_NM\",\"type\":[\"null\",\"string\"]},{\"name\":\"SLLNGRTTNCTGY_EFFECTIVE_DT\",\"type\":[\"null\",\"string\"]},{\"name\":\"SLLNGRTTNCTGY_DESC\",\"type\":[\"null\",\"string\"]},{\"name\":\"SLLNGRTTNCTGY_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"SLLNGRTTNCTGY_NOTES\",\"type\":[\"null\",\"string\"]},{\"name\":\"SLLNGRTTNCTGY_SHORT_NM\",\"type\":[\"null\",\"string\"]},{\"name\":\"SLLNGRTTNCTGY_LEVEL\",\"type\":[\"null\",\"double\"]},{\"name\":\"SLLNGRTTNCTGY_ISLIVE_IND\",\"type\":[\"null\",\"long\"]},{\"name\":\"SLLNGRTTNCTGY_EXPIRY_DT\",\"type\":[\"null\",\"string\"]},{\"name\":\"LAST_MODIFIED_BY\",\"type\":[\"null\",\"string\"]},{\"name\":\"LAST_MODIFIED_DT\",\"type\":[\"null\",\"string\"]},{\"name\":\"TOT_HOME_ADJMT_FCTR\",\"type\":[\"null\",\"double\"]},{\"name\":\"SRC_KEY_VAL\",\"type\":\"string\"},{\"name\":\"SRC_CDC_OPER_NM\",\"type\":\"string\"},{\"name\":\"SRC_COMMIT_DT_UTC\",\"type\":\"string\"},{\"name\":\"TRG_CRT_DT_PART_UTC\",\"type\":\"string\"},{\"name\":\"SRC_SCHEMA_NM\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY> ENCODER =
      new BinaryMessageEncoder<LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY> DECODER =
      new BinaryMessageDecoder<LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Long SELLING_ROTATION_CATEGORY_ID;
   private java.lang.CharSequence SLLNGRTTNCTGY_CODE;
   private java.lang.CharSequence SLLNGRTTNCTGY_NM;
   private java.lang.CharSequence SLLNGRTTNCTGY_EFFECTIVE_DT;
   private java.lang.CharSequence SLLNGRTTNCTGY_DESC;
   private java.lang.Long SLLNGRTTNCTGY_ID;
   private java.lang.CharSequence SLLNGRTTNCTGY_NOTES;
   private java.lang.CharSequence SLLNGRTTNCTGY_SHORT_NM;
   private java.lang.Double SLLNGRTTNCTGY_LEVEL;
   private java.lang.Long SLLNGRTTNCTGY_ISLIVE_IND;
   private java.lang.CharSequence SLLNGRTTNCTGY_EXPIRY_DT;
   private java.lang.CharSequence LAST_MODIFIED_BY;
   private java.lang.CharSequence LAST_MODIFIED_DT;
   private java.lang.Double TOT_HOME_ADJMT_FCTR;
   private java.lang.CharSequence SRC_KEY_VAL;
   private java.lang.CharSequence SRC_CDC_OPER_NM;
   private java.lang.CharSequence SRC_COMMIT_DT_UTC;
   private java.lang.CharSequence TRG_CRT_DT_PART_UTC;
   private java.lang.CharSequence SRC_SCHEMA_NM;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY() {}

  /**
   * All-args constructor.
   * @param SELLING_ROTATION_CATEGORY_ID The new value for SELLING_ROTATION_CATEGORY_ID
   * @param SLLNGRTTNCTGY_CODE The new value for SLLNGRTTNCTGY_CODE
   * @param SLLNGRTTNCTGY_NM The new value for SLLNGRTTNCTGY_NM
   * @param SLLNGRTTNCTGY_EFFECTIVE_DT The new value for SLLNGRTTNCTGY_EFFECTIVE_DT
   * @param SLLNGRTTNCTGY_DESC The new value for SLLNGRTTNCTGY_DESC
   * @param SLLNGRTTNCTGY_ID The new value for SLLNGRTTNCTGY_ID
   * @param SLLNGRTTNCTGY_NOTES The new value for SLLNGRTTNCTGY_NOTES
   * @param SLLNGRTTNCTGY_SHORT_NM The new value for SLLNGRTTNCTGY_SHORT_NM
   * @param SLLNGRTTNCTGY_LEVEL The new value for SLLNGRTTNCTGY_LEVEL
   * @param SLLNGRTTNCTGY_ISLIVE_IND The new value for SLLNGRTTNCTGY_ISLIVE_IND
   * @param SLLNGRTTNCTGY_EXPIRY_DT The new value for SLLNGRTTNCTGY_EXPIRY_DT
   * @param LAST_MODIFIED_BY The new value for LAST_MODIFIED_BY
   * @param LAST_MODIFIED_DT The new value for LAST_MODIFIED_DT
   * @param TOT_HOME_ADJMT_FCTR The new value for TOT_HOME_ADJMT_FCTR
   * @param SRC_KEY_VAL The new value for SRC_KEY_VAL
   * @param SRC_CDC_OPER_NM The new value for SRC_CDC_OPER_NM
   * @param SRC_COMMIT_DT_UTC The new value for SRC_COMMIT_DT_UTC
   * @param TRG_CRT_DT_PART_UTC The new value for TRG_CRT_DT_PART_UTC
   * @param SRC_SCHEMA_NM The new value for SRC_SCHEMA_NM
   */
  public LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY(java.lang.Long SELLING_ROTATION_CATEGORY_ID, java.lang.CharSequence SLLNGRTTNCTGY_CODE, java.lang.CharSequence SLLNGRTTNCTGY_NM, java.lang.CharSequence SLLNGRTTNCTGY_EFFECTIVE_DT, java.lang.CharSequence SLLNGRTTNCTGY_DESC, java.lang.Long SLLNGRTTNCTGY_ID, java.lang.CharSequence SLLNGRTTNCTGY_NOTES, java.lang.CharSequence SLLNGRTTNCTGY_SHORT_NM, java.lang.Double SLLNGRTTNCTGY_LEVEL, java.lang.Long SLLNGRTTNCTGY_ISLIVE_IND, java.lang.CharSequence SLLNGRTTNCTGY_EXPIRY_DT, java.lang.CharSequence LAST_MODIFIED_BY, java.lang.CharSequence LAST_MODIFIED_DT, java.lang.Double TOT_HOME_ADJMT_FCTR, java.lang.CharSequence SRC_KEY_VAL, java.lang.CharSequence SRC_CDC_OPER_NM, java.lang.CharSequence SRC_COMMIT_DT_UTC, java.lang.CharSequence TRG_CRT_DT_PART_UTC, java.lang.CharSequence SRC_SCHEMA_NM) {
    this.SELLING_ROTATION_CATEGORY_ID = SELLING_ROTATION_CATEGORY_ID;
    this.SLLNGRTTNCTGY_CODE = SLLNGRTTNCTGY_CODE;
    this.SLLNGRTTNCTGY_NM = SLLNGRTTNCTGY_NM;
    this.SLLNGRTTNCTGY_EFFECTIVE_DT = SLLNGRTTNCTGY_EFFECTIVE_DT;
    this.SLLNGRTTNCTGY_DESC = SLLNGRTTNCTGY_DESC;
    this.SLLNGRTTNCTGY_ID = SLLNGRTTNCTGY_ID;
    this.SLLNGRTTNCTGY_NOTES = SLLNGRTTNCTGY_NOTES;
    this.SLLNGRTTNCTGY_SHORT_NM = SLLNGRTTNCTGY_SHORT_NM;
    this.SLLNGRTTNCTGY_LEVEL = SLLNGRTTNCTGY_LEVEL;
    this.SLLNGRTTNCTGY_ISLIVE_IND = SLLNGRTTNCTGY_ISLIVE_IND;
    this.SLLNGRTTNCTGY_EXPIRY_DT = SLLNGRTTNCTGY_EXPIRY_DT;
    this.LAST_MODIFIED_BY = LAST_MODIFIED_BY;
    this.LAST_MODIFIED_DT = LAST_MODIFIED_DT;
    this.TOT_HOME_ADJMT_FCTR = TOT_HOME_ADJMT_FCTR;
    this.SRC_KEY_VAL = SRC_KEY_VAL;
    this.SRC_CDC_OPER_NM = SRC_CDC_OPER_NM;
    this.SRC_COMMIT_DT_UTC = SRC_COMMIT_DT_UTC;
    this.TRG_CRT_DT_PART_UTC = TRG_CRT_DT_PART_UTC;
    this.SRC_SCHEMA_NM = SRC_SCHEMA_NM;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return SELLING_ROTATION_CATEGORY_ID;
    case 1: return SLLNGRTTNCTGY_CODE;
    case 2: return SLLNGRTTNCTGY_NM;
    case 3: return SLLNGRTTNCTGY_EFFECTIVE_DT;
    case 4: return SLLNGRTTNCTGY_DESC;
    case 5: return SLLNGRTTNCTGY_ID;
    case 6: return SLLNGRTTNCTGY_NOTES;
    case 7: return SLLNGRTTNCTGY_SHORT_NM;
    case 8: return SLLNGRTTNCTGY_LEVEL;
    case 9: return SLLNGRTTNCTGY_ISLIVE_IND;
    case 10: return SLLNGRTTNCTGY_EXPIRY_DT;
    case 11: return LAST_MODIFIED_BY;
    case 12: return LAST_MODIFIED_DT;
    case 13: return TOT_HOME_ADJMT_FCTR;
    case 14: return SRC_KEY_VAL;
    case 15: return SRC_CDC_OPER_NM;
    case 16: return SRC_COMMIT_DT_UTC;
    case 17: return TRG_CRT_DT_PART_UTC;
    case 18: return SRC_SCHEMA_NM;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: SELLING_ROTATION_CATEGORY_ID = (java.lang.Long)value$; break;
    case 1: SLLNGRTTNCTGY_CODE = (java.lang.CharSequence)value$; break;
    case 2: SLLNGRTTNCTGY_NM = (java.lang.CharSequence)value$; break;
    case 3: SLLNGRTTNCTGY_EFFECTIVE_DT = (java.lang.CharSequence)value$; break;
    case 4: SLLNGRTTNCTGY_DESC = (java.lang.CharSequence)value$; break;
    case 5: SLLNGRTTNCTGY_ID = (java.lang.Long)value$; break;
    case 6: SLLNGRTTNCTGY_NOTES = (java.lang.CharSequence)value$; break;
    case 7: SLLNGRTTNCTGY_SHORT_NM = (java.lang.CharSequence)value$; break;
    case 8: SLLNGRTTNCTGY_LEVEL = (java.lang.Double)value$; break;
    case 9: SLLNGRTTNCTGY_ISLIVE_IND = (java.lang.Long)value$; break;
    case 10: SLLNGRTTNCTGY_EXPIRY_DT = (java.lang.CharSequence)value$; break;
    case 11: LAST_MODIFIED_BY = (java.lang.CharSequence)value$; break;
    case 12: LAST_MODIFIED_DT = (java.lang.CharSequence)value$; break;
    case 13: TOT_HOME_ADJMT_FCTR = (java.lang.Double)value$; break;
    case 14: SRC_KEY_VAL = (java.lang.CharSequence)value$; break;
    case 15: SRC_CDC_OPER_NM = (java.lang.CharSequence)value$; break;
    case 16: SRC_COMMIT_DT_UTC = (java.lang.CharSequence)value$; break;
    case 17: TRG_CRT_DT_PART_UTC = (java.lang.CharSequence)value$; break;
    case 18: SRC_SCHEMA_NM = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'SELLING_ROTATION_CATEGORY_ID' field.
   * @return The value of the 'SELLING_ROTATION_CATEGORY_ID' field.
   */
  public java.lang.Long getSELLINGROTATIONCATEGORYID() {
    return SELLING_ROTATION_CATEGORY_ID;
  }


  /**
   * Sets the value of the 'SELLING_ROTATION_CATEGORY_ID' field.
   * @param value the value to set.
   */
  public void setSELLINGROTATIONCATEGORYID(java.lang.Long value) {
    this.SELLING_ROTATION_CATEGORY_ID = value;
  }

  /**
   * Gets the value of the 'SLLNGRTTNCTGY_CODE' field.
   * @return The value of the 'SLLNGRTTNCTGY_CODE' field.
   */
  public java.lang.CharSequence getSLLNGRTTNCTGYCODE() {
    return SLLNGRTTNCTGY_CODE;
  }


  /**
   * Sets the value of the 'SLLNGRTTNCTGY_CODE' field.
   * @param value the value to set.
   */
  public void setSLLNGRTTNCTGYCODE(java.lang.CharSequence value) {
    this.SLLNGRTTNCTGY_CODE = value;
  }

  /**
   * Gets the value of the 'SLLNGRTTNCTGY_NM' field.
   * @return The value of the 'SLLNGRTTNCTGY_NM' field.
   */
  public java.lang.CharSequence getSLLNGRTTNCTGYNM() {
    return SLLNGRTTNCTGY_NM;
  }


  /**
   * Sets the value of the 'SLLNGRTTNCTGY_NM' field.
   * @param value the value to set.
   */
  public void setSLLNGRTTNCTGYNM(java.lang.CharSequence value) {
    this.SLLNGRTTNCTGY_NM = value;
  }

  /**
   * Gets the value of the 'SLLNGRTTNCTGY_EFFECTIVE_DT' field.
   * @return The value of the 'SLLNGRTTNCTGY_EFFECTIVE_DT' field.
   */
  public java.lang.CharSequence getSLLNGRTTNCTGYEFFECTIVEDT() {
    return SLLNGRTTNCTGY_EFFECTIVE_DT;
  }


  /**
   * Sets the value of the 'SLLNGRTTNCTGY_EFFECTIVE_DT' field.
   * @param value the value to set.
   */
  public void setSLLNGRTTNCTGYEFFECTIVEDT(java.lang.CharSequence value) {
    this.SLLNGRTTNCTGY_EFFECTIVE_DT = value;
  }

  /**
   * Gets the value of the 'SLLNGRTTNCTGY_DESC' field.
   * @return The value of the 'SLLNGRTTNCTGY_DESC' field.
   */
  public java.lang.CharSequence getSLLNGRTTNCTGYDESC() {
    return SLLNGRTTNCTGY_DESC;
  }


  /**
   * Sets the value of the 'SLLNGRTTNCTGY_DESC' field.
   * @param value the value to set.
   */
  public void setSLLNGRTTNCTGYDESC(java.lang.CharSequence value) {
    this.SLLNGRTTNCTGY_DESC = value;
  }

  /**
   * Gets the value of the 'SLLNGRTTNCTGY_ID' field.
   * @return The value of the 'SLLNGRTTNCTGY_ID' field.
   */
  public java.lang.Long getSLLNGRTTNCTGYID() {
    return SLLNGRTTNCTGY_ID;
  }


  /**
   * Sets the value of the 'SLLNGRTTNCTGY_ID' field.
   * @param value the value to set.
   */
  public void setSLLNGRTTNCTGYID(java.lang.Long value) {
    this.SLLNGRTTNCTGY_ID = value;
  }

  /**
   * Gets the value of the 'SLLNGRTTNCTGY_NOTES' field.
   * @return The value of the 'SLLNGRTTNCTGY_NOTES' field.
   */
  public java.lang.CharSequence getSLLNGRTTNCTGYNOTES() {
    return SLLNGRTTNCTGY_NOTES;
  }


  /**
   * Sets the value of the 'SLLNGRTTNCTGY_NOTES' field.
   * @param value the value to set.
   */
  public void setSLLNGRTTNCTGYNOTES(java.lang.CharSequence value) {
    this.SLLNGRTTNCTGY_NOTES = value;
  }

  /**
   * Gets the value of the 'SLLNGRTTNCTGY_SHORT_NM' field.
   * @return The value of the 'SLLNGRTTNCTGY_SHORT_NM' field.
   */
  public java.lang.CharSequence getSLLNGRTTNCTGYSHORTNM() {
    return SLLNGRTTNCTGY_SHORT_NM;
  }


  /**
   * Sets the value of the 'SLLNGRTTNCTGY_SHORT_NM' field.
   * @param value the value to set.
   */
  public void setSLLNGRTTNCTGYSHORTNM(java.lang.CharSequence value) {
    this.SLLNGRTTNCTGY_SHORT_NM = value;
  }

  /**
   * Gets the value of the 'SLLNGRTTNCTGY_LEVEL' field.
   * @return The value of the 'SLLNGRTTNCTGY_LEVEL' field.
   */
  public java.lang.Double getSLLNGRTTNCTGYLEVEL() {
    return SLLNGRTTNCTGY_LEVEL;
  }


  /**
   * Sets the value of the 'SLLNGRTTNCTGY_LEVEL' field.
   * @param value the value to set.
   */
  public void setSLLNGRTTNCTGYLEVEL(java.lang.Double value) {
    this.SLLNGRTTNCTGY_LEVEL = value;
  }

  /**
   * Gets the value of the 'SLLNGRTTNCTGY_ISLIVE_IND' field.
   * @return The value of the 'SLLNGRTTNCTGY_ISLIVE_IND' field.
   */
  public java.lang.Long getSLLNGRTTNCTGYISLIVEIND() {
    return SLLNGRTTNCTGY_ISLIVE_IND;
  }


  /**
   * Sets the value of the 'SLLNGRTTNCTGY_ISLIVE_IND' field.
   * @param value the value to set.
   */
  public void setSLLNGRTTNCTGYISLIVEIND(java.lang.Long value) {
    this.SLLNGRTTNCTGY_ISLIVE_IND = value;
  }

  /**
   * Gets the value of the 'SLLNGRTTNCTGY_EXPIRY_DT' field.
   * @return The value of the 'SLLNGRTTNCTGY_EXPIRY_DT' field.
   */
  public java.lang.CharSequence getSLLNGRTTNCTGYEXPIRYDT() {
    return SLLNGRTTNCTGY_EXPIRY_DT;
  }


  /**
   * Sets the value of the 'SLLNGRTTNCTGY_EXPIRY_DT' field.
   * @param value the value to set.
   */
  public void setSLLNGRTTNCTGYEXPIRYDT(java.lang.CharSequence value) {
    this.SLLNGRTTNCTGY_EXPIRY_DT = value;
  }

  /**
   * Gets the value of the 'LAST_MODIFIED_BY' field.
   * @return The value of the 'LAST_MODIFIED_BY' field.
   */
  public java.lang.CharSequence getLASTMODIFIEDBY() {
    return LAST_MODIFIED_BY;
  }


  /**
   * Sets the value of the 'LAST_MODIFIED_BY' field.
   * @param value the value to set.
   */
  public void setLASTMODIFIEDBY(java.lang.CharSequence value) {
    this.LAST_MODIFIED_BY = value;
  }

  /**
   * Gets the value of the 'LAST_MODIFIED_DT' field.
   * @return The value of the 'LAST_MODIFIED_DT' field.
   */
  public java.lang.CharSequence getLASTMODIFIEDDT() {
    return LAST_MODIFIED_DT;
  }


  /**
   * Sets the value of the 'LAST_MODIFIED_DT' field.
   * @param value the value to set.
   */
  public void setLASTMODIFIEDDT(java.lang.CharSequence value) {
    this.LAST_MODIFIED_DT = value;
  }

  /**
   * Gets the value of the 'TOT_HOME_ADJMT_FCTR' field.
   * @return The value of the 'TOT_HOME_ADJMT_FCTR' field.
   */
  public java.lang.Double getTOTHOMEADJMTFCTR() {
    return TOT_HOME_ADJMT_FCTR;
  }


  /**
   * Sets the value of the 'TOT_HOME_ADJMT_FCTR' field.
   * @param value the value to set.
   */
  public void setTOTHOMEADJMTFCTR(java.lang.Double value) {
    this.TOT_HOME_ADJMT_FCTR = value;
  }

  /**
   * Gets the value of the 'SRC_KEY_VAL' field.
   * @return The value of the 'SRC_KEY_VAL' field.
   */
  public java.lang.CharSequence getSRCKEYVAL() {
    return SRC_KEY_VAL;
  }


  /**
   * Sets the value of the 'SRC_KEY_VAL' field.
   * @param value the value to set.
   */
  public void setSRCKEYVAL(java.lang.CharSequence value) {
    this.SRC_KEY_VAL = value;
  }

  /**
   * Gets the value of the 'SRC_CDC_OPER_NM' field.
   * @return The value of the 'SRC_CDC_OPER_NM' field.
   */
  public java.lang.CharSequence getSRCCDCOPERNM() {
    return SRC_CDC_OPER_NM;
  }


  /**
   * Sets the value of the 'SRC_CDC_OPER_NM' field.
   * @param value the value to set.
   */
  public void setSRCCDCOPERNM(java.lang.CharSequence value) {
    this.SRC_CDC_OPER_NM = value;
  }

  /**
   * Gets the value of the 'SRC_COMMIT_DT_UTC' field.
   * @return The value of the 'SRC_COMMIT_DT_UTC' field.
   */
  public java.lang.CharSequence getSRCCOMMITDTUTC() {
    return SRC_COMMIT_DT_UTC;
  }


  /**
   * Sets the value of the 'SRC_COMMIT_DT_UTC' field.
   * @param value the value to set.
   */
  public void setSRCCOMMITDTUTC(java.lang.CharSequence value) {
    this.SRC_COMMIT_DT_UTC = value;
  }

  /**
   * Gets the value of the 'TRG_CRT_DT_PART_UTC' field.
   * @return The value of the 'TRG_CRT_DT_PART_UTC' field.
   */
  public java.lang.CharSequence getTRGCRTDTPARTUTC() {
    return TRG_CRT_DT_PART_UTC;
  }


  /**
   * Sets the value of the 'TRG_CRT_DT_PART_UTC' field.
   * @param value the value to set.
   */
  public void setTRGCRTDTPARTUTC(java.lang.CharSequence value) {
    this.TRG_CRT_DT_PART_UTC = value;
  }

  /**
   * Gets the value of the 'SRC_SCHEMA_NM' field.
   * @return The value of the 'SRC_SCHEMA_NM' field.
   */
  public java.lang.CharSequence getSRCSCHEMANM() {
    return SRC_SCHEMA_NM;
  }


  /**
   * Sets the value of the 'SRC_SCHEMA_NM' field.
   * @param value the value to set.
   */
  public void setSRCSCHEMANM(java.lang.CharSequence value) {
    this.SRC_SCHEMA_NM = value;
  }

  /**
   * Creates a new LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY RecordBuilder.
   * @return A new LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY RecordBuilder
   */
  public static org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder newBuilder() {
    return new org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder();
  }

  /**
   * Creates a new LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY RecordBuilder
   */
  public static org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder newBuilder(org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder other) {
    if (other == null) {
      return new org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder();
    } else {
      return new org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder(other);
    }
  }

  /**
   * Creates a new LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY RecordBuilder by copying an existing LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY instance.
   * @param other The existing instance to copy.
   * @return A new LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY RecordBuilder
   */
  public static org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder newBuilder(org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY other) {
    if (other == null) {
      return new org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder();
    } else {
      return new org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder(other);
    }
  }

  /**
   * RecordBuilder for LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY>
    implements org.apache.avro.data.RecordBuilder<LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY> {

    private java.lang.Long SELLING_ROTATION_CATEGORY_ID;
    private java.lang.CharSequence SLLNGRTTNCTGY_CODE;
    private java.lang.CharSequence SLLNGRTTNCTGY_NM;
    private java.lang.CharSequence SLLNGRTTNCTGY_EFFECTIVE_DT;
    private java.lang.CharSequence SLLNGRTTNCTGY_DESC;
    private java.lang.Long SLLNGRTTNCTGY_ID;
    private java.lang.CharSequence SLLNGRTTNCTGY_NOTES;
    private java.lang.CharSequence SLLNGRTTNCTGY_SHORT_NM;
    private java.lang.Double SLLNGRTTNCTGY_LEVEL;
    private java.lang.Long SLLNGRTTNCTGY_ISLIVE_IND;
    private java.lang.CharSequence SLLNGRTTNCTGY_EXPIRY_DT;
    private java.lang.CharSequence LAST_MODIFIED_BY;
    private java.lang.CharSequence LAST_MODIFIED_DT;
    private java.lang.Double TOT_HOME_ADJMT_FCTR;
    private java.lang.CharSequence SRC_KEY_VAL;
    private java.lang.CharSequence SRC_CDC_OPER_NM;
    private java.lang.CharSequence SRC_COMMIT_DT_UTC;
    private java.lang.CharSequence TRG_CRT_DT_PART_UTC;
    private java.lang.CharSequence SRC_SCHEMA_NM;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.SELLING_ROTATION_CATEGORY_ID)) {
        this.SELLING_ROTATION_CATEGORY_ID = data().deepCopy(fields()[0].schema(), other.SELLING_ROTATION_CATEGORY_ID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.SLLNGRTTNCTGY_CODE)) {
        this.SLLNGRTTNCTGY_CODE = data().deepCopy(fields()[1].schema(), other.SLLNGRTTNCTGY_CODE);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.SLLNGRTTNCTGY_NM)) {
        this.SLLNGRTTNCTGY_NM = data().deepCopy(fields()[2].schema(), other.SLLNGRTTNCTGY_NM);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.SLLNGRTTNCTGY_EFFECTIVE_DT)) {
        this.SLLNGRTTNCTGY_EFFECTIVE_DT = data().deepCopy(fields()[3].schema(), other.SLLNGRTTNCTGY_EFFECTIVE_DT);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.SLLNGRTTNCTGY_DESC)) {
        this.SLLNGRTTNCTGY_DESC = data().deepCopy(fields()[4].schema(), other.SLLNGRTTNCTGY_DESC);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.SLLNGRTTNCTGY_ID)) {
        this.SLLNGRTTNCTGY_ID = data().deepCopy(fields()[5].schema(), other.SLLNGRTTNCTGY_ID);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.SLLNGRTTNCTGY_NOTES)) {
        this.SLLNGRTTNCTGY_NOTES = data().deepCopy(fields()[6].schema(), other.SLLNGRTTNCTGY_NOTES);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.SLLNGRTTNCTGY_SHORT_NM)) {
        this.SLLNGRTTNCTGY_SHORT_NM = data().deepCopy(fields()[7].schema(), other.SLLNGRTTNCTGY_SHORT_NM);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.SLLNGRTTNCTGY_LEVEL)) {
        this.SLLNGRTTNCTGY_LEVEL = data().deepCopy(fields()[8].schema(), other.SLLNGRTTNCTGY_LEVEL);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.SLLNGRTTNCTGY_ISLIVE_IND)) {
        this.SLLNGRTTNCTGY_ISLIVE_IND = data().deepCopy(fields()[9].schema(), other.SLLNGRTTNCTGY_ISLIVE_IND);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.SLLNGRTTNCTGY_EXPIRY_DT)) {
        this.SLLNGRTTNCTGY_EXPIRY_DT = data().deepCopy(fields()[10].schema(), other.SLLNGRTTNCTGY_EXPIRY_DT);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.LAST_MODIFIED_BY)) {
        this.LAST_MODIFIED_BY = data().deepCopy(fields()[11].schema(), other.LAST_MODIFIED_BY);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.LAST_MODIFIED_DT)) {
        this.LAST_MODIFIED_DT = data().deepCopy(fields()[12].schema(), other.LAST_MODIFIED_DT);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.TOT_HOME_ADJMT_FCTR)) {
        this.TOT_HOME_ADJMT_FCTR = data().deepCopy(fields()[13].schema(), other.TOT_HOME_ADJMT_FCTR);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.SRC_KEY_VAL)) {
        this.SRC_KEY_VAL = data().deepCopy(fields()[14].schema(), other.SRC_KEY_VAL);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.SRC_CDC_OPER_NM)) {
        this.SRC_CDC_OPER_NM = data().deepCopy(fields()[15].schema(), other.SRC_CDC_OPER_NM);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
      if (isValidValue(fields()[16], other.SRC_COMMIT_DT_UTC)) {
        this.SRC_COMMIT_DT_UTC = data().deepCopy(fields()[16].schema(), other.SRC_COMMIT_DT_UTC);
        fieldSetFlags()[16] = other.fieldSetFlags()[16];
      }
      if (isValidValue(fields()[17], other.TRG_CRT_DT_PART_UTC)) {
        this.TRG_CRT_DT_PART_UTC = data().deepCopy(fields()[17].schema(), other.TRG_CRT_DT_PART_UTC);
        fieldSetFlags()[17] = other.fieldSetFlags()[17];
      }
      if (isValidValue(fields()[18], other.SRC_SCHEMA_NM)) {
        this.SRC_SCHEMA_NM = data().deepCopy(fields()[18].schema(), other.SRC_SCHEMA_NM);
        fieldSetFlags()[18] = other.fieldSetFlags()[18];
      }
    }

    /**
     * Creates a Builder by copying an existing LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY instance
     * @param other The existing instance to copy.
     */
    private Builder(org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.SELLING_ROTATION_CATEGORY_ID)) {
        this.SELLING_ROTATION_CATEGORY_ID = data().deepCopy(fields()[0].schema(), other.SELLING_ROTATION_CATEGORY_ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.SLLNGRTTNCTGY_CODE)) {
        this.SLLNGRTTNCTGY_CODE = data().deepCopy(fields()[1].schema(), other.SLLNGRTTNCTGY_CODE);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.SLLNGRTTNCTGY_NM)) {
        this.SLLNGRTTNCTGY_NM = data().deepCopy(fields()[2].schema(), other.SLLNGRTTNCTGY_NM);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.SLLNGRTTNCTGY_EFFECTIVE_DT)) {
        this.SLLNGRTTNCTGY_EFFECTIVE_DT = data().deepCopy(fields()[3].schema(), other.SLLNGRTTNCTGY_EFFECTIVE_DT);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.SLLNGRTTNCTGY_DESC)) {
        this.SLLNGRTTNCTGY_DESC = data().deepCopy(fields()[4].schema(), other.SLLNGRTTNCTGY_DESC);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.SLLNGRTTNCTGY_ID)) {
        this.SLLNGRTTNCTGY_ID = data().deepCopy(fields()[5].schema(), other.SLLNGRTTNCTGY_ID);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.SLLNGRTTNCTGY_NOTES)) {
        this.SLLNGRTTNCTGY_NOTES = data().deepCopy(fields()[6].schema(), other.SLLNGRTTNCTGY_NOTES);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.SLLNGRTTNCTGY_SHORT_NM)) {
        this.SLLNGRTTNCTGY_SHORT_NM = data().deepCopy(fields()[7].schema(), other.SLLNGRTTNCTGY_SHORT_NM);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.SLLNGRTTNCTGY_LEVEL)) {
        this.SLLNGRTTNCTGY_LEVEL = data().deepCopy(fields()[8].schema(), other.SLLNGRTTNCTGY_LEVEL);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.SLLNGRTTNCTGY_ISLIVE_IND)) {
        this.SLLNGRTTNCTGY_ISLIVE_IND = data().deepCopy(fields()[9].schema(), other.SLLNGRTTNCTGY_ISLIVE_IND);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.SLLNGRTTNCTGY_EXPIRY_DT)) {
        this.SLLNGRTTNCTGY_EXPIRY_DT = data().deepCopy(fields()[10].schema(), other.SLLNGRTTNCTGY_EXPIRY_DT);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.LAST_MODIFIED_BY)) {
        this.LAST_MODIFIED_BY = data().deepCopy(fields()[11].schema(), other.LAST_MODIFIED_BY);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.LAST_MODIFIED_DT)) {
        this.LAST_MODIFIED_DT = data().deepCopy(fields()[12].schema(), other.LAST_MODIFIED_DT);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.TOT_HOME_ADJMT_FCTR)) {
        this.TOT_HOME_ADJMT_FCTR = data().deepCopy(fields()[13].schema(), other.TOT_HOME_ADJMT_FCTR);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.SRC_KEY_VAL)) {
        this.SRC_KEY_VAL = data().deepCopy(fields()[14].schema(), other.SRC_KEY_VAL);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.SRC_CDC_OPER_NM)) {
        this.SRC_CDC_OPER_NM = data().deepCopy(fields()[15].schema(), other.SRC_CDC_OPER_NM);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.SRC_COMMIT_DT_UTC)) {
        this.SRC_COMMIT_DT_UTC = data().deepCopy(fields()[16].schema(), other.SRC_COMMIT_DT_UTC);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.TRG_CRT_DT_PART_UTC)) {
        this.TRG_CRT_DT_PART_UTC = data().deepCopy(fields()[17].schema(), other.TRG_CRT_DT_PART_UTC);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.SRC_SCHEMA_NM)) {
        this.SRC_SCHEMA_NM = data().deepCopy(fields()[18].schema(), other.SRC_SCHEMA_NM);
        fieldSetFlags()[18] = true;
      }
    }

    /**
      * Gets the value of the 'SELLING_ROTATION_CATEGORY_ID' field.
      * @return The value.
      */
    public java.lang.Long getSELLINGROTATIONCATEGORYID() {
      return SELLING_ROTATION_CATEGORY_ID;
    }


    /**
      * Sets the value of the 'SELLING_ROTATION_CATEGORY_ID' field.
      * @param value The value of 'SELLING_ROTATION_CATEGORY_ID'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setSELLINGROTATIONCATEGORYID(java.lang.Long value) {
      validate(fields()[0], value);
      this.SELLING_ROTATION_CATEGORY_ID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'SELLING_ROTATION_CATEGORY_ID' field has been set.
      * @return True if the 'SELLING_ROTATION_CATEGORY_ID' field has been set, false otherwise.
      */
    public boolean hasSELLINGROTATIONCATEGORYID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'SELLING_ROTATION_CATEGORY_ID' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearSELLINGROTATIONCATEGORYID() {
      SELLING_ROTATION_CATEGORY_ID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'SLLNGRTTNCTGY_CODE' field.
      * @return The value.
      */
    public java.lang.CharSequence getSLLNGRTTNCTGYCODE() {
      return SLLNGRTTNCTGY_CODE;
    }


    /**
      * Sets the value of the 'SLLNGRTTNCTGY_CODE' field.
      * @param value The value of 'SLLNGRTTNCTGY_CODE'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setSLLNGRTTNCTGYCODE(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.SLLNGRTTNCTGY_CODE = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'SLLNGRTTNCTGY_CODE' field has been set.
      * @return True if the 'SLLNGRTTNCTGY_CODE' field has been set, false otherwise.
      */
    public boolean hasSLLNGRTTNCTGYCODE() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'SLLNGRTTNCTGY_CODE' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearSLLNGRTTNCTGYCODE() {
      SLLNGRTTNCTGY_CODE = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'SLLNGRTTNCTGY_NM' field.
      * @return The value.
      */
    public java.lang.CharSequence getSLLNGRTTNCTGYNM() {
      return SLLNGRTTNCTGY_NM;
    }


    /**
      * Sets the value of the 'SLLNGRTTNCTGY_NM' field.
      * @param value The value of 'SLLNGRTTNCTGY_NM'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setSLLNGRTTNCTGYNM(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.SLLNGRTTNCTGY_NM = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'SLLNGRTTNCTGY_NM' field has been set.
      * @return True if the 'SLLNGRTTNCTGY_NM' field has been set, false otherwise.
      */
    public boolean hasSLLNGRTTNCTGYNM() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'SLLNGRTTNCTGY_NM' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearSLLNGRTTNCTGYNM() {
      SLLNGRTTNCTGY_NM = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'SLLNGRTTNCTGY_EFFECTIVE_DT' field.
      * @return The value.
      */
    public java.lang.CharSequence getSLLNGRTTNCTGYEFFECTIVEDT() {
      return SLLNGRTTNCTGY_EFFECTIVE_DT;
    }


    /**
      * Sets the value of the 'SLLNGRTTNCTGY_EFFECTIVE_DT' field.
      * @param value The value of 'SLLNGRTTNCTGY_EFFECTIVE_DT'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setSLLNGRTTNCTGYEFFECTIVEDT(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.SLLNGRTTNCTGY_EFFECTIVE_DT = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'SLLNGRTTNCTGY_EFFECTIVE_DT' field has been set.
      * @return True if the 'SLLNGRTTNCTGY_EFFECTIVE_DT' field has been set, false otherwise.
      */
    public boolean hasSLLNGRTTNCTGYEFFECTIVEDT() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'SLLNGRTTNCTGY_EFFECTIVE_DT' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearSLLNGRTTNCTGYEFFECTIVEDT() {
      SLLNGRTTNCTGY_EFFECTIVE_DT = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'SLLNGRTTNCTGY_DESC' field.
      * @return The value.
      */
    public java.lang.CharSequence getSLLNGRTTNCTGYDESC() {
      return SLLNGRTTNCTGY_DESC;
    }


    /**
      * Sets the value of the 'SLLNGRTTNCTGY_DESC' field.
      * @param value The value of 'SLLNGRTTNCTGY_DESC'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setSLLNGRTTNCTGYDESC(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.SLLNGRTTNCTGY_DESC = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'SLLNGRTTNCTGY_DESC' field has been set.
      * @return True if the 'SLLNGRTTNCTGY_DESC' field has been set, false otherwise.
      */
    public boolean hasSLLNGRTTNCTGYDESC() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'SLLNGRTTNCTGY_DESC' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearSLLNGRTTNCTGYDESC() {
      SLLNGRTTNCTGY_DESC = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'SLLNGRTTNCTGY_ID' field.
      * @return The value.
      */
    public java.lang.Long getSLLNGRTTNCTGYID() {
      return SLLNGRTTNCTGY_ID;
    }


    /**
      * Sets the value of the 'SLLNGRTTNCTGY_ID' field.
      * @param value The value of 'SLLNGRTTNCTGY_ID'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setSLLNGRTTNCTGYID(java.lang.Long value) {
      validate(fields()[5], value);
      this.SLLNGRTTNCTGY_ID = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'SLLNGRTTNCTGY_ID' field has been set.
      * @return True if the 'SLLNGRTTNCTGY_ID' field has been set, false otherwise.
      */
    public boolean hasSLLNGRTTNCTGYID() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'SLLNGRTTNCTGY_ID' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearSLLNGRTTNCTGYID() {
      SLLNGRTTNCTGY_ID = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'SLLNGRTTNCTGY_NOTES' field.
      * @return The value.
      */
    public java.lang.CharSequence getSLLNGRTTNCTGYNOTES() {
      return SLLNGRTTNCTGY_NOTES;
    }


    /**
      * Sets the value of the 'SLLNGRTTNCTGY_NOTES' field.
      * @param value The value of 'SLLNGRTTNCTGY_NOTES'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setSLLNGRTTNCTGYNOTES(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.SLLNGRTTNCTGY_NOTES = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'SLLNGRTTNCTGY_NOTES' field has been set.
      * @return True if the 'SLLNGRTTNCTGY_NOTES' field has been set, false otherwise.
      */
    public boolean hasSLLNGRTTNCTGYNOTES() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'SLLNGRTTNCTGY_NOTES' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearSLLNGRTTNCTGYNOTES() {
      SLLNGRTTNCTGY_NOTES = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'SLLNGRTTNCTGY_SHORT_NM' field.
      * @return The value.
      */
    public java.lang.CharSequence getSLLNGRTTNCTGYSHORTNM() {
      return SLLNGRTTNCTGY_SHORT_NM;
    }


    /**
      * Sets the value of the 'SLLNGRTTNCTGY_SHORT_NM' field.
      * @param value The value of 'SLLNGRTTNCTGY_SHORT_NM'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setSLLNGRTTNCTGYSHORTNM(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.SLLNGRTTNCTGY_SHORT_NM = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'SLLNGRTTNCTGY_SHORT_NM' field has been set.
      * @return True if the 'SLLNGRTTNCTGY_SHORT_NM' field has been set, false otherwise.
      */
    public boolean hasSLLNGRTTNCTGYSHORTNM() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'SLLNGRTTNCTGY_SHORT_NM' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearSLLNGRTTNCTGYSHORTNM() {
      SLLNGRTTNCTGY_SHORT_NM = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'SLLNGRTTNCTGY_LEVEL' field.
      * @return The value.
      */
    public java.lang.Double getSLLNGRTTNCTGYLEVEL() {
      return SLLNGRTTNCTGY_LEVEL;
    }


    /**
      * Sets the value of the 'SLLNGRTTNCTGY_LEVEL' field.
      * @param value The value of 'SLLNGRTTNCTGY_LEVEL'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setSLLNGRTTNCTGYLEVEL(java.lang.Double value) {
      validate(fields()[8], value);
      this.SLLNGRTTNCTGY_LEVEL = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'SLLNGRTTNCTGY_LEVEL' field has been set.
      * @return True if the 'SLLNGRTTNCTGY_LEVEL' field has been set, false otherwise.
      */
    public boolean hasSLLNGRTTNCTGYLEVEL() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'SLLNGRTTNCTGY_LEVEL' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearSLLNGRTTNCTGYLEVEL() {
      SLLNGRTTNCTGY_LEVEL = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'SLLNGRTTNCTGY_ISLIVE_IND' field.
      * @return The value.
      */
    public java.lang.Long getSLLNGRTTNCTGYISLIVEIND() {
      return SLLNGRTTNCTGY_ISLIVE_IND;
    }


    /**
      * Sets the value of the 'SLLNGRTTNCTGY_ISLIVE_IND' field.
      * @param value The value of 'SLLNGRTTNCTGY_ISLIVE_IND'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setSLLNGRTTNCTGYISLIVEIND(java.lang.Long value) {
      validate(fields()[9], value);
      this.SLLNGRTTNCTGY_ISLIVE_IND = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'SLLNGRTTNCTGY_ISLIVE_IND' field has been set.
      * @return True if the 'SLLNGRTTNCTGY_ISLIVE_IND' field has been set, false otherwise.
      */
    public boolean hasSLLNGRTTNCTGYISLIVEIND() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'SLLNGRTTNCTGY_ISLIVE_IND' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearSLLNGRTTNCTGYISLIVEIND() {
      SLLNGRTTNCTGY_ISLIVE_IND = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'SLLNGRTTNCTGY_EXPIRY_DT' field.
      * @return The value.
      */
    public java.lang.CharSequence getSLLNGRTTNCTGYEXPIRYDT() {
      return SLLNGRTTNCTGY_EXPIRY_DT;
    }


    /**
      * Sets the value of the 'SLLNGRTTNCTGY_EXPIRY_DT' field.
      * @param value The value of 'SLLNGRTTNCTGY_EXPIRY_DT'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setSLLNGRTTNCTGYEXPIRYDT(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.SLLNGRTTNCTGY_EXPIRY_DT = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'SLLNGRTTNCTGY_EXPIRY_DT' field has been set.
      * @return True if the 'SLLNGRTTNCTGY_EXPIRY_DT' field has been set, false otherwise.
      */
    public boolean hasSLLNGRTTNCTGYEXPIRYDT() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'SLLNGRTTNCTGY_EXPIRY_DT' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearSLLNGRTTNCTGYEXPIRYDT() {
      SLLNGRTTNCTGY_EXPIRY_DT = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'LAST_MODIFIED_BY' field.
      * @return The value.
      */
    public java.lang.CharSequence getLASTMODIFIEDBY() {
      return LAST_MODIFIED_BY;
    }


    /**
      * Sets the value of the 'LAST_MODIFIED_BY' field.
      * @param value The value of 'LAST_MODIFIED_BY'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setLASTMODIFIEDBY(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.LAST_MODIFIED_BY = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'LAST_MODIFIED_BY' field has been set.
      * @return True if the 'LAST_MODIFIED_BY' field has been set, false otherwise.
      */
    public boolean hasLASTMODIFIEDBY() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'LAST_MODIFIED_BY' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearLASTMODIFIEDBY() {
      LAST_MODIFIED_BY = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'LAST_MODIFIED_DT' field.
      * @return The value.
      */
    public java.lang.CharSequence getLASTMODIFIEDDT() {
      return LAST_MODIFIED_DT;
    }


    /**
      * Sets the value of the 'LAST_MODIFIED_DT' field.
      * @param value The value of 'LAST_MODIFIED_DT'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setLASTMODIFIEDDT(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.LAST_MODIFIED_DT = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'LAST_MODIFIED_DT' field has been set.
      * @return True if the 'LAST_MODIFIED_DT' field has been set, false otherwise.
      */
    public boolean hasLASTMODIFIEDDT() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'LAST_MODIFIED_DT' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearLASTMODIFIEDDT() {
      LAST_MODIFIED_DT = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'TOT_HOME_ADJMT_FCTR' field.
      * @return The value.
      */
    public java.lang.Double getTOTHOMEADJMTFCTR() {
      return TOT_HOME_ADJMT_FCTR;
    }


    /**
      * Sets the value of the 'TOT_HOME_ADJMT_FCTR' field.
      * @param value The value of 'TOT_HOME_ADJMT_FCTR'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setTOTHOMEADJMTFCTR(java.lang.Double value) {
      validate(fields()[13], value);
      this.TOT_HOME_ADJMT_FCTR = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'TOT_HOME_ADJMT_FCTR' field has been set.
      * @return True if the 'TOT_HOME_ADJMT_FCTR' field has been set, false otherwise.
      */
    public boolean hasTOTHOMEADJMTFCTR() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'TOT_HOME_ADJMT_FCTR' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearTOTHOMEADJMTFCTR() {
      TOT_HOME_ADJMT_FCTR = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'SRC_KEY_VAL' field.
      * @return The value.
      */
    public java.lang.CharSequence getSRCKEYVAL() {
      return SRC_KEY_VAL;
    }


    /**
      * Sets the value of the 'SRC_KEY_VAL' field.
      * @param value The value of 'SRC_KEY_VAL'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setSRCKEYVAL(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.SRC_KEY_VAL = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'SRC_KEY_VAL' field has been set.
      * @return True if the 'SRC_KEY_VAL' field has been set, false otherwise.
      */
    public boolean hasSRCKEYVAL() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'SRC_KEY_VAL' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearSRCKEYVAL() {
      SRC_KEY_VAL = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'SRC_CDC_OPER_NM' field.
      * @return The value.
      */
    public java.lang.CharSequence getSRCCDCOPERNM() {
      return SRC_CDC_OPER_NM;
    }


    /**
      * Sets the value of the 'SRC_CDC_OPER_NM' field.
      * @param value The value of 'SRC_CDC_OPER_NM'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setSRCCDCOPERNM(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.SRC_CDC_OPER_NM = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'SRC_CDC_OPER_NM' field has been set.
      * @return True if the 'SRC_CDC_OPER_NM' field has been set, false otherwise.
      */
    public boolean hasSRCCDCOPERNM() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'SRC_CDC_OPER_NM' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearSRCCDCOPERNM() {
      SRC_CDC_OPER_NM = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'SRC_COMMIT_DT_UTC' field.
      * @return The value.
      */
    public java.lang.CharSequence getSRCCOMMITDTUTC() {
      return SRC_COMMIT_DT_UTC;
    }


    /**
      * Sets the value of the 'SRC_COMMIT_DT_UTC' field.
      * @param value The value of 'SRC_COMMIT_DT_UTC'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setSRCCOMMITDTUTC(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.SRC_COMMIT_DT_UTC = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'SRC_COMMIT_DT_UTC' field has been set.
      * @return True if the 'SRC_COMMIT_DT_UTC' field has been set, false otherwise.
      */
    public boolean hasSRCCOMMITDTUTC() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'SRC_COMMIT_DT_UTC' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearSRCCOMMITDTUTC() {
      SRC_COMMIT_DT_UTC = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'TRG_CRT_DT_PART_UTC' field.
      * @return The value.
      */
    public java.lang.CharSequence getTRGCRTDTPARTUTC() {
      return TRG_CRT_DT_PART_UTC;
    }


    /**
      * Sets the value of the 'TRG_CRT_DT_PART_UTC' field.
      * @param value The value of 'TRG_CRT_DT_PART_UTC'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setTRGCRTDTPARTUTC(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.TRG_CRT_DT_PART_UTC = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'TRG_CRT_DT_PART_UTC' field has been set.
      * @return True if the 'TRG_CRT_DT_PART_UTC' field has been set, false otherwise.
      */
    public boolean hasTRGCRTDTPARTUTC() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'TRG_CRT_DT_PART_UTC' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearTRGCRTDTPARTUTC() {
      TRG_CRT_DT_PART_UTC = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'SRC_SCHEMA_NM' field.
      * @return The value.
      */
    public java.lang.CharSequence getSRCSCHEMANM() {
      return SRC_SCHEMA_NM;
    }


    /**
      * Sets the value of the 'SRC_SCHEMA_NM' field.
      * @param value The value of 'SRC_SCHEMA_NM'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder setSRCSCHEMANM(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.SRC_SCHEMA_NM = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'SRC_SCHEMA_NM' field has been set.
      * @return True if the 'SRC_SCHEMA_NM' field has been set, false otherwise.
      */
    public boolean hasSRCSCHEMANM() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'SRC_SCHEMA_NM' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_RTCRD.SELLING_ROTATION_CATEGORY.apache.nifi.LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY.Builder clearSRCSCHEMANM() {
      SRC_SCHEMA_NM = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY build() {
      try {
        LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY record = new LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY();
        record.SELLING_ROTATION_CATEGORY_ID = fieldSetFlags()[0] ? this.SELLING_ROTATION_CATEGORY_ID : (java.lang.Long) defaultValue(fields()[0]);
        record.SLLNGRTTNCTGY_CODE = fieldSetFlags()[1] ? this.SLLNGRTTNCTGY_CODE : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.SLLNGRTTNCTGY_NM = fieldSetFlags()[2] ? this.SLLNGRTTNCTGY_NM : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.SLLNGRTTNCTGY_EFFECTIVE_DT = fieldSetFlags()[3] ? this.SLLNGRTTNCTGY_EFFECTIVE_DT : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.SLLNGRTTNCTGY_DESC = fieldSetFlags()[4] ? this.SLLNGRTTNCTGY_DESC : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.SLLNGRTTNCTGY_ID = fieldSetFlags()[5] ? this.SLLNGRTTNCTGY_ID : (java.lang.Long) defaultValue(fields()[5]);
        record.SLLNGRTTNCTGY_NOTES = fieldSetFlags()[6] ? this.SLLNGRTTNCTGY_NOTES : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.SLLNGRTTNCTGY_SHORT_NM = fieldSetFlags()[7] ? this.SLLNGRTTNCTGY_SHORT_NM : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.SLLNGRTTNCTGY_LEVEL = fieldSetFlags()[8] ? this.SLLNGRTTNCTGY_LEVEL : (java.lang.Double) defaultValue(fields()[8]);
        record.SLLNGRTTNCTGY_ISLIVE_IND = fieldSetFlags()[9] ? this.SLLNGRTTNCTGY_ISLIVE_IND : (java.lang.Long) defaultValue(fields()[9]);
        record.SLLNGRTTNCTGY_EXPIRY_DT = fieldSetFlags()[10] ? this.SLLNGRTTNCTGY_EXPIRY_DT : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.LAST_MODIFIED_BY = fieldSetFlags()[11] ? this.LAST_MODIFIED_BY : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.LAST_MODIFIED_DT = fieldSetFlags()[12] ? this.LAST_MODIFIED_DT : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.TOT_HOME_ADJMT_FCTR = fieldSetFlags()[13] ? this.TOT_HOME_ADJMT_FCTR : (java.lang.Double) defaultValue(fields()[13]);
        record.SRC_KEY_VAL = fieldSetFlags()[14] ? this.SRC_KEY_VAL : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.SRC_CDC_OPER_NM = fieldSetFlags()[15] ? this.SRC_CDC_OPER_NM : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.SRC_COMMIT_DT_UTC = fieldSetFlags()[16] ? this.SRC_COMMIT_DT_UTC : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.TRG_CRT_DT_PART_UTC = fieldSetFlags()[17] ? this.TRG_CRT_DT_PART_UTC : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.SRC_SCHEMA_NM = fieldSetFlags()[18] ? this.SRC_SCHEMA_NM : (java.lang.CharSequence) defaultValue(fields()[18]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY>
    WRITER$ = (org.apache.avro.io.DatumWriter<LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY>
    READER$ = (org.apache.avro.io.DatumReader<LNDCDC_ADS_RTCRD_SELLING_ROTATION_CATEGORY>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.SELLING_ROTATION_CATEGORY_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.SELLING_ROTATION_CATEGORY_ID);
    }

    if (this.SLLNGRTTNCTGY_CODE == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.SLLNGRTTNCTGY_CODE);
    }

    if (this.SLLNGRTTNCTGY_NM == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.SLLNGRTTNCTGY_NM);
    }

    if (this.SLLNGRTTNCTGY_EFFECTIVE_DT == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.SLLNGRTTNCTGY_EFFECTIVE_DT);
    }

    if (this.SLLNGRTTNCTGY_DESC == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.SLLNGRTTNCTGY_DESC);
    }

    if (this.SLLNGRTTNCTGY_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.SLLNGRTTNCTGY_ID);
    }

    if (this.SLLNGRTTNCTGY_NOTES == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.SLLNGRTTNCTGY_NOTES);
    }

    if (this.SLLNGRTTNCTGY_SHORT_NM == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.SLLNGRTTNCTGY_SHORT_NM);
    }

    if (this.SLLNGRTTNCTGY_LEVEL == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.SLLNGRTTNCTGY_LEVEL);
    }

    if (this.SLLNGRTTNCTGY_ISLIVE_IND == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.SLLNGRTTNCTGY_ISLIVE_IND);
    }

    if (this.SLLNGRTTNCTGY_EXPIRY_DT == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.SLLNGRTTNCTGY_EXPIRY_DT);
    }

    if (this.LAST_MODIFIED_BY == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.LAST_MODIFIED_BY);
    }

    if (this.LAST_MODIFIED_DT == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.LAST_MODIFIED_DT);
    }

    if (this.TOT_HOME_ADJMT_FCTR == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.TOT_HOME_ADJMT_FCTR);
    }

    out.writeString(this.SRC_KEY_VAL);

    out.writeString(this.SRC_CDC_OPER_NM);

    out.writeString(this.SRC_COMMIT_DT_UTC);

    out.writeString(this.TRG_CRT_DT_PART_UTC);

    out.writeString(this.SRC_SCHEMA_NM);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.SELLING_ROTATION_CATEGORY_ID = null;
      } else {
        this.SELLING_ROTATION_CATEGORY_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.SLLNGRTTNCTGY_CODE = null;
      } else {
        this.SLLNGRTTNCTGY_CODE = in.readString(this.SLLNGRTTNCTGY_CODE instanceof Utf8 ? (Utf8)this.SLLNGRTTNCTGY_CODE : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.SLLNGRTTNCTGY_NM = null;
      } else {
        this.SLLNGRTTNCTGY_NM = in.readString(this.SLLNGRTTNCTGY_NM instanceof Utf8 ? (Utf8)this.SLLNGRTTNCTGY_NM : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.SLLNGRTTNCTGY_EFFECTIVE_DT = null;
      } else {
        this.SLLNGRTTNCTGY_EFFECTIVE_DT = in.readString(this.SLLNGRTTNCTGY_EFFECTIVE_DT instanceof Utf8 ? (Utf8)this.SLLNGRTTNCTGY_EFFECTIVE_DT : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.SLLNGRTTNCTGY_DESC = null;
      } else {
        this.SLLNGRTTNCTGY_DESC = in.readString(this.SLLNGRTTNCTGY_DESC instanceof Utf8 ? (Utf8)this.SLLNGRTTNCTGY_DESC : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.SLLNGRTTNCTGY_ID = null;
      } else {
        this.SLLNGRTTNCTGY_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.SLLNGRTTNCTGY_NOTES = null;
      } else {
        this.SLLNGRTTNCTGY_NOTES = in.readString(this.SLLNGRTTNCTGY_NOTES instanceof Utf8 ? (Utf8)this.SLLNGRTTNCTGY_NOTES : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.SLLNGRTTNCTGY_SHORT_NM = null;
      } else {
        this.SLLNGRTTNCTGY_SHORT_NM = in.readString(this.SLLNGRTTNCTGY_SHORT_NM instanceof Utf8 ? (Utf8)this.SLLNGRTTNCTGY_SHORT_NM : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.SLLNGRTTNCTGY_LEVEL = null;
      } else {
        this.SLLNGRTTNCTGY_LEVEL = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.SLLNGRTTNCTGY_ISLIVE_IND = null;
      } else {
        this.SLLNGRTTNCTGY_ISLIVE_IND = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.SLLNGRTTNCTGY_EXPIRY_DT = null;
      } else {
        this.SLLNGRTTNCTGY_EXPIRY_DT = in.readString(this.SLLNGRTTNCTGY_EXPIRY_DT instanceof Utf8 ? (Utf8)this.SLLNGRTTNCTGY_EXPIRY_DT : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.LAST_MODIFIED_BY = null;
      } else {
        this.LAST_MODIFIED_BY = in.readString(this.LAST_MODIFIED_BY instanceof Utf8 ? (Utf8)this.LAST_MODIFIED_BY : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.LAST_MODIFIED_DT = null;
      } else {
        this.LAST_MODIFIED_DT = in.readString(this.LAST_MODIFIED_DT instanceof Utf8 ? (Utf8)this.LAST_MODIFIED_DT : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.TOT_HOME_ADJMT_FCTR = null;
      } else {
        this.TOT_HOME_ADJMT_FCTR = in.readDouble();
      }

      this.SRC_KEY_VAL = in.readString(this.SRC_KEY_VAL instanceof Utf8 ? (Utf8)this.SRC_KEY_VAL : null);

      this.SRC_CDC_OPER_NM = in.readString(this.SRC_CDC_OPER_NM instanceof Utf8 ? (Utf8)this.SRC_CDC_OPER_NM : null);

      this.SRC_COMMIT_DT_UTC = in.readString(this.SRC_COMMIT_DT_UTC instanceof Utf8 ? (Utf8)this.SRC_COMMIT_DT_UTC : null);

      this.TRG_CRT_DT_PART_UTC = in.readString(this.TRG_CRT_DT_PART_UTC instanceof Utf8 ? (Utf8)this.TRG_CRT_DT_PART_UTC : null);

      this.SRC_SCHEMA_NM = in.readString(this.SRC_SCHEMA_NM instanceof Utf8 ? (Utf8)this.SRC_SCHEMA_NM : null);

    } else {
      for (int i = 0; i < 19; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.SELLING_ROTATION_CATEGORY_ID = null;
          } else {
            this.SELLING_ROTATION_CATEGORY_ID = in.readLong();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.SLLNGRTTNCTGY_CODE = null;
          } else {
            this.SLLNGRTTNCTGY_CODE = in.readString(this.SLLNGRTTNCTGY_CODE instanceof Utf8 ? (Utf8)this.SLLNGRTTNCTGY_CODE : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.SLLNGRTTNCTGY_NM = null;
          } else {
            this.SLLNGRTTNCTGY_NM = in.readString(this.SLLNGRTTNCTGY_NM instanceof Utf8 ? (Utf8)this.SLLNGRTTNCTGY_NM : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.SLLNGRTTNCTGY_EFFECTIVE_DT = null;
          } else {
            this.SLLNGRTTNCTGY_EFFECTIVE_DT = in.readString(this.SLLNGRTTNCTGY_EFFECTIVE_DT instanceof Utf8 ? (Utf8)this.SLLNGRTTNCTGY_EFFECTIVE_DT : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.SLLNGRTTNCTGY_DESC = null;
          } else {
            this.SLLNGRTTNCTGY_DESC = in.readString(this.SLLNGRTTNCTGY_DESC instanceof Utf8 ? (Utf8)this.SLLNGRTTNCTGY_DESC : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.SLLNGRTTNCTGY_ID = null;
          } else {
            this.SLLNGRTTNCTGY_ID = in.readLong();
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.SLLNGRTTNCTGY_NOTES = null;
          } else {
            this.SLLNGRTTNCTGY_NOTES = in.readString(this.SLLNGRTTNCTGY_NOTES instanceof Utf8 ? (Utf8)this.SLLNGRTTNCTGY_NOTES : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.SLLNGRTTNCTGY_SHORT_NM = null;
          } else {
            this.SLLNGRTTNCTGY_SHORT_NM = in.readString(this.SLLNGRTTNCTGY_SHORT_NM instanceof Utf8 ? (Utf8)this.SLLNGRTTNCTGY_SHORT_NM : null);
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.SLLNGRTTNCTGY_LEVEL = null;
          } else {
            this.SLLNGRTTNCTGY_LEVEL = in.readDouble();
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.SLLNGRTTNCTGY_ISLIVE_IND = null;
          } else {
            this.SLLNGRTTNCTGY_ISLIVE_IND = in.readLong();
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.SLLNGRTTNCTGY_EXPIRY_DT = null;
          } else {
            this.SLLNGRTTNCTGY_EXPIRY_DT = in.readString(this.SLLNGRTTNCTGY_EXPIRY_DT instanceof Utf8 ? (Utf8)this.SLLNGRTTNCTGY_EXPIRY_DT : null);
          }
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.LAST_MODIFIED_BY = null;
          } else {
            this.LAST_MODIFIED_BY = in.readString(this.LAST_MODIFIED_BY instanceof Utf8 ? (Utf8)this.LAST_MODIFIED_BY : null);
          }
          break;

        case 12:
          if (in.readIndex() != 1) {
            in.readNull();
            this.LAST_MODIFIED_DT = null;
          } else {
            this.LAST_MODIFIED_DT = in.readString(this.LAST_MODIFIED_DT instanceof Utf8 ? (Utf8)this.LAST_MODIFIED_DT : null);
          }
          break;

        case 13:
          if (in.readIndex() != 1) {
            in.readNull();
            this.TOT_HOME_ADJMT_FCTR = null;
          } else {
            this.TOT_HOME_ADJMT_FCTR = in.readDouble();
          }
          break;

        case 14:
          this.SRC_KEY_VAL = in.readString(this.SRC_KEY_VAL instanceof Utf8 ? (Utf8)this.SRC_KEY_VAL : null);
          break;

        case 15:
          this.SRC_CDC_OPER_NM = in.readString(this.SRC_CDC_OPER_NM instanceof Utf8 ? (Utf8)this.SRC_CDC_OPER_NM : null);
          break;

        case 16:
          this.SRC_COMMIT_DT_UTC = in.readString(this.SRC_COMMIT_DT_UTC instanceof Utf8 ? (Utf8)this.SRC_COMMIT_DT_UTC : null);
          break;

        case 17:
          this.TRG_CRT_DT_PART_UTC = in.readString(this.TRG_CRT_DT_PART_UTC instanceof Utf8 ? (Utf8)this.TRG_CRT_DT_PART_UTC : null);
          break;

        case 18:
          this.SRC_SCHEMA_NM = in.readString(this.SRC_SCHEMA_NM instanceof Utf8 ? (Utf8)this.SRC_SCHEMA_NM : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










