/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.apache.nifi.custom.joined;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Intesting other unified AVRO schema before joinging with PRPSL_LN (PK: PRPSL_LN_KEY) */
@org.apache.avro.specific.AvroGenerated
public class CONFORMED_CON_PRPSL_PRPSL_LN extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4289144100398187360L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CONFORMED_CON_PRPSL_PRPSL_LN\",\"namespace\":\"org.apache.nifi.custom.joined\",\"doc\":\"Intesting other unified AVRO schema before joinging with PRPSL_LN (PK: PRPSL_LN_KEY)\",\"fields\":[{\"name\":\"_ID\",\"type\":\"string\"},{\"name\":\"PROPOSAL_LINE_ID\",\"type\":\"long\"},{\"name\":\"PARENT_PROPOSAL_LINE_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"PRPSL_LN_KEY_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"PRPSL_LN_QTR_KEY_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"PROPOSAL_ID\",\"type\":\"long\"},{\"name\":\"FLIGHT_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"OTLT_EXT_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"SELLING_ROTATION_KEY\",\"type\":[\"null\",\"double\"]},{\"name\":\"PKG_SLLNG_RTTN_TYP_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"PRPSL_LN_COST_TYP_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"PKG_PRD_VRSN_RLS_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"SELLING_ROTATION_CATEGORY_KEY\",\"type\":[\"null\",\"double\"]},{\"name\":\"ROTATION_PERIOD_RELEASE_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"SALES_INVENTORY_TYPE_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"RATE_CARD_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"EQV_RTS_IND\",\"type\":[\"null\",\"long\"]},{\"name\":\"AGENCY_COMMISSION\",\"type\":[\"null\",\"double\"]},{\"name\":\"CURRENCY_KEY\",\"type\":[\"null\",\"long\"]},{\"name\":\"TELEVISION_PROPOSAL_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"AD_UNIT_SCHD_ALOCTN_TYP_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"SRC_KEY_VAL\",\"type\":\"string\"},{\"name\":\"SRC_CDC_OPER_NM\",\"type\":\"string\"},{\"name\":\"SRC_COMMIT_DT_UTC\",\"type\":\"string\"},{\"name\":\"TRG_CRT_DT_PART_UTC\",\"type\":\"string\"},{\"name\":\"SRC_SCHEMA_NM\",\"type\":\"string\"},{\"name\":\"LAST_MODIFIED_BY\",\"type\":[\"null\",\"string\"]},{\"name\":\"LAST_MODIFIED_DT\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CONFORMED_CON_PRPSL_PRPSL_LN> ENCODER =
      new BinaryMessageEncoder<CONFORMED_CON_PRPSL_PRPSL_LN>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CONFORMED_CON_PRPSL_PRPSL_LN> DECODER =
      new BinaryMessageDecoder<CONFORMED_CON_PRPSL_PRPSL_LN>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CONFORMED_CON_PRPSL_PRPSL_LN> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CONFORMED_CON_PRPSL_PRPSL_LN> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CONFORMED_CON_PRPSL_PRPSL_LN> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CONFORMED_CON_PRPSL_PRPSL_LN>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CONFORMED_CON_PRPSL_PRPSL_LN to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CONFORMED_CON_PRPSL_PRPSL_LN from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CONFORMED_CON_PRPSL_PRPSL_LN instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CONFORMED_CON_PRPSL_PRPSL_LN fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence _ID;
   private long PROPOSAL_LINE_ID;
   private java.lang.Long PARENT_PROPOSAL_LINE_ID;
   private java.lang.Long PRPSL_LN_KEY_ID;
   private java.lang.Long PRPSL_LN_QTR_KEY_ID;
   private long PROPOSAL_ID;
   private java.lang.Long FLIGHT_ID;
   private java.lang.Long OTLT_EXT_ID;
   private java.lang.Double SELLING_ROTATION_KEY;
   private java.lang.Long PKG_SLLNG_RTTN_TYP_ID;
   private java.lang.Long PRPSL_LN_COST_TYP_ID;
   private java.lang.Long PKG_PRD_VRSN_RLS_ID;
   private java.lang.Double SELLING_ROTATION_CATEGORY_KEY;
   private java.lang.Long ROTATION_PERIOD_RELEASE_ID;
   private java.lang.Long SALES_INVENTORY_TYPE_ID;
   private java.lang.Long RATE_CARD_ID;
   private java.lang.Long EQV_RTS_IND;
   private java.lang.Double AGENCY_COMMISSION;
   private java.lang.Long CURRENCY_KEY;
   private java.lang.Long TELEVISION_PROPOSAL_ID;
   private java.lang.Long AD_UNIT_SCHD_ALOCTN_TYP_ID;
   private java.lang.CharSequence SRC_KEY_VAL;
   private java.lang.CharSequence SRC_CDC_OPER_NM;
   private java.lang.CharSequence SRC_COMMIT_DT_UTC;
   private java.lang.CharSequence TRG_CRT_DT_PART_UTC;
   private java.lang.CharSequence SRC_SCHEMA_NM;
   private java.lang.CharSequence LAST_MODIFIED_BY;
   private java.lang.CharSequence LAST_MODIFIED_DT;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CONFORMED_CON_PRPSL_PRPSL_LN() {}

  /**
   * All-args constructor.
   * @param _ID The new value for _ID
   * @param PROPOSAL_LINE_ID The new value for PROPOSAL_LINE_ID
   * @param PARENT_PROPOSAL_LINE_ID The new value for PARENT_PROPOSAL_LINE_ID
   * @param PRPSL_LN_KEY_ID The new value for PRPSL_LN_KEY_ID
   * @param PRPSL_LN_QTR_KEY_ID The new value for PRPSL_LN_QTR_KEY_ID
   * @param PROPOSAL_ID The new value for PROPOSAL_ID
   * @param FLIGHT_ID The new value for FLIGHT_ID
   * @param OTLT_EXT_ID The new value for OTLT_EXT_ID
   * @param SELLING_ROTATION_KEY The new value for SELLING_ROTATION_KEY
   * @param PKG_SLLNG_RTTN_TYP_ID The new value for PKG_SLLNG_RTTN_TYP_ID
   * @param PRPSL_LN_COST_TYP_ID The new value for PRPSL_LN_COST_TYP_ID
   * @param PKG_PRD_VRSN_RLS_ID The new value for PKG_PRD_VRSN_RLS_ID
   * @param SELLING_ROTATION_CATEGORY_KEY The new value for SELLING_ROTATION_CATEGORY_KEY
   * @param ROTATION_PERIOD_RELEASE_ID The new value for ROTATION_PERIOD_RELEASE_ID
   * @param SALES_INVENTORY_TYPE_ID The new value for SALES_INVENTORY_TYPE_ID
   * @param RATE_CARD_ID The new value for RATE_CARD_ID
   * @param EQV_RTS_IND The new value for EQV_RTS_IND
   * @param AGENCY_COMMISSION The new value for AGENCY_COMMISSION
   * @param CURRENCY_KEY The new value for CURRENCY_KEY
   * @param TELEVISION_PROPOSAL_ID The new value for TELEVISION_PROPOSAL_ID
   * @param AD_UNIT_SCHD_ALOCTN_TYP_ID The new value for AD_UNIT_SCHD_ALOCTN_TYP_ID
   * @param SRC_KEY_VAL The new value for SRC_KEY_VAL
   * @param SRC_CDC_OPER_NM The new value for SRC_CDC_OPER_NM
   * @param SRC_COMMIT_DT_UTC The new value for SRC_COMMIT_DT_UTC
   * @param TRG_CRT_DT_PART_UTC The new value for TRG_CRT_DT_PART_UTC
   * @param SRC_SCHEMA_NM The new value for SRC_SCHEMA_NM
   * @param LAST_MODIFIED_BY The new value for LAST_MODIFIED_BY
   * @param LAST_MODIFIED_DT The new value for LAST_MODIFIED_DT
   */
  public CONFORMED_CON_PRPSL_PRPSL_LN(java.lang.CharSequence _ID, java.lang.Long PROPOSAL_LINE_ID, java.lang.Long PARENT_PROPOSAL_LINE_ID, java.lang.Long PRPSL_LN_KEY_ID, java.lang.Long PRPSL_LN_QTR_KEY_ID, java.lang.Long PROPOSAL_ID, java.lang.Long FLIGHT_ID, java.lang.Long OTLT_EXT_ID, java.lang.Double SELLING_ROTATION_KEY, java.lang.Long PKG_SLLNG_RTTN_TYP_ID, java.lang.Long PRPSL_LN_COST_TYP_ID, java.lang.Long PKG_PRD_VRSN_RLS_ID, java.lang.Double SELLING_ROTATION_CATEGORY_KEY, java.lang.Long ROTATION_PERIOD_RELEASE_ID, java.lang.Long SALES_INVENTORY_TYPE_ID, java.lang.Long RATE_CARD_ID, java.lang.Long EQV_RTS_IND, java.lang.Double AGENCY_COMMISSION, java.lang.Long CURRENCY_KEY, java.lang.Long TELEVISION_PROPOSAL_ID, java.lang.Long AD_UNIT_SCHD_ALOCTN_TYP_ID, java.lang.CharSequence SRC_KEY_VAL, java.lang.CharSequence SRC_CDC_OPER_NM, java.lang.CharSequence SRC_COMMIT_DT_UTC, java.lang.CharSequence TRG_CRT_DT_PART_UTC, java.lang.CharSequence SRC_SCHEMA_NM, java.lang.CharSequence LAST_MODIFIED_BY, java.lang.CharSequence LAST_MODIFIED_DT) {
    this._ID = _ID;
    this.PROPOSAL_LINE_ID = PROPOSAL_LINE_ID;
    this.PARENT_PROPOSAL_LINE_ID = PARENT_PROPOSAL_LINE_ID;
    this.PRPSL_LN_KEY_ID = PRPSL_LN_KEY_ID;
    this.PRPSL_LN_QTR_KEY_ID = PRPSL_LN_QTR_KEY_ID;
    this.PROPOSAL_ID = PROPOSAL_ID;
    this.FLIGHT_ID = FLIGHT_ID;
    this.OTLT_EXT_ID = OTLT_EXT_ID;
    this.SELLING_ROTATION_KEY = SELLING_ROTATION_KEY;
    this.PKG_SLLNG_RTTN_TYP_ID = PKG_SLLNG_RTTN_TYP_ID;
    this.PRPSL_LN_COST_TYP_ID = PRPSL_LN_COST_TYP_ID;
    this.PKG_PRD_VRSN_RLS_ID = PKG_PRD_VRSN_RLS_ID;
    this.SELLING_ROTATION_CATEGORY_KEY = SELLING_ROTATION_CATEGORY_KEY;
    this.ROTATION_PERIOD_RELEASE_ID = ROTATION_PERIOD_RELEASE_ID;
    this.SALES_INVENTORY_TYPE_ID = SALES_INVENTORY_TYPE_ID;
    this.RATE_CARD_ID = RATE_CARD_ID;
    this.EQV_RTS_IND = EQV_RTS_IND;
    this.AGENCY_COMMISSION = AGENCY_COMMISSION;
    this.CURRENCY_KEY = CURRENCY_KEY;
    this.TELEVISION_PROPOSAL_ID = TELEVISION_PROPOSAL_ID;
    this.AD_UNIT_SCHD_ALOCTN_TYP_ID = AD_UNIT_SCHD_ALOCTN_TYP_ID;
    this.SRC_KEY_VAL = SRC_KEY_VAL;
    this.SRC_CDC_OPER_NM = SRC_CDC_OPER_NM;
    this.SRC_COMMIT_DT_UTC = SRC_COMMIT_DT_UTC;
    this.TRG_CRT_DT_PART_UTC = TRG_CRT_DT_PART_UTC;
    this.SRC_SCHEMA_NM = SRC_SCHEMA_NM;
    this.LAST_MODIFIED_BY = LAST_MODIFIED_BY;
    this.LAST_MODIFIED_DT = LAST_MODIFIED_DT;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return _ID;
    case 1: return PROPOSAL_LINE_ID;
    case 2: return PARENT_PROPOSAL_LINE_ID;
    case 3: return PRPSL_LN_KEY_ID;
    case 4: return PRPSL_LN_QTR_KEY_ID;
    case 5: return PROPOSAL_ID;
    case 6: return FLIGHT_ID;
    case 7: return OTLT_EXT_ID;
    case 8: return SELLING_ROTATION_KEY;
    case 9: return PKG_SLLNG_RTTN_TYP_ID;
    case 10: return PRPSL_LN_COST_TYP_ID;
    case 11: return PKG_PRD_VRSN_RLS_ID;
    case 12: return SELLING_ROTATION_CATEGORY_KEY;
    case 13: return ROTATION_PERIOD_RELEASE_ID;
    case 14: return SALES_INVENTORY_TYPE_ID;
    case 15: return RATE_CARD_ID;
    case 16: return EQV_RTS_IND;
    case 17: return AGENCY_COMMISSION;
    case 18: return CURRENCY_KEY;
    case 19: return TELEVISION_PROPOSAL_ID;
    case 20: return AD_UNIT_SCHD_ALOCTN_TYP_ID;
    case 21: return SRC_KEY_VAL;
    case 22: return SRC_CDC_OPER_NM;
    case 23: return SRC_COMMIT_DT_UTC;
    case 24: return TRG_CRT_DT_PART_UTC;
    case 25: return SRC_SCHEMA_NM;
    case 26: return LAST_MODIFIED_BY;
    case 27: return LAST_MODIFIED_DT;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: _ID = (java.lang.CharSequence)value$; break;
    case 1: PROPOSAL_LINE_ID = (java.lang.Long)value$; break;
    case 2: PARENT_PROPOSAL_LINE_ID = (java.lang.Long)value$; break;
    case 3: PRPSL_LN_KEY_ID = (java.lang.Long)value$; break;
    case 4: PRPSL_LN_QTR_KEY_ID = (java.lang.Long)value$; break;
    case 5: PROPOSAL_ID = (java.lang.Long)value$; break;
    case 6: FLIGHT_ID = (java.lang.Long)value$; break;
    case 7: OTLT_EXT_ID = (java.lang.Long)value$; break;
    case 8: SELLING_ROTATION_KEY = (java.lang.Double)value$; break;
    case 9: PKG_SLLNG_RTTN_TYP_ID = (java.lang.Long)value$; break;
    case 10: PRPSL_LN_COST_TYP_ID = (java.lang.Long)value$; break;
    case 11: PKG_PRD_VRSN_RLS_ID = (java.lang.Long)value$; break;
    case 12: SELLING_ROTATION_CATEGORY_KEY = (java.lang.Double)value$; break;
    case 13: ROTATION_PERIOD_RELEASE_ID = (java.lang.Long)value$; break;
    case 14: SALES_INVENTORY_TYPE_ID = (java.lang.Long)value$; break;
    case 15: RATE_CARD_ID = (java.lang.Long)value$; break;
    case 16: EQV_RTS_IND = (java.lang.Long)value$; break;
    case 17: AGENCY_COMMISSION = (java.lang.Double)value$; break;
    case 18: CURRENCY_KEY = (java.lang.Long)value$; break;
    case 19: TELEVISION_PROPOSAL_ID = (java.lang.Long)value$; break;
    case 20: AD_UNIT_SCHD_ALOCTN_TYP_ID = (java.lang.Long)value$; break;
    case 21: SRC_KEY_VAL = (java.lang.CharSequence)value$; break;
    case 22: SRC_CDC_OPER_NM = (java.lang.CharSequence)value$; break;
    case 23: SRC_COMMIT_DT_UTC = (java.lang.CharSequence)value$; break;
    case 24: TRG_CRT_DT_PART_UTC = (java.lang.CharSequence)value$; break;
    case 25: SRC_SCHEMA_NM = (java.lang.CharSequence)value$; break;
    case 26: LAST_MODIFIED_BY = (java.lang.CharSequence)value$; break;
    case 27: LAST_MODIFIED_DT = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the '_ID' field.
   * @return The value of the '_ID' field.
   */
  public java.lang.CharSequence getID$1() {
    return _ID;
  }


  /**
   * Sets the value of the '_ID' field.
   * @param value the value to set.
   */
  public void setID$1(java.lang.CharSequence value) {
    this._ID = value;
  }

  /**
   * Gets the value of the 'PROPOSAL_LINE_ID' field.
   * @return The value of the 'PROPOSAL_LINE_ID' field.
   */
  public long getPROPOSALLINEID() {
    return PROPOSAL_LINE_ID;
  }


  /**
   * Sets the value of the 'PROPOSAL_LINE_ID' field.
   * @param value the value to set.
   */
  public void setPROPOSALLINEID(long value) {
    this.PROPOSAL_LINE_ID = value;
  }

  /**
   * Gets the value of the 'PARENT_PROPOSAL_LINE_ID' field.
   * @return The value of the 'PARENT_PROPOSAL_LINE_ID' field.
   */
  public java.lang.Long getPARENTPROPOSALLINEID() {
    return PARENT_PROPOSAL_LINE_ID;
  }


  /**
   * Sets the value of the 'PARENT_PROPOSAL_LINE_ID' field.
   * @param value the value to set.
   */
  public void setPARENTPROPOSALLINEID(java.lang.Long value) {
    this.PARENT_PROPOSAL_LINE_ID = value;
  }

  /**
   * Gets the value of the 'PRPSL_LN_KEY_ID' field.
   * @return The value of the 'PRPSL_LN_KEY_ID' field.
   */
  public java.lang.Long getPRPSLLNKEYID() {
    return PRPSL_LN_KEY_ID;
  }


  /**
   * Sets the value of the 'PRPSL_LN_KEY_ID' field.
   * @param value the value to set.
   */
  public void setPRPSLLNKEYID(java.lang.Long value) {
    this.PRPSL_LN_KEY_ID = value;
  }

  /**
   * Gets the value of the 'PRPSL_LN_QTR_KEY_ID' field.
   * @return The value of the 'PRPSL_LN_QTR_KEY_ID' field.
   */
  public java.lang.Long getPRPSLLNQTRKEYID() {
    return PRPSL_LN_QTR_KEY_ID;
  }


  /**
   * Sets the value of the 'PRPSL_LN_QTR_KEY_ID' field.
   * @param value the value to set.
   */
  public void setPRPSLLNQTRKEYID(java.lang.Long value) {
    this.PRPSL_LN_QTR_KEY_ID = value;
  }

  /**
   * Gets the value of the 'PROPOSAL_ID' field.
   * @return The value of the 'PROPOSAL_ID' field.
   */
  public long getPROPOSALID() {
    return PROPOSAL_ID;
  }


  /**
   * Sets the value of the 'PROPOSAL_ID' field.
   * @param value the value to set.
   */
  public void setPROPOSALID(long value) {
    this.PROPOSAL_ID = value;
  }

  /**
   * Gets the value of the 'FLIGHT_ID' field.
   * @return The value of the 'FLIGHT_ID' field.
   */
  public java.lang.Long getFLIGHTID() {
    return FLIGHT_ID;
  }


  /**
   * Sets the value of the 'FLIGHT_ID' field.
   * @param value the value to set.
   */
  public void setFLIGHTID(java.lang.Long value) {
    this.FLIGHT_ID = value;
  }

  /**
   * Gets the value of the 'OTLT_EXT_ID' field.
   * @return The value of the 'OTLT_EXT_ID' field.
   */
  public java.lang.Long getOTLTEXTID() {
    return OTLT_EXT_ID;
  }


  /**
   * Sets the value of the 'OTLT_EXT_ID' field.
   * @param value the value to set.
   */
  public void setOTLTEXTID(java.lang.Long value) {
    this.OTLT_EXT_ID = value;
  }

  /**
   * Gets the value of the 'SELLING_ROTATION_KEY' field.
   * @return The value of the 'SELLING_ROTATION_KEY' field.
   */
  public java.lang.Double getSELLINGROTATIONKEY() {
    return SELLING_ROTATION_KEY;
  }


  /**
   * Sets the value of the 'SELLING_ROTATION_KEY' field.
   * @param value the value to set.
   */
  public void setSELLINGROTATIONKEY(java.lang.Double value) {
    this.SELLING_ROTATION_KEY = value;
  }

  /**
   * Gets the value of the 'PKG_SLLNG_RTTN_TYP_ID' field.
   * @return The value of the 'PKG_SLLNG_RTTN_TYP_ID' field.
   */
  public java.lang.Long getPKGSLLNGRTTNTYPID() {
    return PKG_SLLNG_RTTN_TYP_ID;
  }


  /**
   * Sets the value of the 'PKG_SLLNG_RTTN_TYP_ID' field.
   * @param value the value to set.
   */
  public void setPKGSLLNGRTTNTYPID(java.lang.Long value) {
    this.PKG_SLLNG_RTTN_TYP_ID = value;
  }

  /**
   * Gets the value of the 'PRPSL_LN_COST_TYP_ID' field.
   * @return The value of the 'PRPSL_LN_COST_TYP_ID' field.
   */
  public java.lang.Long getPRPSLLNCOSTTYPID() {
    return PRPSL_LN_COST_TYP_ID;
  }


  /**
   * Sets the value of the 'PRPSL_LN_COST_TYP_ID' field.
   * @param value the value to set.
   */
  public void setPRPSLLNCOSTTYPID(java.lang.Long value) {
    this.PRPSL_LN_COST_TYP_ID = value;
  }

  /**
   * Gets the value of the 'PKG_PRD_VRSN_RLS_ID' field.
   * @return The value of the 'PKG_PRD_VRSN_RLS_ID' field.
   */
  public java.lang.Long getPKGPRDVRSNRLSID() {
    return PKG_PRD_VRSN_RLS_ID;
  }


  /**
   * Sets the value of the 'PKG_PRD_VRSN_RLS_ID' field.
   * @param value the value to set.
   */
  public void setPKGPRDVRSNRLSID(java.lang.Long value) {
    this.PKG_PRD_VRSN_RLS_ID = value;
  }

  /**
   * Gets the value of the 'SELLING_ROTATION_CATEGORY_KEY' field.
   * @return The value of the 'SELLING_ROTATION_CATEGORY_KEY' field.
   */
  public java.lang.Double getSELLINGROTATIONCATEGORYKEY() {
    return SELLING_ROTATION_CATEGORY_KEY;
  }


  /**
   * Sets the value of the 'SELLING_ROTATION_CATEGORY_KEY' field.
   * @param value the value to set.
   */
  public void setSELLINGROTATIONCATEGORYKEY(java.lang.Double value) {
    this.SELLING_ROTATION_CATEGORY_KEY = value;
  }

  /**
   * Gets the value of the 'ROTATION_PERIOD_RELEASE_ID' field.
   * @return The value of the 'ROTATION_PERIOD_RELEASE_ID' field.
   */
  public java.lang.Long getROTATIONPERIODRELEASEID() {
    return ROTATION_PERIOD_RELEASE_ID;
  }


  /**
   * Sets the value of the 'ROTATION_PERIOD_RELEASE_ID' field.
   * @param value the value to set.
   */
  public void setROTATIONPERIODRELEASEID(java.lang.Long value) {
    this.ROTATION_PERIOD_RELEASE_ID = value;
  }

  /**
   * Gets the value of the 'SALES_INVENTORY_TYPE_ID' field.
   * @return The value of the 'SALES_INVENTORY_TYPE_ID' field.
   */
  public java.lang.Long getSALESINVENTORYTYPEID() {
    return SALES_INVENTORY_TYPE_ID;
  }


  /**
   * Sets the value of the 'SALES_INVENTORY_TYPE_ID' field.
   * @param value the value to set.
   */
  public void setSALESINVENTORYTYPEID(java.lang.Long value) {
    this.SALES_INVENTORY_TYPE_ID = value;
  }

  /**
   * Gets the value of the 'RATE_CARD_ID' field.
   * @return The value of the 'RATE_CARD_ID' field.
   */
  public java.lang.Long getRATECARDID() {
    return RATE_CARD_ID;
  }


  /**
   * Sets the value of the 'RATE_CARD_ID' field.
   * @param value the value to set.
   */
  public void setRATECARDID(java.lang.Long value) {
    this.RATE_CARD_ID = value;
  }

  /**
   * Gets the value of the 'EQV_RTS_IND' field.
   * @return The value of the 'EQV_RTS_IND' field.
   */
  public java.lang.Long getEQVRTSIND() {
    return EQV_RTS_IND;
  }


  /**
   * Sets the value of the 'EQV_RTS_IND' field.
   * @param value the value to set.
   */
  public void setEQVRTSIND(java.lang.Long value) {
    this.EQV_RTS_IND = value;
  }

  /**
   * Gets the value of the 'AGENCY_COMMISSION' field.
   * @return The value of the 'AGENCY_COMMISSION' field.
   */
  public java.lang.Double getAGENCYCOMMISSION() {
    return AGENCY_COMMISSION;
  }


  /**
   * Sets the value of the 'AGENCY_COMMISSION' field.
   * @param value the value to set.
   */
  public void setAGENCYCOMMISSION(java.lang.Double value) {
    this.AGENCY_COMMISSION = value;
  }

  /**
   * Gets the value of the 'CURRENCY_KEY' field.
   * @return The value of the 'CURRENCY_KEY' field.
   */
  public java.lang.Long getCURRENCYKEY() {
    return CURRENCY_KEY;
  }


  /**
   * Sets the value of the 'CURRENCY_KEY' field.
   * @param value the value to set.
   */
  public void setCURRENCYKEY(java.lang.Long value) {
    this.CURRENCY_KEY = value;
  }

  /**
   * Gets the value of the 'TELEVISION_PROPOSAL_ID' field.
   * @return The value of the 'TELEVISION_PROPOSAL_ID' field.
   */
  public java.lang.Long getTELEVISIONPROPOSALID() {
    return TELEVISION_PROPOSAL_ID;
  }


  /**
   * Sets the value of the 'TELEVISION_PROPOSAL_ID' field.
   * @param value the value to set.
   */
  public void setTELEVISIONPROPOSALID(java.lang.Long value) {
    this.TELEVISION_PROPOSAL_ID = value;
  }

  /**
   * Gets the value of the 'AD_UNIT_SCHD_ALOCTN_TYP_ID' field.
   * @return The value of the 'AD_UNIT_SCHD_ALOCTN_TYP_ID' field.
   */
  public java.lang.Long getADUNITSCHDALOCTNTYPID() {
    return AD_UNIT_SCHD_ALOCTN_TYP_ID;
  }


  /**
   * Sets the value of the 'AD_UNIT_SCHD_ALOCTN_TYP_ID' field.
   * @param value the value to set.
   */
  public void setADUNITSCHDALOCTNTYPID(java.lang.Long value) {
    this.AD_UNIT_SCHD_ALOCTN_TYP_ID = value;
  }

  /**
   * Gets the value of the 'SRC_KEY_VAL' field.
   * @return The value of the 'SRC_KEY_VAL' field.
   */
  public java.lang.CharSequence getSRCKEYVAL() {
    return SRC_KEY_VAL;
  }


  /**
   * Sets the value of the 'SRC_KEY_VAL' field.
   * @param value the value to set.
   */
  public void setSRCKEYVAL(java.lang.CharSequence value) {
    this.SRC_KEY_VAL = value;
  }

  /**
   * Gets the value of the 'SRC_CDC_OPER_NM' field.
   * @return The value of the 'SRC_CDC_OPER_NM' field.
   */
  public java.lang.CharSequence getSRCCDCOPERNM() {
    return SRC_CDC_OPER_NM;
  }


  /**
   * Sets the value of the 'SRC_CDC_OPER_NM' field.
   * @param value the value to set.
   */
  public void setSRCCDCOPERNM(java.lang.CharSequence value) {
    this.SRC_CDC_OPER_NM = value;
  }

  /**
   * Gets the value of the 'SRC_COMMIT_DT_UTC' field.
   * @return The value of the 'SRC_COMMIT_DT_UTC' field.
   */
  public java.lang.CharSequence getSRCCOMMITDTUTC() {
    return SRC_COMMIT_DT_UTC;
  }


  /**
   * Sets the value of the 'SRC_COMMIT_DT_UTC' field.
   * @param value the value to set.
   */
  public void setSRCCOMMITDTUTC(java.lang.CharSequence value) {
    this.SRC_COMMIT_DT_UTC = value;
  }

  /**
   * Gets the value of the 'TRG_CRT_DT_PART_UTC' field.
   * @return The value of the 'TRG_CRT_DT_PART_UTC' field.
   */
  public java.lang.CharSequence getTRGCRTDTPARTUTC() {
    return TRG_CRT_DT_PART_UTC;
  }


  /**
   * Sets the value of the 'TRG_CRT_DT_PART_UTC' field.
   * @param value the value to set.
   */
  public void setTRGCRTDTPARTUTC(java.lang.CharSequence value) {
    this.TRG_CRT_DT_PART_UTC = value;
  }

  /**
   * Gets the value of the 'SRC_SCHEMA_NM' field.
   * @return The value of the 'SRC_SCHEMA_NM' field.
   */
  public java.lang.CharSequence getSRCSCHEMANM() {
    return SRC_SCHEMA_NM;
  }


  /**
   * Sets the value of the 'SRC_SCHEMA_NM' field.
   * @param value the value to set.
   */
  public void setSRCSCHEMANM(java.lang.CharSequence value) {
    this.SRC_SCHEMA_NM = value;
  }

  /**
   * Gets the value of the 'LAST_MODIFIED_BY' field.
   * @return The value of the 'LAST_MODIFIED_BY' field.
   */
  public java.lang.CharSequence getLASTMODIFIEDBY() {
    return LAST_MODIFIED_BY;
  }


  /**
   * Sets the value of the 'LAST_MODIFIED_BY' field.
   * @param value the value to set.
   */
  public void setLASTMODIFIEDBY(java.lang.CharSequence value) {
    this.LAST_MODIFIED_BY = value;
  }

  /**
   * Gets the value of the 'LAST_MODIFIED_DT' field.
   * @return The value of the 'LAST_MODIFIED_DT' field.
   */
  public java.lang.CharSequence getLASTMODIFIEDDT() {
    return LAST_MODIFIED_DT;
  }


  /**
   * Sets the value of the 'LAST_MODIFIED_DT' field.
   * @param value the value to set.
   */
  public void setLASTMODIFIEDDT(java.lang.CharSequence value) {
    this.LAST_MODIFIED_DT = value;
  }

  /**
   * Creates a new CONFORMED_CON_PRPSL_PRPSL_LN RecordBuilder.
   * @return A new CONFORMED_CON_PRPSL_PRPSL_LN RecordBuilder
   */
  public static org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder newBuilder() {
    return new org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder();
  }

  /**
   * Creates a new CONFORMED_CON_PRPSL_PRPSL_LN RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CONFORMED_CON_PRPSL_PRPSL_LN RecordBuilder
   */
  public static org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder newBuilder(org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder other) {
    if (other == null) {
      return new org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder();
    } else {
      return new org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder(other);
    }
  }

  /**
   * Creates a new CONFORMED_CON_PRPSL_PRPSL_LN RecordBuilder by copying an existing CONFORMED_CON_PRPSL_PRPSL_LN instance.
   * @param other The existing instance to copy.
   * @return A new CONFORMED_CON_PRPSL_PRPSL_LN RecordBuilder
   */
  public static org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder newBuilder(org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN other) {
    if (other == null) {
      return new org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder();
    } else {
      return new org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder(other);
    }
  }

  /**
   * RecordBuilder for CONFORMED_CON_PRPSL_PRPSL_LN instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CONFORMED_CON_PRPSL_PRPSL_LN>
    implements org.apache.avro.data.RecordBuilder<CONFORMED_CON_PRPSL_PRPSL_LN> {

    private java.lang.CharSequence _ID;
    private long PROPOSAL_LINE_ID;
    private java.lang.Long PARENT_PROPOSAL_LINE_ID;
    private java.lang.Long PRPSL_LN_KEY_ID;
    private java.lang.Long PRPSL_LN_QTR_KEY_ID;
    private long PROPOSAL_ID;
    private java.lang.Long FLIGHT_ID;
    private java.lang.Long OTLT_EXT_ID;
    private java.lang.Double SELLING_ROTATION_KEY;
    private java.lang.Long PKG_SLLNG_RTTN_TYP_ID;
    private java.lang.Long PRPSL_LN_COST_TYP_ID;
    private java.lang.Long PKG_PRD_VRSN_RLS_ID;
    private java.lang.Double SELLING_ROTATION_CATEGORY_KEY;
    private java.lang.Long ROTATION_PERIOD_RELEASE_ID;
    private java.lang.Long SALES_INVENTORY_TYPE_ID;
    private java.lang.Long RATE_CARD_ID;
    private java.lang.Long EQV_RTS_IND;
    private java.lang.Double AGENCY_COMMISSION;
    private java.lang.Long CURRENCY_KEY;
    private java.lang.Long TELEVISION_PROPOSAL_ID;
    private java.lang.Long AD_UNIT_SCHD_ALOCTN_TYP_ID;
    private java.lang.CharSequence SRC_KEY_VAL;
    private java.lang.CharSequence SRC_CDC_OPER_NM;
    private java.lang.CharSequence SRC_COMMIT_DT_UTC;
    private java.lang.CharSequence TRG_CRT_DT_PART_UTC;
    private java.lang.CharSequence SRC_SCHEMA_NM;
    private java.lang.CharSequence LAST_MODIFIED_BY;
    private java.lang.CharSequence LAST_MODIFIED_DT;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other._ID)) {
        this._ID = data().deepCopy(fields()[0].schema(), other._ID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.PROPOSAL_LINE_ID)) {
        this.PROPOSAL_LINE_ID = data().deepCopy(fields()[1].schema(), other.PROPOSAL_LINE_ID);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.PARENT_PROPOSAL_LINE_ID)) {
        this.PARENT_PROPOSAL_LINE_ID = data().deepCopy(fields()[2].schema(), other.PARENT_PROPOSAL_LINE_ID);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.PRPSL_LN_KEY_ID)) {
        this.PRPSL_LN_KEY_ID = data().deepCopy(fields()[3].schema(), other.PRPSL_LN_KEY_ID);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.PRPSL_LN_QTR_KEY_ID)) {
        this.PRPSL_LN_QTR_KEY_ID = data().deepCopy(fields()[4].schema(), other.PRPSL_LN_QTR_KEY_ID);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.PROPOSAL_ID)) {
        this.PROPOSAL_ID = data().deepCopy(fields()[5].schema(), other.PROPOSAL_ID);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.FLIGHT_ID)) {
        this.FLIGHT_ID = data().deepCopy(fields()[6].schema(), other.FLIGHT_ID);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.OTLT_EXT_ID)) {
        this.OTLT_EXT_ID = data().deepCopy(fields()[7].schema(), other.OTLT_EXT_ID);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.SELLING_ROTATION_KEY)) {
        this.SELLING_ROTATION_KEY = data().deepCopy(fields()[8].schema(), other.SELLING_ROTATION_KEY);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.PKG_SLLNG_RTTN_TYP_ID)) {
        this.PKG_SLLNG_RTTN_TYP_ID = data().deepCopy(fields()[9].schema(), other.PKG_SLLNG_RTTN_TYP_ID);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.PRPSL_LN_COST_TYP_ID)) {
        this.PRPSL_LN_COST_TYP_ID = data().deepCopy(fields()[10].schema(), other.PRPSL_LN_COST_TYP_ID);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.PKG_PRD_VRSN_RLS_ID)) {
        this.PKG_PRD_VRSN_RLS_ID = data().deepCopy(fields()[11].schema(), other.PKG_PRD_VRSN_RLS_ID);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.SELLING_ROTATION_CATEGORY_KEY)) {
        this.SELLING_ROTATION_CATEGORY_KEY = data().deepCopy(fields()[12].schema(), other.SELLING_ROTATION_CATEGORY_KEY);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.ROTATION_PERIOD_RELEASE_ID)) {
        this.ROTATION_PERIOD_RELEASE_ID = data().deepCopy(fields()[13].schema(), other.ROTATION_PERIOD_RELEASE_ID);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.SALES_INVENTORY_TYPE_ID)) {
        this.SALES_INVENTORY_TYPE_ID = data().deepCopy(fields()[14].schema(), other.SALES_INVENTORY_TYPE_ID);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.RATE_CARD_ID)) {
        this.RATE_CARD_ID = data().deepCopy(fields()[15].schema(), other.RATE_CARD_ID);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
      if (isValidValue(fields()[16], other.EQV_RTS_IND)) {
        this.EQV_RTS_IND = data().deepCopy(fields()[16].schema(), other.EQV_RTS_IND);
        fieldSetFlags()[16] = other.fieldSetFlags()[16];
      }
      if (isValidValue(fields()[17], other.AGENCY_COMMISSION)) {
        this.AGENCY_COMMISSION = data().deepCopy(fields()[17].schema(), other.AGENCY_COMMISSION);
        fieldSetFlags()[17] = other.fieldSetFlags()[17];
      }
      if (isValidValue(fields()[18], other.CURRENCY_KEY)) {
        this.CURRENCY_KEY = data().deepCopy(fields()[18].schema(), other.CURRENCY_KEY);
        fieldSetFlags()[18] = other.fieldSetFlags()[18];
      }
      if (isValidValue(fields()[19], other.TELEVISION_PROPOSAL_ID)) {
        this.TELEVISION_PROPOSAL_ID = data().deepCopy(fields()[19].schema(), other.TELEVISION_PROPOSAL_ID);
        fieldSetFlags()[19] = other.fieldSetFlags()[19];
      }
      if (isValidValue(fields()[20], other.AD_UNIT_SCHD_ALOCTN_TYP_ID)) {
        this.AD_UNIT_SCHD_ALOCTN_TYP_ID = data().deepCopy(fields()[20].schema(), other.AD_UNIT_SCHD_ALOCTN_TYP_ID);
        fieldSetFlags()[20] = other.fieldSetFlags()[20];
      }
      if (isValidValue(fields()[21], other.SRC_KEY_VAL)) {
        this.SRC_KEY_VAL = data().deepCopy(fields()[21].schema(), other.SRC_KEY_VAL);
        fieldSetFlags()[21] = other.fieldSetFlags()[21];
      }
      if (isValidValue(fields()[22], other.SRC_CDC_OPER_NM)) {
        this.SRC_CDC_OPER_NM = data().deepCopy(fields()[22].schema(), other.SRC_CDC_OPER_NM);
        fieldSetFlags()[22] = other.fieldSetFlags()[22];
      }
      if (isValidValue(fields()[23], other.SRC_COMMIT_DT_UTC)) {
        this.SRC_COMMIT_DT_UTC = data().deepCopy(fields()[23].schema(), other.SRC_COMMIT_DT_UTC);
        fieldSetFlags()[23] = other.fieldSetFlags()[23];
      }
      if (isValidValue(fields()[24], other.TRG_CRT_DT_PART_UTC)) {
        this.TRG_CRT_DT_PART_UTC = data().deepCopy(fields()[24].schema(), other.TRG_CRT_DT_PART_UTC);
        fieldSetFlags()[24] = other.fieldSetFlags()[24];
      }
      if (isValidValue(fields()[25], other.SRC_SCHEMA_NM)) {
        this.SRC_SCHEMA_NM = data().deepCopy(fields()[25].schema(), other.SRC_SCHEMA_NM);
        fieldSetFlags()[25] = other.fieldSetFlags()[25];
      }
      if (isValidValue(fields()[26], other.LAST_MODIFIED_BY)) {
        this.LAST_MODIFIED_BY = data().deepCopy(fields()[26].schema(), other.LAST_MODIFIED_BY);
        fieldSetFlags()[26] = other.fieldSetFlags()[26];
      }
      if (isValidValue(fields()[27], other.LAST_MODIFIED_DT)) {
        this.LAST_MODIFIED_DT = data().deepCopy(fields()[27].schema(), other.LAST_MODIFIED_DT);
        fieldSetFlags()[27] = other.fieldSetFlags()[27];
      }
    }

    /**
     * Creates a Builder by copying an existing CONFORMED_CON_PRPSL_PRPSL_LN instance
     * @param other The existing instance to copy.
     */
    private Builder(org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other._ID)) {
        this._ID = data().deepCopy(fields()[0].schema(), other._ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.PROPOSAL_LINE_ID)) {
        this.PROPOSAL_LINE_ID = data().deepCopy(fields()[1].schema(), other.PROPOSAL_LINE_ID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.PARENT_PROPOSAL_LINE_ID)) {
        this.PARENT_PROPOSAL_LINE_ID = data().deepCopy(fields()[2].schema(), other.PARENT_PROPOSAL_LINE_ID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.PRPSL_LN_KEY_ID)) {
        this.PRPSL_LN_KEY_ID = data().deepCopy(fields()[3].schema(), other.PRPSL_LN_KEY_ID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.PRPSL_LN_QTR_KEY_ID)) {
        this.PRPSL_LN_QTR_KEY_ID = data().deepCopy(fields()[4].schema(), other.PRPSL_LN_QTR_KEY_ID);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.PROPOSAL_ID)) {
        this.PROPOSAL_ID = data().deepCopy(fields()[5].schema(), other.PROPOSAL_ID);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.FLIGHT_ID)) {
        this.FLIGHT_ID = data().deepCopy(fields()[6].schema(), other.FLIGHT_ID);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.OTLT_EXT_ID)) {
        this.OTLT_EXT_ID = data().deepCopy(fields()[7].schema(), other.OTLT_EXT_ID);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.SELLING_ROTATION_KEY)) {
        this.SELLING_ROTATION_KEY = data().deepCopy(fields()[8].schema(), other.SELLING_ROTATION_KEY);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.PKG_SLLNG_RTTN_TYP_ID)) {
        this.PKG_SLLNG_RTTN_TYP_ID = data().deepCopy(fields()[9].schema(), other.PKG_SLLNG_RTTN_TYP_ID);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.PRPSL_LN_COST_TYP_ID)) {
        this.PRPSL_LN_COST_TYP_ID = data().deepCopy(fields()[10].schema(), other.PRPSL_LN_COST_TYP_ID);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.PKG_PRD_VRSN_RLS_ID)) {
        this.PKG_PRD_VRSN_RLS_ID = data().deepCopy(fields()[11].schema(), other.PKG_PRD_VRSN_RLS_ID);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.SELLING_ROTATION_CATEGORY_KEY)) {
        this.SELLING_ROTATION_CATEGORY_KEY = data().deepCopy(fields()[12].schema(), other.SELLING_ROTATION_CATEGORY_KEY);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.ROTATION_PERIOD_RELEASE_ID)) {
        this.ROTATION_PERIOD_RELEASE_ID = data().deepCopy(fields()[13].schema(), other.ROTATION_PERIOD_RELEASE_ID);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.SALES_INVENTORY_TYPE_ID)) {
        this.SALES_INVENTORY_TYPE_ID = data().deepCopy(fields()[14].schema(), other.SALES_INVENTORY_TYPE_ID);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.RATE_CARD_ID)) {
        this.RATE_CARD_ID = data().deepCopy(fields()[15].schema(), other.RATE_CARD_ID);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.EQV_RTS_IND)) {
        this.EQV_RTS_IND = data().deepCopy(fields()[16].schema(), other.EQV_RTS_IND);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.AGENCY_COMMISSION)) {
        this.AGENCY_COMMISSION = data().deepCopy(fields()[17].schema(), other.AGENCY_COMMISSION);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.CURRENCY_KEY)) {
        this.CURRENCY_KEY = data().deepCopy(fields()[18].schema(), other.CURRENCY_KEY);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.TELEVISION_PROPOSAL_ID)) {
        this.TELEVISION_PROPOSAL_ID = data().deepCopy(fields()[19].schema(), other.TELEVISION_PROPOSAL_ID);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.AD_UNIT_SCHD_ALOCTN_TYP_ID)) {
        this.AD_UNIT_SCHD_ALOCTN_TYP_ID = data().deepCopy(fields()[20].schema(), other.AD_UNIT_SCHD_ALOCTN_TYP_ID);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.SRC_KEY_VAL)) {
        this.SRC_KEY_VAL = data().deepCopy(fields()[21].schema(), other.SRC_KEY_VAL);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.SRC_CDC_OPER_NM)) {
        this.SRC_CDC_OPER_NM = data().deepCopy(fields()[22].schema(), other.SRC_CDC_OPER_NM);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.SRC_COMMIT_DT_UTC)) {
        this.SRC_COMMIT_DT_UTC = data().deepCopy(fields()[23].schema(), other.SRC_COMMIT_DT_UTC);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.TRG_CRT_DT_PART_UTC)) {
        this.TRG_CRT_DT_PART_UTC = data().deepCopy(fields()[24].schema(), other.TRG_CRT_DT_PART_UTC);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.SRC_SCHEMA_NM)) {
        this.SRC_SCHEMA_NM = data().deepCopy(fields()[25].schema(), other.SRC_SCHEMA_NM);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.LAST_MODIFIED_BY)) {
        this.LAST_MODIFIED_BY = data().deepCopy(fields()[26].schema(), other.LAST_MODIFIED_BY);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.LAST_MODIFIED_DT)) {
        this.LAST_MODIFIED_DT = data().deepCopy(fields()[27].schema(), other.LAST_MODIFIED_DT);
        fieldSetFlags()[27] = true;
      }
    }

    /**
      * Gets the value of the '_ID' field.
      * @return The value.
      */
    public java.lang.CharSequence getID$1() {
      return _ID;
    }


    /**
      * Sets the value of the '_ID' field.
      * @param value The value of '_ID'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setID$1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this._ID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the '_ID' field has been set.
      * @return True if the '_ID' field has been set, false otherwise.
      */
    public boolean hasID$1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the '_ID' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearID$1() {
      _ID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'PROPOSAL_LINE_ID' field.
      * @return The value.
      */
    public long getPROPOSALLINEID() {
      return PROPOSAL_LINE_ID;
    }


    /**
      * Sets the value of the 'PROPOSAL_LINE_ID' field.
      * @param value The value of 'PROPOSAL_LINE_ID'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setPROPOSALLINEID(long value) {
      validate(fields()[1], value);
      this.PROPOSAL_LINE_ID = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'PROPOSAL_LINE_ID' field has been set.
      * @return True if the 'PROPOSAL_LINE_ID' field has been set, false otherwise.
      */
    public boolean hasPROPOSALLINEID() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'PROPOSAL_LINE_ID' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearPROPOSALLINEID() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'PARENT_PROPOSAL_LINE_ID' field.
      * @return The value.
      */
    public java.lang.Long getPARENTPROPOSALLINEID() {
      return PARENT_PROPOSAL_LINE_ID;
    }


    /**
      * Sets the value of the 'PARENT_PROPOSAL_LINE_ID' field.
      * @param value The value of 'PARENT_PROPOSAL_LINE_ID'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setPARENTPROPOSALLINEID(java.lang.Long value) {
      validate(fields()[2], value);
      this.PARENT_PROPOSAL_LINE_ID = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'PARENT_PROPOSAL_LINE_ID' field has been set.
      * @return True if the 'PARENT_PROPOSAL_LINE_ID' field has been set, false otherwise.
      */
    public boolean hasPARENTPROPOSALLINEID() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'PARENT_PROPOSAL_LINE_ID' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearPARENTPROPOSALLINEID() {
      PARENT_PROPOSAL_LINE_ID = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'PRPSL_LN_KEY_ID' field.
      * @return The value.
      */
    public java.lang.Long getPRPSLLNKEYID() {
      return PRPSL_LN_KEY_ID;
    }


    /**
      * Sets the value of the 'PRPSL_LN_KEY_ID' field.
      * @param value The value of 'PRPSL_LN_KEY_ID'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setPRPSLLNKEYID(java.lang.Long value) {
      validate(fields()[3], value);
      this.PRPSL_LN_KEY_ID = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'PRPSL_LN_KEY_ID' field has been set.
      * @return True if the 'PRPSL_LN_KEY_ID' field has been set, false otherwise.
      */
    public boolean hasPRPSLLNKEYID() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'PRPSL_LN_KEY_ID' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearPRPSLLNKEYID() {
      PRPSL_LN_KEY_ID = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'PRPSL_LN_QTR_KEY_ID' field.
      * @return The value.
      */
    public java.lang.Long getPRPSLLNQTRKEYID() {
      return PRPSL_LN_QTR_KEY_ID;
    }


    /**
      * Sets the value of the 'PRPSL_LN_QTR_KEY_ID' field.
      * @param value The value of 'PRPSL_LN_QTR_KEY_ID'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setPRPSLLNQTRKEYID(java.lang.Long value) {
      validate(fields()[4], value);
      this.PRPSL_LN_QTR_KEY_ID = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'PRPSL_LN_QTR_KEY_ID' field has been set.
      * @return True if the 'PRPSL_LN_QTR_KEY_ID' field has been set, false otherwise.
      */
    public boolean hasPRPSLLNQTRKEYID() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'PRPSL_LN_QTR_KEY_ID' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearPRPSLLNQTRKEYID() {
      PRPSL_LN_QTR_KEY_ID = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'PROPOSAL_ID' field.
      * @return The value.
      */
    public long getPROPOSALID() {
      return PROPOSAL_ID;
    }


    /**
      * Sets the value of the 'PROPOSAL_ID' field.
      * @param value The value of 'PROPOSAL_ID'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setPROPOSALID(long value) {
      validate(fields()[5], value);
      this.PROPOSAL_ID = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'PROPOSAL_ID' field has been set.
      * @return True if the 'PROPOSAL_ID' field has been set, false otherwise.
      */
    public boolean hasPROPOSALID() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'PROPOSAL_ID' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearPROPOSALID() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'FLIGHT_ID' field.
      * @return The value.
      */
    public java.lang.Long getFLIGHTID() {
      return FLIGHT_ID;
    }


    /**
      * Sets the value of the 'FLIGHT_ID' field.
      * @param value The value of 'FLIGHT_ID'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setFLIGHTID(java.lang.Long value) {
      validate(fields()[6], value);
      this.FLIGHT_ID = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'FLIGHT_ID' field has been set.
      * @return True if the 'FLIGHT_ID' field has been set, false otherwise.
      */
    public boolean hasFLIGHTID() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'FLIGHT_ID' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearFLIGHTID() {
      FLIGHT_ID = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'OTLT_EXT_ID' field.
      * @return The value.
      */
    public java.lang.Long getOTLTEXTID() {
      return OTLT_EXT_ID;
    }


    /**
      * Sets the value of the 'OTLT_EXT_ID' field.
      * @param value The value of 'OTLT_EXT_ID'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setOTLTEXTID(java.lang.Long value) {
      validate(fields()[7], value);
      this.OTLT_EXT_ID = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'OTLT_EXT_ID' field has been set.
      * @return True if the 'OTLT_EXT_ID' field has been set, false otherwise.
      */
    public boolean hasOTLTEXTID() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'OTLT_EXT_ID' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearOTLTEXTID() {
      OTLT_EXT_ID = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'SELLING_ROTATION_KEY' field.
      * @return The value.
      */
    public java.lang.Double getSELLINGROTATIONKEY() {
      return SELLING_ROTATION_KEY;
    }


    /**
      * Sets the value of the 'SELLING_ROTATION_KEY' field.
      * @param value The value of 'SELLING_ROTATION_KEY'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setSELLINGROTATIONKEY(java.lang.Double value) {
      validate(fields()[8], value);
      this.SELLING_ROTATION_KEY = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'SELLING_ROTATION_KEY' field has been set.
      * @return True if the 'SELLING_ROTATION_KEY' field has been set, false otherwise.
      */
    public boolean hasSELLINGROTATIONKEY() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'SELLING_ROTATION_KEY' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearSELLINGROTATIONKEY() {
      SELLING_ROTATION_KEY = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'PKG_SLLNG_RTTN_TYP_ID' field.
      * @return The value.
      */
    public java.lang.Long getPKGSLLNGRTTNTYPID() {
      return PKG_SLLNG_RTTN_TYP_ID;
    }


    /**
      * Sets the value of the 'PKG_SLLNG_RTTN_TYP_ID' field.
      * @param value The value of 'PKG_SLLNG_RTTN_TYP_ID'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setPKGSLLNGRTTNTYPID(java.lang.Long value) {
      validate(fields()[9], value);
      this.PKG_SLLNG_RTTN_TYP_ID = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'PKG_SLLNG_RTTN_TYP_ID' field has been set.
      * @return True if the 'PKG_SLLNG_RTTN_TYP_ID' field has been set, false otherwise.
      */
    public boolean hasPKGSLLNGRTTNTYPID() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'PKG_SLLNG_RTTN_TYP_ID' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearPKGSLLNGRTTNTYPID() {
      PKG_SLLNG_RTTN_TYP_ID = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'PRPSL_LN_COST_TYP_ID' field.
      * @return The value.
      */
    public java.lang.Long getPRPSLLNCOSTTYPID() {
      return PRPSL_LN_COST_TYP_ID;
    }


    /**
      * Sets the value of the 'PRPSL_LN_COST_TYP_ID' field.
      * @param value The value of 'PRPSL_LN_COST_TYP_ID'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setPRPSLLNCOSTTYPID(java.lang.Long value) {
      validate(fields()[10], value);
      this.PRPSL_LN_COST_TYP_ID = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'PRPSL_LN_COST_TYP_ID' field has been set.
      * @return True if the 'PRPSL_LN_COST_TYP_ID' field has been set, false otherwise.
      */
    public boolean hasPRPSLLNCOSTTYPID() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'PRPSL_LN_COST_TYP_ID' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearPRPSLLNCOSTTYPID() {
      PRPSL_LN_COST_TYP_ID = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'PKG_PRD_VRSN_RLS_ID' field.
      * @return The value.
      */
    public java.lang.Long getPKGPRDVRSNRLSID() {
      return PKG_PRD_VRSN_RLS_ID;
    }


    /**
      * Sets the value of the 'PKG_PRD_VRSN_RLS_ID' field.
      * @param value The value of 'PKG_PRD_VRSN_RLS_ID'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setPKGPRDVRSNRLSID(java.lang.Long value) {
      validate(fields()[11], value);
      this.PKG_PRD_VRSN_RLS_ID = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'PKG_PRD_VRSN_RLS_ID' field has been set.
      * @return True if the 'PKG_PRD_VRSN_RLS_ID' field has been set, false otherwise.
      */
    public boolean hasPKGPRDVRSNRLSID() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'PKG_PRD_VRSN_RLS_ID' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearPKGPRDVRSNRLSID() {
      PKG_PRD_VRSN_RLS_ID = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'SELLING_ROTATION_CATEGORY_KEY' field.
      * @return The value.
      */
    public java.lang.Double getSELLINGROTATIONCATEGORYKEY() {
      return SELLING_ROTATION_CATEGORY_KEY;
    }


    /**
      * Sets the value of the 'SELLING_ROTATION_CATEGORY_KEY' field.
      * @param value The value of 'SELLING_ROTATION_CATEGORY_KEY'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setSELLINGROTATIONCATEGORYKEY(java.lang.Double value) {
      validate(fields()[12], value);
      this.SELLING_ROTATION_CATEGORY_KEY = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'SELLING_ROTATION_CATEGORY_KEY' field has been set.
      * @return True if the 'SELLING_ROTATION_CATEGORY_KEY' field has been set, false otherwise.
      */
    public boolean hasSELLINGROTATIONCATEGORYKEY() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'SELLING_ROTATION_CATEGORY_KEY' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearSELLINGROTATIONCATEGORYKEY() {
      SELLING_ROTATION_CATEGORY_KEY = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'ROTATION_PERIOD_RELEASE_ID' field.
      * @return The value.
      */
    public java.lang.Long getROTATIONPERIODRELEASEID() {
      return ROTATION_PERIOD_RELEASE_ID;
    }


    /**
      * Sets the value of the 'ROTATION_PERIOD_RELEASE_ID' field.
      * @param value The value of 'ROTATION_PERIOD_RELEASE_ID'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setROTATIONPERIODRELEASEID(java.lang.Long value) {
      validate(fields()[13], value);
      this.ROTATION_PERIOD_RELEASE_ID = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'ROTATION_PERIOD_RELEASE_ID' field has been set.
      * @return True if the 'ROTATION_PERIOD_RELEASE_ID' field has been set, false otherwise.
      */
    public boolean hasROTATIONPERIODRELEASEID() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'ROTATION_PERIOD_RELEASE_ID' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearROTATIONPERIODRELEASEID() {
      ROTATION_PERIOD_RELEASE_ID = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'SALES_INVENTORY_TYPE_ID' field.
      * @return The value.
      */
    public java.lang.Long getSALESINVENTORYTYPEID() {
      return SALES_INVENTORY_TYPE_ID;
    }


    /**
      * Sets the value of the 'SALES_INVENTORY_TYPE_ID' field.
      * @param value The value of 'SALES_INVENTORY_TYPE_ID'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setSALESINVENTORYTYPEID(java.lang.Long value) {
      validate(fields()[14], value);
      this.SALES_INVENTORY_TYPE_ID = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'SALES_INVENTORY_TYPE_ID' field has been set.
      * @return True if the 'SALES_INVENTORY_TYPE_ID' field has been set, false otherwise.
      */
    public boolean hasSALESINVENTORYTYPEID() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'SALES_INVENTORY_TYPE_ID' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearSALESINVENTORYTYPEID() {
      SALES_INVENTORY_TYPE_ID = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'RATE_CARD_ID' field.
      * @return The value.
      */
    public java.lang.Long getRATECARDID() {
      return RATE_CARD_ID;
    }


    /**
      * Sets the value of the 'RATE_CARD_ID' field.
      * @param value The value of 'RATE_CARD_ID'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setRATECARDID(java.lang.Long value) {
      validate(fields()[15], value);
      this.RATE_CARD_ID = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'RATE_CARD_ID' field has been set.
      * @return True if the 'RATE_CARD_ID' field has been set, false otherwise.
      */
    public boolean hasRATECARDID() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'RATE_CARD_ID' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearRATECARDID() {
      RATE_CARD_ID = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'EQV_RTS_IND' field.
      * @return The value.
      */
    public java.lang.Long getEQVRTSIND() {
      return EQV_RTS_IND;
    }


    /**
      * Sets the value of the 'EQV_RTS_IND' field.
      * @param value The value of 'EQV_RTS_IND'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setEQVRTSIND(java.lang.Long value) {
      validate(fields()[16], value);
      this.EQV_RTS_IND = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'EQV_RTS_IND' field has been set.
      * @return True if the 'EQV_RTS_IND' field has been set, false otherwise.
      */
    public boolean hasEQVRTSIND() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'EQV_RTS_IND' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearEQVRTSIND() {
      EQV_RTS_IND = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'AGENCY_COMMISSION' field.
      * @return The value.
      */
    public java.lang.Double getAGENCYCOMMISSION() {
      return AGENCY_COMMISSION;
    }


    /**
      * Sets the value of the 'AGENCY_COMMISSION' field.
      * @param value The value of 'AGENCY_COMMISSION'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setAGENCYCOMMISSION(java.lang.Double value) {
      validate(fields()[17], value);
      this.AGENCY_COMMISSION = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'AGENCY_COMMISSION' field has been set.
      * @return True if the 'AGENCY_COMMISSION' field has been set, false otherwise.
      */
    public boolean hasAGENCYCOMMISSION() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'AGENCY_COMMISSION' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearAGENCYCOMMISSION() {
      AGENCY_COMMISSION = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'CURRENCY_KEY' field.
      * @return The value.
      */
    public java.lang.Long getCURRENCYKEY() {
      return CURRENCY_KEY;
    }


    /**
      * Sets the value of the 'CURRENCY_KEY' field.
      * @param value The value of 'CURRENCY_KEY'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setCURRENCYKEY(java.lang.Long value) {
      validate(fields()[18], value);
      this.CURRENCY_KEY = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'CURRENCY_KEY' field has been set.
      * @return True if the 'CURRENCY_KEY' field has been set, false otherwise.
      */
    public boolean hasCURRENCYKEY() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'CURRENCY_KEY' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearCURRENCYKEY() {
      CURRENCY_KEY = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'TELEVISION_PROPOSAL_ID' field.
      * @return The value.
      */
    public java.lang.Long getTELEVISIONPROPOSALID() {
      return TELEVISION_PROPOSAL_ID;
    }


    /**
      * Sets the value of the 'TELEVISION_PROPOSAL_ID' field.
      * @param value The value of 'TELEVISION_PROPOSAL_ID'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setTELEVISIONPROPOSALID(java.lang.Long value) {
      validate(fields()[19], value);
      this.TELEVISION_PROPOSAL_ID = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'TELEVISION_PROPOSAL_ID' field has been set.
      * @return True if the 'TELEVISION_PROPOSAL_ID' field has been set, false otherwise.
      */
    public boolean hasTELEVISIONPROPOSALID() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'TELEVISION_PROPOSAL_ID' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearTELEVISIONPROPOSALID() {
      TELEVISION_PROPOSAL_ID = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'AD_UNIT_SCHD_ALOCTN_TYP_ID' field.
      * @return The value.
      */
    public java.lang.Long getADUNITSCHDALOCTNTYPID() {
      return AD_UNIT_SCHD_ALOCTN_TYP_ID;
    }


    /**
      * Sets the value of the 'AD_UNIT_SCHD_ALOCTN_TYP_ID' field.
      * @param value The value of 'AD_UNIT_SCHD_ALOCTN_TYP_ID'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setADUNITSCHDALOCTNTYPID(java.lang.Long value) {
      validate(fields()[20], value);
      this.AD_UNIT_SCHD_ALOCTN_TYP_ID = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'AD_UNIT_SCHD_ALOCTN_TYP_ID' field has been set.
      * @return True if the 'AD_UNIT_SCHD_ALOCTN_TYP_ID' field has been set, false otherwise.
      */
    public boolean hasADUNITSCHDALOCTNTYPID() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'AD_UNIT_SCHD_ALOCTN_TYP_ID' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearADUNITSCHDALOCTNTYPID() {
      AD_UNIT_SCHD_ALOCTN_TYP_ID = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'SRC_KEY_VAL' field.
      * @return The value.
      */
    public java.lang.CharSequence getSRCKEYVAL() {
      return SRC_KEY_VAL;
    }


    /**
      * Sets the value of the 'SRC_KEY_VAL' field.
      * @param value The value of 'SRC_KEY_VAL'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setSRCKEYVAL(java.lang.CharSequence value) {
      validate(fields()[21], value);
      this.SRC_KEY_VAL = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'SRC_KEY_VAL' field has been set.
      * @return True if the 'SRC_KEY_VAL' field has been set, false otherwise.
      */
    public boolean hasSRCKEYVAL() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'SRC_KEY_VAL' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearSRCKEYVAL() {
      SRC_KEY_VAL = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    /**
      * Gets the value of the 'SRC_CDC_OPER_NM' field.
      * @return The value.
      */
    public java.lang.CharSequence getSRCCDCOPERNM() {
      return SRC_CDC_OPER_NM;
    }


    /**
      * Sets the value of the 'SRC_CDC_OPER_NM' field.
      * @param value The value of 'SRC_CDC_OPER_NM'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setSRCCDCOPERNM(java.lang.CharSequence value) {
      validate(fields()[22], value);
      this.SRC_CDC_OPER_NM = value;
      fieldSetFlags()[22] = true;
      return this;
    }

    /**
      * Checks whether the 'SRC_CDC_OPER_NM' field has been set.
      * @return True if the 'SRC_CDC_OPER_NM' field has been set, false otherwise.
      */
    public boolean hasSRCCDCOPERNM() {
      return fieldSetFlags()[22];
    }


    /**
      * Clears the value of the 'SRC_CDC_OPER_NM' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearSRCCDCOPERNM() {
      SRC_CDC_OPER_NM = null;
      fieldSetFlags()[22] = false;
      return this;
    }

    /**
      * Gets the value of the 'SRC_COMMIT_DT_UTC' field.
      * @return The value.
      */
    public java.lang.CharSequence getSRCCOMMITDTUTC() {
      return SRC_COMMIT_DT_UTC;
    }


    /**
      * Sets the value of the 'SRC_COMMIT_DT_UTC' field.
      * @param value The value of 'SRC_COMMIT_DT_UTC'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setSRCCOMMITDTUTC(java.lang.CharSequence value) {
      validate(fields()[23], value);
      this.SRC_COMMIT_DT_UTC = value;
      fieldSetFlags()[23] = true;
      return this;
    }

    /**
      * Checks whether the 'SRC_COMMIT_DT_UTC' field has been set.
      * @return True if the 'SRC_COMMIT_DT_UTC' field has been set, false otherwise.
      */
    public boolean hasSRCCOMMITDTUTC() {
      return fieldSetFlags()[23];
    }


    /**
      * Clears the value of the 'SRC_COMMIT_DT_UTC' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearSRCCOMMITDTUTC() {
      SRC_COMMIT_DT_UTC = null;
      fieldSetFlags()[23] = false;
      return this;
    }

    /**
      * Gets the value of the 'TRG_CRT_DT_PART_UTC' field.
      * @return The value.
      */
    public java.lang.CharSequence getTRGCRTDTPARTUTC() {
      return TRG_CRT_DT_PART_UTC;
    }


    /**
      * Sets the value of the 'TRG_CRT_DT_PART_UTC' field.
      * @param value The value of 'TRG_CRT_DT_PART_UTC'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setTRGCRTDTPARTUTC(java.lang.CharSequence value) {
      validate(fields()[24], value);
      this.TRG_CRT_DT_PART_UTC = value;
      fieldSetFlags()[24] = true;
      return this;
    }

    /**
      * Checks whether the 'TRG_CRT_DT_PART_UTC' field has been set.
      * @return True if the 'TRG_CRT_DT_PART_UTC' field has been set, false otherwise.
      */
    public boolean hasTRGCRTDTPARTUTC() {
      return fieldSetFlags()[24];
    }


    /**
      * Clears the value of the 'TRG_CRT_DT_PART_UTC' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearTRGCRTDTPARTUTC() {
      TRG_CRT_DT_PART_UTC = null;
      fieldSetFlags()[24] = false;
      return this;
    }

    /**
      * Gets the value of the 'SRC_SCHEMA_NM' field.
      * @return The value.
      */
    public java.lang.CharSequence getSRCSCHEMANM() {
      return SRC_SCHEMA_NM;
    }


    /**
      * Sets the value of the 'SRC_SCHEMA_NM' field.
      * @param value The value of 'SRC_SCHEMA_NM'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setSRCSCHEMANM(java.lang.CharSequence value) {
      validate(fields()[25], value);
      this.SRC_SCHEMA_NM = value;
      fieldSetFlags()[25] = true;
      return this;
    }

    /**
      * Checks whether the 'SRC_SCHEMA_NM' field has been set.
      * @return True if the 'SRC_SCHEMA_NM' field has been set, false otherwise.
      */
    public boolean hasSRCSCHEMANM() {
      return fieldSetFlags()[25];
    }


    /**
      * Clears the value of the 'SRC_SCHEMA_NM' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearSRCSCHEMANM() {
      SRC_SCHEMA_NM = null;
      fieldSetFlags()[25] = false;
      return this;
    }

    /**
      * Gets the value of the 'LAST_MODIFIED_BY' field.
      * @return The value.
      */
    public java.lang.CharSequence getLASTMODIFIEDBY() {
      return LAST_MODIFIED_BY;
    }


    /**
      * Sets the value of the 'LAST_MODIFIED_BY' field.
      * @param value The value of 'LAST_MODIFIED_BY'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setLASTMODIFIEDBY(java.lang.CharSequence value) {
      validate(fields()[26], value);
      this.LAST_MODIFIED_BY = value;
      fieldSetFlags()[26] = true;
      return this;
    }

    /**
      * Checks whether the 'LAST_MODIFIED_BY' field has been set.
      * @return True if the 'LAST_MODIFIED_BY' field has been set, false otherwise.
      */
    public boolean hasLASTMODIFIEDBY() {
      return fieldSetFlags()[26];
    }


    /**
      * Clears the value of the 'LAST_MODIFIED_BY' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearLASTMODIFIEDBY() {
      LAST_MODIFIED_BY = null;
      fieldSetFlags()[26] = false;
      return this;
    }

    /**
      * Gets the value of the 'LAST_MODIFIED_DT' field.
      * @return The value.
      */
    public java.lang.CharSequence getLASTMODIFIEDDT() {
      return LAST_MODIFIED_DT;
    }


    /**
      * Sets the value of the 'LAST_MODIFIED_DT' field.
      * @param value The value of 'LAST_MODIFIED_DT'.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder setLASTMODIFIEDDT(java.lang.CharSequence value) {
      validate(fields()[27], value);
      this.LAST_MODIFIED_DT = value;
      fieldSetFlags()[27] = true;
      return this;
    }

    /**
      * Checks whether the 'LAST_MODIFIED_DT' field has been set.
      * @return True if the 'LAST_MODIFIED_DT' field has been set, false otherwise.
      */
    public boolean hasLASTMODIFIEDDT() {
      return fieldSetFlags()[27];
    }


    /**
      * Clears the value of the 'LAST_MODIFIED_DT' field.
      * @return This builder.
      */
    public org.apache.nifi.custom.joined.CONFORMED_CON_PRPSL_PRPSL_LN.Builder clearLASTMODIFIEDDT() {
      LAST_MODIFIED_DT = null;
      fieldSetFlags()[27] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CONFORMED_CON_PRPSL_PRPSL_LN build() {
      try {
        CONFORMED_CON_PRPSL_PRPSL_LN record = new CONFORMED_CON_PRPSL_PRPSL_LN();
        record._ID = fieldSetFlags()[0] ? this._ID : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.PROPOSAL_LINE_ID = fieldSetFlags()[1] ? this.PROPOSAL_LINE_ID : (java.lang.Long) defaultValue(fields()[1]);
        record.PARENT_PROPOSAL_LINE_ID = fieldSetFlags()[2] ? this.PARENT_PROPOSAL_LINE_ID : (java.lang.Long) defaultValue(fields()[2]);
        record.PRPSL_LN_KEY_ID = fieldSetFlags()[3] ? this.PRPSL_LN_KEY_ID : (java.lang.Long) defaultValue(fields()[3]);
        record.PRPSL_LN_QTR_KEY_ID = fieldSetFlags()[4] ? this.PRPSL_LN_QTR_KEY_ID : (java.lang.Long) defaultValue(fields()[4]);
        record.PROPOSAL_ID = fieldSetFlags()[5] ? this.PROPOSAL_ID : (java.lang.Long) defaultValue(fields()[5]);
        record.FLIGHT_ID = fieldSetFlags()[6] ? this.FLIGHT_ID : (java.lang.Long) defaultValue(fields()[6]);
        record.OTLT_EXT_ID = fieldSetFlags()[7] ? this.OTLT_EXT_ID : (java.lang.Long) defaultValue(fields()[7]);
        record.SELLING_ROTATION_KEY = fieldSetFlags()[8] ? this.SELLING_ROTATION_KEY : (java.lang.Double) defaultValue(fields()[8]);
        record.PKG_SLLNG_RTTN_TYP_ID = fieldSetFlags()[9] ? this.PKG_SLLNG_RTTN_TYP_ID : (java.lang.Long) defaultValue(fields()[9]);
        record.PRPSL_LN_COST_TYP_ID = fieldSetFlags()[10] ? this.PRPSL_LN_COST_TYP_ID : (java.lang.Long) defaultValue(fields()[10]);
        record.PKG_PRD_VRSN_RLS_ID = fieldSetFlags()[11] ? this.PKG_PRD_VRSN_RLS_ID : (java.lang.Long) defaultValue(fields()[11]);
        record.SELLING_ROTATION_CATEGORY_KEY = fieldSetFlags()[12] ? this.SELLING_ROTATION_CATEGORY_KEY : (java.lang.Double) defaultValue(fields()[12]);
        record.ROTATION_PERIOD_RELEASE_ID = fieldSetFlags()[13] ? this.ROTATION_PERIOD_RELEASE_ID : (java.lang.Long) defaultValue(fields()[13]);
        record.SALES_INVENTORY_TYPE_ID = fieldSetFlags()[14] ? this.SALES_INVENTORY_TYPE_ID : (java.lang.Long) defaultValue(fields()[14]);
        record.RATE_CARD_ID = fieldSetFlags()[15] ? this.RATE_CARD_ID : (java.lang.Long) defaultValue(fields()[15]);
        record.EQV_RTS_IND = fieldSetFlags()[16] ? this.EQV_RTS_IND : (java.lang.Long) defaultValue(fields()[16]);
        record.AGENCY_COMMISSION = fieldSetFlags()[17] ? this.AGENCY_COMMISSION : (java.lang.Double) defaultValue(fields()[17]);
        record.CURRENCY_KEY = fieldSetFlags()[18] ? this.CURRENCY_KEY : (java.lang.Long) defaultValue(fields()[18]);
        record.TELEVISION_PROPOSAL_ID = fieldSetFlags()[19] ? this.TELEVISION_PROPOSAL_ID : (java.lang.Long) defaultValue(fields()[19]);
        record.AD_UNIT_SCHD_ALOCTN_TYP_ID = fieldSetFlags()[20] ? this.AD_UNIT_SCHD_ALOCTN_TYP_ID : (java.lang.Long) defaultValue(fields()[20]);
        record.SRC_KEY_VAL = fieldSetFlags()[21] ? this.SRC_KEY_VAL : (java.lang.CharSequence) defaultValue(fields()[21]);
        record.SRC_CDC_OPER_NM = fieldSetFlags()[22] ? this.SRC_CDC_OPER_NM : (java.lang.CharSequence) defaultValue(fields()[22]);
        record.SRC_COMMIT_DT_UTC = fieldSetFlags()[23] ? this.SRC_COMMIT_DT_UTC : (java.lang.CharSequence) defaultValue(fields()[23]);
        record.TRG_CRT_DT_PART_UTC = fieldSetFlags()[24] ? this.TRG_CRT_DT_PART_UTC : (java.lang.CharSequence) defaultValue(fields()[24]);
        record.SRC_SCHEMA_NM = fieldSetFlags()[25] ? this.SRC_SCHEMA_NM : (java.lang.CharSequence) defaultValue(fields()[25]);
        record.LAST_MODIFIED_BY = fieldSetFlags()[26] ? this.LAST_MODIFIED_BY : (java.lang.CharSequence) defaultValue(fields()[26]);
        record.LAST_MODIFIED_DT = fieldSetFlags()[27] ? this.LAST_MODIFIED_DT : (java.lang.CharSequence) defaultValue(fields()[27]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CONFORMED_CON_PRPSL_PRPSL_LN>
    WRITER$ = (org.apache.avro.io.DatumWriter<CONFORMED_CON_PRPSL_PRPSL_LN>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CONFORMED_CON_PRPSL_PRPSL_LN>
    READER$ = (org.apache.avro.io.DatumReader<CONFORMED_CON_PRPSL_PRPSL_LN>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this._ID);

    out.writeLong(this.PROPOSAL_LINE_ID);

    if (this.PARENT_PROPOSAL_LINE_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.PARENT_PROPOSAL_LINE_ID);
    }

    if (this.PRPSL_LN_KEY_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.PRPSL_LN_KEY_ID);
    }

    if (this.PRPSL_LN_QTR_KEY_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.PRPSL_LN_QTR_KEY_ID);
    }

    out.writeLong(this.PROPOSAL_ID);

    if (this.FLIGHT_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.FLIGHT_ID);
    }

    if (this.OTLT_EXT_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.OTLT_EXT_ID);
    }

    if (this.SELLING_ROTATION_KEY == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.SELLING_ROTATION_KEY);
    }

    if (this.PKG_SLLNG_RTTN_TYP_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.PKG_SLLNG_RTTN_TYP_ID);
    }

    if (this.PRPSL_LN_COST_TYP_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.PRPSL_LN_COST_TYP_ID);
    }

    if (this.PKG_PRD_VRSN_RLS_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.PKG_PRD_VRSN_RLS_ID);
    }

    if (this.SELLING_ROTATION_CATEGORY_KEY == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.SELLING_ROTATION_CATEGORY_KEY);
    }

    if (this.ROTATION_PERIOD_RELEASE_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.ROTATION_PERIOD_RELEASE_ID);
    }

    if (this.SALES_INVENTORY_TYPE_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.SALES_INVENTORY_TYPE_ID);
    }

    if (this.RATE_CARD_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.RATE_CARD_ID);
    }

    if (this.EQV_RTS_IND == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.EQV_RTS_IND);
    }

    if (this.AGENCY_COMMISSION == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.AGENCY_COMMISSION);
    }

    if (this.CURRENCY_KEY == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.CURRENCY_KEY);
    }

    if (this.TELEVISION_PROPOSAL_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.TELEVISION_PROPOSAL_ID);
    }

    if (this.AD_UNIT_SCHD_ALOCTN_TYP_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.AD_UNIT_SCHD_ALOCTN_TYP_ID);
    }

    out.writeString(this.SRC_KEY_VAL);

    out.writeString(this.SRC_CDC_OPER_NM);

    out.writeString(this.SRC_COMMIT_DT_UTC);

    out.writeString(this.TRG_CRT_DT_PART_UTC);

    out.writeString(this.SRC_SCHEMA_NM);

    if (this.LAST_MODIFIED_BY == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.LAST_MODIFIED_BY);
    }

    if (this.LAST_MODIFIED_DT == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.LAST_MODIFIED_DT);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this._ID = in.readString(this._ID instanceof Utf8 ? (Utf8)this._ID : null);

      this.PROPOSAL_LINE_ID = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.PARENT_PROPOSAL_LINE_ID = null;
      } else {
        this.PARENT_PROPOSAL_LINE_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.PRPSL_LN_KEY_ID = null;
      } else {
        this.PRPSL_LN_KEY_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.PRPSL_LN_QTR_KEY_ID = null;
      } else {
        this.PRPSL_LN_QTR_KEY_ID = in.readLong();
      }

      this.PROPOSAL_ID = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.FLIGHT_ID = null;
      } else {
        this.FLIGHT_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.OTLT_EXT_ID = null;
      } else {
        this.OTLT_EXT_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.SELLING_ROTATION_KEY = null;
      } else {
        this.SELLING_ROTATION_KEY = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.PKG_SLLNG_RTTN_TYP_ID = null;
      } else {
        this.PKG_SLLNG_RTTN_TYP_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.PRPSL_LN_COST_TYP_ID = null;
      } else {
        this.PRPSL_LN_COST_TYP_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.PKG_PRD_VRSN_RLS_ID = null;
      } else {
        this.PKG_PRD_VRSN_RLS_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.SELLING_ROTATION_CATEGORY_KEY = null;
      } else {
        this.SELLING_ROTATION_CATEGORY_KEY = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.ROTATION_PERIOD_RELEASE_ID = null;
      } else {
        this.ROTATION_PERIOD_RELEASE_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.SALES_INVENTORY_TYPE_ID = null;
      } else {
        this.SALES_INVENTORY_TYPE_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.RATE_CARD_ID = null;
      } else {
        this.RATE_CARD_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.EQV_RTS_IND = null;
      } else {
        this.EQV_RTS_IND = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.AGENCY_COMMISSION = null;
      } else {
        this.AGENCY_COMMISSION = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.CURRENCY_KEY = null;
      } else {
        this.CURRENCY_KEY = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.TELEVISION_PROPOSAL_ID = null;
      } else {
        this.TELEVISION_PROPOSAL_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.AD_UNIT_SCHD_ALOCTN_TYP_ID = null;
      } else {
        this.AD_UNIT_SCHD_ALOCTN_TYP_ID = in.readLong();
      }

      this.SRC_KEY_VAL = in.readString(this.SRC_KEY_VAL instanceof Utf8 ? (Utf8)this.SRC_KEY_VAL : null);

      this.SRC_CDC_OPER_NM = in.readString(this.SRC_CDC_OPER_NM instanceof Utf8 ? (Utf8)this.SRC_CDC_OPER_NM : null);

      this.SRC_COMMIT_DT_UTC = in.readString(this.SRC_COMMIT_DT_UTC instanceof Utf8 ? (Utf8)this.SRC_COMMIT_DT_UTC : null);

      this.TRG_CRT_DT_PART_UTC = in.readString(this.TRG_CRT_DT_PART_UTC instanceof Utf8 ? (Utf8)this.TRG_CRT_DT_PART_UTC : null);

      this.SRC_SCHEMA_NM = in.readString(this.SRC_SCHEMA_NM instanceof Utf8 ? (Utf8)this.SRC_SCHEMA_NM : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.LAST_MODIFIED_BY = null;
      } else {
        this.LAST_MODIFIED_BY = in.readString(this.LAST_MODIFIED_BY instanceof Utf8 ? (Utf8)this.LAST_MODIFIED_BY : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.LAST_MODIFIED_DT = null;
      } else {
        this.LAST_MODIFIED_DT = in.readString(this.LAST_MODIFIED_DT instanceof Utf8 ? (Utf8)this.LAST_MODIFIED_DT : null);
      }

    } else {
      for (int i = 0; i < 28; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this._ID = in.readString(this._ID instanceof Utf8 ? (Utf8)this._ID : null);
          break;

        case 1:
          this.PROPOSAL_LINE_ID = in.readLong();
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.PARENT_PROPOSAL_LINE_ID = null;
          } else {
            this.PARENT_PROPOSAL_LINE_ID = in.readLong();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.PRPSL_LN_KEY_ID = null;
          } else {
            this.PRPSL_LN_KEY_ID = in.readLong();
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.PRPSL_LN_QTR_KEY_ID = null;
          } else {
            this.PRPSL_LN_QTR_KEY_ID = in.readLong();
          }
          break;

        case 5:
          this.PROPOSAL_ID = in.readLong();
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.FLIGHT_ID = null;
          } else {
            this.FLIGHT_ID = in.readLong();
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.OTLT_EXT_ID = null;
          } else {
            this.OTLT_EXT_ID = in.readLong();
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.SELLING_ROTATION_KEY = null;
          } else {
            this.SELLING_ROTATION_KEY = in.readDouble();
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.PKG_SLLNG_RTTN_TYP_ID = null;
          } else {
            this.PKG_SLLNG_RTTN_TYP_ID = in.readLong();
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.PRPSL_LN_COST_TYP_ID = null;
          } else {
            this.PRPSL_LN_COST_TYP_ID = in.readLong();
          }
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.PKG_PRD_VRSN_RLS_ID = null;
          } else {
            this.PKG_PRD_VRSN_RLS_ID = in.readLong();
          }
          break;

        case 12:
          if (in.readIndex() != 1) {
            in.readNull();
            this.SELLING_ROTATION_CATEGORY_KEY = null;
          } else {
            this.SELLING_ROTATION_CATEGORY_KEY = in.readDouble();
          }
          break;

        case 13:
          if (in.readIndex() != 1) {
            in.readNull();
            this.ROTATION_PERIOD_RELEASE_ID = null;
          } else {
            this.ROTATION_PERIOD_RELEASE_ID = in.readLong();
          }
          break;

        case 14:
          if (in.readIndex() != 1) {
            in.readNull();
            this.SALES_INVENTORY_TYPE_ID = null;
          } else {
            this.SALES_INVENTORY_TYPE_ID = in.readLong();
          }
          break;

        case 15:
          if (in.readIndex() != 1) {
            in.readNull();
            this.RATE_CARD_ID = null;
          } else {
            this.RATE_CARD_ID = in.readLong();
          }
          break;

        case 16:
          if (in.readIndex() != 1) {
            in.readNull();
            this.EQV_RTS_IND = null;
          } else {
            this.EQV_RTS_IND = in.readLong();
          }
          break;

        case 17:
          if (in.readIndex() != 1) {
            in.readNull();
            this.AGENCY_COMMISSION = null;
          } else {
            this.AGENCY_COMMISSION = in.readDouble();
          }
          break;

        case 18:
          if (in.readIndex() != 1) {
            in.readNull();
            this.CURRENCY_KEY = null;
          } else {
            this.CURRENCY_KEY = in.readLong();
          }
          break;

        case 19:
          if (in.readIndex() != 1) {
            in.readNull();
            this.TELEVISION_PROPOSAL_ID = null;
          } else {
            this.TELEVISION_PROPOSAL_ID = in.readLong();
          }
          break;

        case 20:
          if (in.readIndex() != 1) {
            in.readNull();
            this.AD_UNIT_SCHD_ALOCTN_TYP_ID = null;
          } else {
            this.AD_UNIT_SCHD_ALOCTN_TYP_ID = in.readLong();
          }
          break;

        case 21:
          this.SRC_KEY_VAL = in.readString(this.SRC_KEY_VAL instanceof Utf8 ? (Utf8)this.SRC_KEY_VAL : null);
          break;

        case 22:
          this.SRC_CDC_OPER_NM = in.readString(this.SRC_CDC_OPER_NM instanceof Utf8 ? (Utf8)this.SRC_CDC_OPER_NM : null);
          break;

        case 23:
          this.SRC_COMMIT_DT_UTC = in.readString(this.SRC_COMMIT_DT_UTC instanceof Utf8 ? (Utf8)this.SRC_COMMIT_DT_UTC : null);
          break;

        case 24:
          this.TRG_CRT_DT_PART_UTC = in.readString(this.TRG_CRT_DT_PART_UTC instanceof Utf8 ? (Utf8)this.TRG_CRT_DT_PART_UTC : null);
          break;

        case 25:
          this.SRC_SCHEMA_NM = in.readString(this.SRC_SCHEMA_NM instanceof Utf8 ? (Utf8)this.SRC_SCHEMA_NM : null);
          break;

        case 26:
          if (in.readIndex() != 1) {
            in.readNull();
            this.LAST_MODIFIED_BY = null;
          } else {
            this.LAST_MODIFIED_BY = in.readString(this.LAST_MODIFIED_BY instanceof Utf8 ? (Utf8)this.LAST_MODIFIED_BY : null);
          }
          break;

        case 27:
          if (in.readIndex() != 1) {
            in.readNull();
            this.LAST_MODIFIED_DT = null;
          } else {
            this.LAST_MODIFIED_DT = in.readString(this.LAST_MODIFIED_DT instanceof Utf8 ? (Utf8)this.LAST_MODIFIED_DT : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










