/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LNDCDC_ADS_COMMON_OUTLET_EXTENSION extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3181896586498411613L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LNDCDC_ADS_COMMON_OUTLET_EXTENSION\",\"namespace\":\"org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi\",\"fields\":[{\"name\":\"OUTLET_EXTENSION_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"LAST_MODIFIED_BY\",\"type\":[\"null\",\"string\"]},{\"name\":\"LAST_MODIFIED_DT\",\"type\":[\"null\",\"string\"]},{\"name\":\"OUTLET_KEY\",\"type\":[\"null\",\"double\"]},{\"name\":\"DIVISION_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"INACTIVE_DT\",\"type\":[\"null\",\"string\"]},{\"name\":\"REGION_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"OUTLET_CHANNEL_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"MGD_INVNTRY_IND\",\"type\":[\"null\",\"long\"]},{\"name\":\"VLD_FOR_ORDR_IND\",\"type\":[\"null\",\"long\"]},{\"name\":\"SRC_KEY_VAL\",\"type\":\"string\"},{\"name\":\"SRC_CDC_OPER_NM\",\"type\":\"string\"},{\"name\":\"SRC_COMMIT_DT_UTC\",\"type\":\"string\"},{\"name\":\"TRG_CRT_DT_PART_UTC\",\"type\":\"string\"},{\"name\":\"SRC_SCHEMA_NM\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LNDCDC_ADS_COMMON_OUTLET_EXTENSION> ENCODER =
      new BinaryMessageEncoder<LNDCDC_ADS_COMMON_OUTLET_EXTENSION>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LNDCDC_ADS_COMMON_OUTLET_EXTENSION> DECODER =
      new BinaryMessageDecoder<LNDCDC_ADS_COMMON_OUTLET_EXTENSION>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LNDCDC_ADS_COMMON_OUTLET_EXTENSION> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LNDCDC_ADS_COMMON_OUTLET_EXTENSION> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LNDCDC_ADS_COMMON_OUTLET_EXTENSION> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LNDCDC_ADS_COMMON_OUTLET_EXTENSION>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LNDCDC_ADS_COMMON_OUTLET_EXTENSION to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LNDCDC_ADS_COMMON_OUTLET_EXTENSION from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LNDCDC_ADS_COMMON_OUTLET_EXTENSION instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LNDCDC_ADS_COMMON_OUTLET_EXTENSION fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Long OUTLET_EXTENSION_ID;
   private java.lang.CharSequence LAST_MODIFIED_BY;
   private java.lang.CharSequence LAST_MODIFIED_DT;
   private java.lang.Double OUTLET_KEY;
   private java.lang.Long DIVISION_ID;
   private java.lang.CharSequence INACTIVE_DT;
   private java.lang.Long REGION_ID;
   private java.lang.Long OUTLET_CHANNEL_ID;
   private java.lang.Long MGD_INVNTRY_IND;
   private java.lang.Long VLD_FOR_ORDR_IND;
   private java.lang.CharSequence SRC_KEY_VAL;
   private java.lang.CharSequence SRC_CDC_OPER_NM;
   private java.lang.CharSequence SRC_COMMIT_DT_UTC;
   private java.lang.CharSequence TRG_CRT_DT_PART_UTC;
   private java.lang.CharSequence SRC_SCHEMA_NM;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LNDCDC_ADS_COMMON_OUTLET_EXTENSION() {}

  /**
   * All-args constructor.
   * @param OUTLET_EXTENSION_ID The new value for OUTLET_EXTENSION_ID
   * @param LAST_MODIFIED_BY The new value for LAST_MODIFIED_BY
   * @param LAST_MODIFIED_DT The new value for LAST_MODIFIED_DT
   * @param OUTLET_KEY The new value for OUTLET_KEY
   * @param DIVISION_ID The new value for DIVISION_ID
   * @param INACTIVE_DT The new value for INACTIVE_DT
   * @param REGION_ID The new value for REGION_ID
   * @param OUTLET_CHANNEL_ID The new value for OUTLET_CHANNEL_ID
   * @param MGD_INVNTRY_IND The new value for MGD_INVNTRY_IND
   * @param VLD_FOR_ORDR_IND The new value for VLD_FOR_ORDR_IND
   * @param SRC_KEY_VAL The new value for SRC_KEY_VAL
   * @param SRC_CDC_OPER_NM The new value for SRC_CDC_OPER_NM
   * @param SRC_COMMIT_DT_UTC The new value for SRC_COMMIT_DT_UTC
   * @param TRG_CRT_DT_PART_UTC The new value for TRG_CRT_DT_PART_UTC
   * @param SRC_SCHEMA_NM The new value for SRC_SCHEMA_NM
   */
  public LNDCDC_ADS_COMMON_OUTLET_EXTENSION(java.lang.Long OUTLET_EXTENSION_ID, java.lang.CharSequence LAST_MODIFIED_BY, java.lang.CharSequence LAST_MODIFIED_DT, java.lang.Double OUTLET_KEY, java.lang.Long DIVISION_ID, java.lang.CharSequence INACTIVE_DT, java.lang.Long REGION_ID, java.lang.Long OUTLET_CHANNEL_ID, java.lang.Long MGD_INVNTRY_IND, java.lang.Long VLD_FOR_ORDR_IND, java.lang.CharSequence SRC_KEY_VAL, java.lang.CharSequence SRC_CDC_OPER_NM, java.lang.CharSequence SRC_COMMIT_DT_UTC, java.lang.CharSequence TRG_CRT_DT_PART_UTC, java.lang.CharSequence SRC_SCHEMA_NM) {
    this.OUTLET_EXTENSION_ID = OUTLET_EXTENSION_ID;
    this.LAST_MODIFIED_BY = LAST_MODIFIED_BY;
    this.LAST_MODIFIED_DT = LAST_MODIFIED_DT;
    this.OUTLET_KEY = OUTLET_KEY;
    this.DIVISION_ID = DIVISION_ID;
    this.INACTIVE_DT = INACTIVE_DT;
    this.REGION_ID = REGION_ID;
    this.OUTLET_CHANNEL_ID = OUTLET_CHANNEL_ID;
    this.MGD_INVNTRY_IND = MGD_INVNTRY_IND;
    this.VLD_FOR_ORDR_IND = VLD_FOR_ORDR_IND;
    this.SRC_KEY_VAL = SRC_KEY_VAL;
    this.SRC_CDC_OPER_NM = SRC_CDC_OPER_NM;
    this.SRC_COMMIT_DT_UTC = SRC_COMMIT_DT_UTC;
    this.TRG_CRT_DT_PART_UTC = TRG_CRT_DT_PART_UTC;
    this.SRC_SCHEMA_NM = SRC_SCHEMA_NM;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return OUTLET_EXTENSION_ID;
    case 1: return LAST_MODIFIED_BY;
    case 2: return LAST_MODIFIED_DT;
    case 3: return OUTLET_KEY;
    case 4: return DIVISION_ID;
    case 5: return INACTIVE_DT;
    case 6: return REGION_ID;
    case 7: return OUTLET_CHANNEL_ID;
    case 8: return MGD_INVNTRY_IND;
    case 9: return VLD_FOR_ORDR_IND;
    case 10: return SRC_KEY_VAL;
    case 11: return SRC_CDC_OPER_NM;
    case 12: return SRC_COMMIT_DT_UTC;
    case 13: return TRG_CRT_DT_PART_UTC;
    case 14: return SRC_SCHEMA_NM;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: OUTLET_EXTENSION_ID = (java.lang.Long)value$; break;
    case 1: LAST_MODIFIED_BY = (java.lang.CharSequence)value$; break;
    case 2: LAST_MODIFIED_DT = (java.lang.CharSequence)value$; break;
    case 3: OUTLET_KEY = (java.lang.Double)value$; break;
    case 4: DIVISION_ID = (java.lang.Long)value$; break;
    case 5: INACTIVE_DT = (java.lang.CharSequence)value$; break;
    case 6: REGION_ID = (java.lang.Long)value$; break;
    case 7: OUTLET_CHANNEL_ID = (java.lang.Long)value$; break;
    case 8: MGD_INVNTRY_IND = (java.lang.Long)value$; break;
    case 9: VLD_FOR_ORDR_IND = (java.lang.Long)value$; break;
    case 10: SRC_KEY_VAL = (java.lang.CharSequence)value$; break;
    case 11: SRC_CDC_OPER_NM = (java.lang.CharSequence)value$; break;
    case 12: SRC_COMMIT_DT_UTC = (java.lang.CharSequence)value$; break;
    case 13: TRG_CRT_DT_PART_UTC = (java.lang.CharSequence)value$; break;
    case 14: SRC_SCHEMA_NM = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'OUTLET_EXTENSION_ID' field.
   * @return The value of the 'OUTLET_EXTENSION_ID' field.
   */
  public java.lang.Long getOUTLETEXTENSIONID() {
    return OUTLET_EXTENSION_ID;
  }


  /**
   * Sets the value of the 'OUTLET_EXTENSION_ID' field.
   * @param value the value to set.
   */
  public void setOUTLETEXTENSIONID(java.lang.Long value) {
    this.OUTLET_EXTENSION_ID = value;
  }

  /**
   * Gets the value of the 'LAST_MODIFIED_BY' field.
   * @return The value of the 'LAST_MODIFIED_BY' field.
   */
  public java.lang.CharSequence getLASTMODIFIEDBY() {
    return LAST_MODIFIED_BY;
  }


  /**
   * Sets the value of the 'LAST_MODIFIED_BY' field.
   * @param value the value to set.
   */
  public void setLASTMODIFIEDBY(java.lang.CharSequence value) {
    this.LAST_MODIFIED_BY = value;
  }

  /**
   * Gets the value of the 'LAST_MODIFIED_DT' field.
   * @return The value of the 'LAST_MODIFIED_DT' field.
   */
  public java.lang.CharSequence getLASTMODIFIEDDT() {
    return LAST_MODIFIED_DT;
  }


  /**
   * Sets the value of the 'LAST_MODIFIED_DT' field.
   * @param value the value to set.
   */
  public void setLASTMODIFIEDDT(java.lang.CharSequence value) {
    this.LAST_MODIFIED_DT = value;
  }

  /**
   * Gets the value of the 'OUTLET_KEY' field.
   * @return The value of the 'OUTLET_KEY' field.
   */
  public java.lang.Double getOUTLETKEY() {
    return OUTLET_KEY;
  }


  /**
   * Sets the value of the 'OUTLET_KEY' field.
   * @param value the value to set.
   */
  public void setOUTLETKEY(java.lang.Double value) {
    this.OUTLET_KEY = value;
  }

  /**
   * Gets the value of the 'DIVISION_ID' field.
   * @return The value of the 'DIVISION_ID' field.
   */
  public java.lang.Long getDIVISIONID() {
    return DIVISION_ID;
  }


  /**
   * Sets the value of the 'DIVISION_ID' field.
   * @param value the value to set.
   */
  public void setDIVISIONID(java.lang.Long value) {
    this.DIVISION_ID = value;
  }

  /**
   * Gets the value of the 'INACTIVE_DT' field.
   * @return The value of the 'INACTIVE_DT' field.
   */
  public java.lang.CharSequence getINACTIVEDT() {
    return INACTIVE_DT;
  }


  /**
   * Sets the value of the 'INACTIVE_DT' field.
   * @param value the value to set.
   */
  public void setINACTIVEDT(java.lang.CharSequence value) {
    this.INACTIVE_DT = value;
  }

  /**
   * Gets the value of the 'REGION_ID' field.
   * @return The value of the 'REGION_ID' field.
   */
  public java.lang.Long getREGIONID() {
    return REGION_ID;
  }


  /**
   * Sets the value of the 'REGION_ID' field.
   * @param value the value to set.
   */
  public void setREGIONID(java.lang.Long value) {
    this.REGION_ID = value;
  }

  /**
   * Gets the value of the 'OUTLET_CHANNEL_ID' field.
   * @return The value of the 'OUTLET_CHANNEL_ID' field.
   */
  public java.lang.Long getOUTLETCHANNELID() {
    return OUTLET_CHANNEL_ID;
  }


  /**
   * Sets the value of the 'OUTLET_CHANNEL_ID' field.
   * @param value the value to set.
   */
  public void setOUTLETCHANNELID(java.lang.Long value) {
    this.OUTLET_CHANNEL_ID = value;
  }

  /**
   * Gets the value of the 'MGD_INVNTRY_IND' field.
   * @return The value of the 'MGD_INVNTRY_IND' field.
   */
  public java.lang.Long getMGDINVNTRYIND() {
    return MGD_INVNTRY_IND;
  }


  /**
   * Sets the value of the 'MGD_INVNTRY_IND' field.
   * @param value the value to set.
   */
  public void setMGDINVNTRYIND(java.lang.Long value) {
    this.MGD_INVNTRY_IND = value;
  }

  /**
   * Gets the value of the 'VLD_FOR_ORDR_IND' field.
   * @return The value of the 'VLD_FOR_ORDR_IND' field.
   */
  public java.lang.Long getVLDFORORDRIND() {
    return VLD_FOR_ORDR_IND;
  }


  /**
   * Sets the value of the 'VLD_FOR_ORDR_IND' field.
   * @param value the value to set.
   */
  public void setVLDFORORDRIND(java.lang.Long value) {
    this.VLD_FOR_ORDR_IND = value;
  }

  /**
   * Gets the value of the 'SRC_KEY_VAL' field.
   * @return The value of the 'SRC_KEY_VAL' field.
   */
  public java.lang.CharSequence getSRCKEYVAL() {
    return SRC_KEY_VAL;
  }


  /**
   * Sets the value of the 'SRC_KEY_VAL' field.
   * @param value the value to set.
   */
  public void setSRCKEYVAL(java.lang.CharSequence value) {
    this.SRC_KEY_VAL = value;
  }

  /**
   * Gets the value of the 'SRC_CDC_OPER_NM' field.
   * @return The value of the 'SRC_CDC_OPER_NM' field.
   */
  public java.lang.CharSequence getSRCCDCOPERNM() {
    return SRC_CDC_OPER_NM;
  }


  /**
   * Sets the value of the 'SRC_CDC_OPER_NM' field.
   * @param value the value to set.
   */
  public void setSRCCDCOPERNM(java.lang.CharSequence value) {
    this.SRC_CDC_OPER_NM = value;
  }

  /**
   * Gets the value of the 'SRC_COMMIT_DT_UTC' field.
   * @return The value of the 'SRC_COMMIT_DT_UTC' field.
   */
  public java.lang.CharSequence getSRCCOMMITDTUTC() {
    return SRC_COMMIT_DT_UTC;
  }


  /**
   * Sets the value of the 'SRC_COMMIT_DT_UTC' field.
   * @param value the value to set.
   */
  public void setSRCCOMMITDTUTC(java.lang.CharSequence value) {
    this.SRC_COMMIT_DT_UTC = value;
  }

  /**
   * Gets the value of the 'TRG_CRT_DT_PART_UTC' field.
   * @return The value of the 'TRG_CRT_DT_PART_UTC' field.
   */
  public java.lang.CharSequence getTRGCRTDTPARTUTC() {
    return TRG_CRT_DT_PART_UTC;
  }


  /**
   * Sets the value of the 'TRG_CRT_DT_PART_UTC' field.
   * @param value the value to set.
   */
  public void setTRGCRTDTPARTUTC(java.lang.CharSequence value) {
    this.TRG_CRT_DT_PART_UTC = value;
  }

  /**
   * Gets the value of the 'SRC_SCHEMA_NM' field.
   * @return The value of the 'SRC_SCHEMA_NM' field.
   */
  public java.lang.CharSequence getSRCSCHEMANM() {
    return SRC_SCHEMA_NM;
  }


  /**
   * Sets the value of the 'SRC_SCHEMA_NM' field.
   * @param value the value to set.
   */
  public void setSRCSCHEMANM(java.lang.CharSequence value) {
    this.SRC_SCHEMA_NM = value;
  }

  /**
   * Creates a new LNDCDC_ADS_COMMON_OUTLET_EXTENSION RecordBuilder.
   * @return A new LNDCDC_ADS_COMMON_OUTLET_EXTENSION RecordBuilder
   */
  public static org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder newBuilder() {
    return new org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder();
  }

  /**
   * Creates a new LNDCDC_ADS_COMMON_OUTLET_EXTENSION RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LNDCDC_ADS_COMMON_OUTLET_EXTENSION RecordBuilder
   */
  public static org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder newBuilder(org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder other) {
    if (other == null) {
      return new org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder();
    } else {
      return new org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder(other);
    }
  }

  /**
   * Creates a new LNDCDC_ADS_COMMON_OUTLET_EXTENSION RecordBuilder by copying an existing LNDCDC_ADS_COMMON_OUTLET_EXTENSION instance.
   * @param other The existing instance to copy.
   * @return A new LNDCDC_ADS_COMMON_OUTLET_EXTENSION RecordBuilder
   */
  public static org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder newBuilder(org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION other) {
    if (other == null) {
      return new org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder();
    } else {
      return new org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder(other);
    }
  }

  /**
   * RecordBuilder for LNDCDC_ADS_COMMON_OUTLET_EXTENSION instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LNDCDC_ADS_COMMON_OUTLET_EXTENSION>
    implements org.apache.avro.data.RecordBuilder<LNDCDC_ADS_COMMON_OUTLET_EXTENSION> {

    private java.lang.Long OUTLET_EXTENSION_ID;
    private java.lang.CharSequence LAST_MODIFIED_BY;
    private java.lang.CharSequence LAST_MODIFIED_DT;
    private java.lang.Double OUTLET_KEY;
    private java.lang.Long DIVISION_ID;
    private java.lang.CharSequence INACTIVE_DT;
    private java.lang.Long REGION_ID;
    private java.lang.Long OUTLET_CHANNEL_ID;
    private java.lang.Long MGD_INVNTRY_IND;
    private java.lang.Long VLD_FOR_ORDR_IND;
    private java.lang.CharSequence SRC_KEY_VAL;
    private java.lang.CharSequence SRC_CDC_OPER_NM;
    private java.lang.CharSequence SRC_COMMIT_DT_UTC;
    private java.lang.CharSequence TRG_CRT_DT_PART_UTC;
    private java.lang.CharSequence SRC_SCHEMA_NM;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.OUTLET_EXTENSION_ID)) {
        this.OUTLET_EXTENSION_ID = data().deepCopy(fields()[0].schema(), other.OUTLET_EXTENSION_ID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.LAST_MODIFIED_BY)) {
        this.LAST_MODIFIED_BY = data().deepCopy(fields()[1].schema(), other.LAST_MODIFIED_BY);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.LAST_MODIFIED_DT)) {
        this.LAST_MODIFIED_DT = data().deepCopy(fields()[2].schema(), other.LAST_MODIFIED_DT);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.OUTLET_KEY)) {
        this.OUTLET_KEY = data().deepCopy(fields()[3].schema(), other.OUTLET_KEY);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.DIVISION_ID)) {
        this.DIVISION_ID = data().deepCopy(fields()[4].schema(), other.DIVISION_ID);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.INACTIVE_DT)) {
        this.INACTIVE_DT = data().deepCopy(fields()[5].schema(), other.INACTIVE_DT);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.REGION_ID)) {
        this.REGION_ID = data().deepCopy(fields()[6].schema(), other.REGION_ID);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.OUTLET_CHANNEL_ID)) {
        this.OUTLET_CHANNEL_ID = data().deepCopy(fields()[7].schema(), other.OUTLET_CHANNEL_ID);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.MGD_INVNTRY_IND)) {
        this.MGD_INVNTRY_IND = data().deepCopy(fields()[8].schema(), other.MGD_INVNTRY_IND);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.VLD_FOR_ORDR_IND)) {
        this.VLD_FOR_ORDR_IND = data().deepCopy(fields()[9].schema(), other.VLD_FOR_ORDR_IND);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.SRC_KEY_VAL)) {
        this.SRC_KEY_VAL = data().deepCopy(fields()[10].schema(), other.SRC_KEY_VAL);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.SRC_CDC_OPER_NM)) {
        this.SRC_CDC_OPER_NM = data().deepCopy(fields()[11].schema(), other.SRC_CDC_OPER_NM);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.SRC_COMMIT_DT_UTC)) {
        this.SRC_COMMIT_DT_UTC = data().deepCopy(fields()[12].schema(), other.SRC_COMMIT_DT_UTC);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.TRG_CRT_DT_PART_UTC)) {
        this.TRG_CRT_DT_PART_UTC = data().deepCopy(fields()[13].schema(), other.TRG_CRT_DT_PART_UTC);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.SRC_SCHEMA_NM)) {
        this.SRC_SCHEMA_NM = data().deepCopy(fields()[14].schema(), other.SRC_SCHEMA_NM);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
    }

    /**
     * Creates a Builder by copying an existing LNDCDC_ADS_COMMON_OUTLET_EXTENSION instance
     * @param other The existing instance to copy.
     */
    private Builder(org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.OUTLET_EXTENSION_ID)) {
        this.OUTLET_EXTENSION_ID = data().deepCopy(fields()[0].schema(), other.OUTLET_EXTENSION_ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.LAST_MODIFIED_BY)) {
        this.LAST_MODIFIED_BY = data().deepCopy(fields()[1].schema(), other.LAST_MODIFIED_BY);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.LAST_MODIFIED_DT)) {
        this.LAST_MODIFIED_DT = data().deepCopy(fields()[2].schema(), other.LAST_MODIFIED_DT);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.OUTLET_KEY)) {
        this.OUTLET_KEY = data().deepCopy(fields()[3].schema(), other.OUTLET_KEY);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.DIVISION_ID)) {
        this.DIVISION_ID = data().deepCopy(fields()[4].schema(), other.DIVISION_ID);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.INACTIVE_DT)) {
        this.INACTIVE_DT = data().deepCopy(fields()[5].schema(), other.INACTIVE_DT);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.REGION_ID)) {
        this.REGION_ID = data().deepCopy(fields()[6].schema(), other.REGION_ID);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.OUTLET_CHANNEL_ID)) {
        this.OUTLET_CHANNEL_ID = data().deepCopy(fields()[7].schema(), other.OUTLET_CHANNEL_ID);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.MGD_INVNTRY_IND)) {
        this.MGD_INVNTRY_IND = data().deepCopy(fields()[8].schema(), other.MGD_INVNTRY_IND);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.VLD_FOR_ORDR_IND)) {
        this.VLD_FOR_ORDR_IND = data().deepCopy(fields()[9].schema(), other.VLD_FOR_ORDR_IND);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.SRC_KEY_VAL)) {
        this.SRC_KEY_VAL = data().deepCopy(fields()[10].schema(), other.SRC_KEY_VAL);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.SRC_CDC_OPER_NM)) {
        this.SRC_CDC_OPER_NM = data().deepCopy(fields()[11].schema(), other.SRC_CDC_OPER_NM);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.SRC_COMMIT_DT_UTC)) {
        this.SRC_COMMIT_DT_UTC = data().deepCopy(fields()[12].schema(), other.SRC_COMMIT_DT_UTC);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.TRG_CRT_DT_PART_UTC)) {
        this.TRG_CRT_DT_PART_UTC = data().deepCopy(fields()[13].schema(), other.TRG_CRT_DT_PART_UTC);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.SRC_SCHEMA_NM)) {
        this.SRC_SCHEMA_NM = data().deepCopy(fields()[14].schema(), other.SRC_SCHEMA_NM);
        fieldSetFlags()[14] = true;
      }
    }

    /**
      * Gets the value of the 'OUTLET_EXTENSION_ID' field.
      * @return The value.
      */
    public java.lang.Long getOUTLETEXTENSIONID() {
      return OUTLET_EXTENSION_ID;
    }


    /**
      * Sets the value of the 'OUTLET_EXTENSION_ID' field.
      * @param value The value of 'OUTLET_EXTENSION_ID'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder setOUTLETEXTENSIONID(java.lang.Long value) {
      validate(fields()[0], value);
      this.OUTLET_EXTENSION_ID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'OUTLET_EXTENSION_ID' field has been set.
      * @return True if the 'OUTLET_EXTENSION_ID' field has been set, false otherwise.
      */
    public boolean hasOUTLETEXTENSIONID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'OUTLET_EXTENSION_ID' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder clearOUTLETEXTENSIONID() {
      OUTLET_EXTENSION_ID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'LAST_MODIFIED_BY' field.
      * @return The value.
      */
    public java.lang.CharSequence getLASTMODIFIEDBY() {
      return LAST_MODIFIED_BY;
    }


    /**
      * Sets the value of the 'LAST_MODIFIED_BY' field.
      * @param value The value of 'LAST_MODIFIED_BY'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder setLASTMODIFIEDBY(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.LAST_MODIFIED_BY = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'LAST_MODIFIED_BY' field has been set.
      * @return True if the 'LAST_MODIFIED_BY' field has been set, false otherwise.
      */
    public boolean hasLASTMODIFIEDBY() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'LAST_MODIFIED_BY' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder clearLASTMODIFIEDBY() {
      LAST_MODIFIED_BY = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'LAST_MODIFIED_DT' field.
      * @return The value.
      */
    public java.lang.CharSequence getLASTMODIFIEDDT() {
      return LAST_MODIFIED_DT;
    }


    /**
      * Sets the value of the 'LAST_MODIFIED_DT' field.
      * @param value The value of 'LAST_MODIFIED_DT'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder setLASTMODIFIEDDT(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.LAST_MODIFIED_DT = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'LAST_MODIFIED_DT' field has been set.
      * @return True if the 'LAST_MODIFIED_DT' field has been set, false otherwise.
      */
    public boolean hasLASTMODIFIEDDT() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'LAST_MODIFIED_DT' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder clearLASTMODIFIEDDT() {
      LAST_MODIFIED_DT = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'OUTLET_KEY' field.
      * @return The value.
      */
    public java.lang.Double getOUTLETKEY() {
      return OUTLET_KEY;
    }


    /**
      * Sets the value of the 'OUTLET_KEY' field.
      * @param value The value of 'OUTLET_KEY'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder setOUTLETKEY(java.lang.Double value) {
      validate(fields()[3], value);
      this.OUTLET_KEY = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'OUTLET_KEY' field has been set.
      * @return True if the 'OUTLET_KEY' field has been set, false otherwise.
      */
    public boolean hasOUTLETKEY() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'OUTLET_KEY' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder clearOUTLETKEY() {
      OUTLET_KEY = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'DIVISION_ID' field.
      * @return The value.
      */
    public java.lang.Long getDIVISIONID() {
      return DIVISION_ID;
    }


    /**
      * Sets the value of the 'DIVISION_ID' field.
      * @param value The value of 'DIVISION_ID'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder setDIVISIONID(java.lang.Long value) {
      validate(fields()[4], value);
      this.DIVISION_ID = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'DIVISION_ID' field has been set.
      * @return True if the 'DIVISION_ID' field has been set, false otherwise.
      */
    public boolean hasDIVISIONID() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'DIVISION_ID' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder clearDIVISIONID() {
      DIVISION_ID = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'INACTIVE_DT' field.
      * @return The value.
      */
    public java.lang.CharSequence getINACTIVEDT() {
      return INACTIVE_DT;
    }


    /**
      * Sets the value of the 'INACTIVE_DT' field.
      * @param value The value of 'INACTIVE_DT'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder setINACTIVEDT(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.INACTIVE_DT = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'INACTIVE_DT' field has been set.
      * @return True if the 'INACTIVE_DT' field has been set, false otherwise.
      */
    public boolean hasINACTIVEDT() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'INACTIVE_DT' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder clearINACTIVEDT() {
      INACTIVE_DT = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'REGION_ID' field.
      * @return The value.
      */
    public java.lang.Long getREGIONID() {
      return REGION_ID;
    }


    /**
      * Sets the value of the 'REGION_ID' field.
      * @param value The value of 'REGION_ID'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder setREGIONID(java.lang.Long value) {
      validate(fields()[6], value);
      this.REGION_ID = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'REGION_ID' field has been set.
      * @return True if the 'REGION_ID' field has been set, false otherwise.
      */
    public boolean hasREGIONID() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'REGION_ID' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder clearREGIONID() {
      REGION_ID = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'OUTLET_CHANNEL_ID' field.
      * @return The value.
      */
    public java.lang.Long getOUTLETCHANNELID() {
      return OUTLET_CHANNEL_ID;
    }


    /**
      * Sets the value of the 'OUTLET_CHANNEL_ID' field.
      * @param value The value of 'OUTLET_CHANNEL_ID'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder setOUTLETCHANNELID(java.lang.Long value) {
      validate(fields()[7], value);
      this.OUTLET_CHANNEL_ID = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'OUTLET_CHANNEL_ID' field has been set.
      * @return True if the 'OUTLET_CHANNEL_ID' field has been set, false otherwise.
      */
    public boolean hasOUTLETCHANNELID() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'OUTLET_CHANNEL_ID' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder clearOUTLETCHANNELID() {
      OUTLET_CHANNEL_ID = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'MGD_INVNTRY_IND' field.
      * @return The value.
      */
    public java.lang.Long getMGDINVNTRYIND() {
      return MGD_INVNTRY_IND;
    }


    /**
      * Sets the value of the 'MGD_INVNTRY_IND' field.
      * @param value The value of 'MGD_INVNTRY_IND'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder setMGDINVNTRYIND(java.lang.Long value) {
      validate(fields()[8], value);
      this.MGD_INVNTRY_IND = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'MGD_INVNTRY_IND' field has been set.
      * @return True if the 'MGD_INVNTRY_IND' field has been set, false otherwise.
      */
    public boolean hasMGDINVNTRYIND() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'MGD_INVNTRY_IND' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder clearMGDINVNTRYIND() {
      MGD_INVNTRY_IND = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'VLD_FOR_ORDR_IND' field.
      * @return The value.
      */
    public java.lang.Long getVLDFORORDRIND() {
      return VLD_FOR_ORDR_IND;
    }


    /**
      * Sets the value of the 'VLD_FOR_ORDR_IND' field.
      * @param value The value of 'VLD_FOR_ORDR_IND'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder setVLDFORORDRIND(java.lang.Long value) {
      validate(fields()[9], value);
      this.VLD_FOR_ORDR_IND = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'VLD_FOR_ORDR_IND' field has been set.
      * @return True if the 'VLD_FOR_ORDR_IND' field has been set, false otherwise.
      */
    public boolean hasVLDFORORDRIND() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'VLD_FOR_ORDR_IND' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder clearVLDFORORDRIND() {
      VLD_FOR_ORDR_IND = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'SRC_KEY_VAL' field.
      * @return The value.
      */
    public java.lang.CharSequence getSRCKEYVAL() {
      return SRC_KEY_VAL;
    }


    /**
      * Sets the value of the 'SRC_KEY_VAL' field.
      * @param value The value of 'SRC_KEY_VAL'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder setSRCKEYVAL(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.SRC_KEY_VAL = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'SRC_KEY_VAL' field has been set.
      * @return True if the 'SRC_KEY_VAL' field has been set, false otherwise.
      */
    public boolean hasSRCKEYVAL() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'SRC_KEY_VAL' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder clearSRCKEYVAL() {
      SRC_KEY_VAL = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'SRC_CDC_OPER_NM' field.
      * @return The value.
      */
    public java.lang.CharSequence getSRCCDCOPERNM() {
      return SRC_CDC_OPER_NM;
    }


    /**
      * Sets the value of the 'SRC_CDC_OPER_NM' field.
      * @param value The value of 'SRC_CDC_OPER_NM'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder setSRCCDCOPERNM(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.SRC_CDC_OPER_NM = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'SRC_CDC_OPER_NM' field has been set.
      * @return True if the 'SRC_CDC_OPER_NM' field has been set, false otherwise.
      */
    public boolean hasSRCCDCOPERNM() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'SRC_CDC_OPER_NM' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder clearSRCCDCOPERNM() {
      SRC_CDC_OPER_NM = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'SRC_COMMIT_DT_UTC' field.
      * @return The value.
      */
    public java.lang.CharSequence getSRCCOMMITDTUTC() {
      return SRC_COMMIT_DT_UTC;
    }


    /**
      * Sets the value of the 'SRC_COMMIT_DT_UTC' field.
      * @param value The value of 'SRC_COMMIT_DT_UTC'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder setSRCCOMMITDTUTC(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.SRC_COMMIT_DT_UTC = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'SRC_COMMIT_DT_UTC' field has been set.
      * @return True if the 'SRC_COMMIT_DT_UTC' field has been set, false otherwise.
      */
    public boolean hasSRCCOMMITDTUTC() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'SRC_COMMIT_DT_UTC' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder clearSRCCOMMITDTUTC() {
      SRC_COMMIT_DT_UTC = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'TRG_CRT_DT_PART_UTC' field.
      * @return The value.
      */
    public java.lang.CharSequence getTRGCRTDTPARTUTC() {
      return TRG_CRT_DT_PART_UTC;
    }


    /**
      * Sets the value of the 'TRG_CRT_DT_PART_UTC' field.
      * @param value The value of 'TRG_CRT_DT_PART_UTC'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder setTRGCRTDTPARTUTC(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.TRG_CRT_DT_PART_UTC = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'TRG_CRT_DT_PART_UTC' field has been set.
      * @return True if the 'TRG_CRT_DT_PART_UTC' field has been set, false otherwise.
      */
    public boolean hasTRGCRTDTPARTUTC() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'TRG_CRT_DT_PART_UTC' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder clearTRGCRTDTPARTUTC() {
      TRG_CRT_DT_PART_UTC = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'SRC_SCHEMA_NM' field.
      * @return The value.
      */
    public java.lang.CharSequence getSRCSCHEMANM() {
      return SRC_SCHEMA_NM;
    }


    /**
      * Sets the value of the 'SRC_SCHEMA_NM' field.
      * @param value The value of 'SRC_SCHEMA_NM'.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder setSRCSCHEMANM(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.SRC_SCHEMA_NM = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'SRC_SCHEMA_NM' field has been set.
      * @return True if the 'SRC_SCHEMA_NM' field has been set, false otherwise.
      */
    public boolean hasSRCSCHEMANM() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'SRC_SCHEMA_NM' field.
      * @return This builder.
      */
    public org.LNDCDC_ADS_COMMON.OUTLET_EXTENSION.apache.nifi.LNDCDC_ADS_COMMON_OUTLET_EXTENSION.Builder clearSRCSCHEMANM() {
      SRC_SCHEMA_NM = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LNDCDC_ADS_COMMON_OUTLET_EXTENSION build() {
      try {
        LNDCDC_ADS_COMMON_OUTLET_EXTENSION record = new LNDCDC_ADS_COMMON_OUTLET_EXTENSION();
        record.OUTLET_EXTENSION_ID = fieldSetFlags()[0] ? this.OUTLET_EXTENSION_ID : (java.lang.Long) defaultValue(fields()[0]);
        record.LAST_MODIFIED_BY = fieldSetFlags()[1] ? this.LAST_MODIFIED_BY : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.LAST_MODIFIED_DT = fieldSetFlags()[2] ? this.LAST_MODIFIED_DT : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.OUTLET_KEY = fieldSetFlags()[3] ? this.OUTLET_KEY : (java.lang.Double) defaultValue(fields()[3]);
        record.DIVISION_ID = fieldSetFlags()[4] ? this.DIVISION_ID : (java.lang.Long) defaultValue(fields()[4]);
        record.INACTIVE_DT = fieldSetFlags()[5] ? this.INACTIVE_DT : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.REGION_ID = fieldSetFlags()[6] ? this.REGION_ID : (java.lang.Long) defaultValue(fields()[6]);
        record.OUTLET_CHANNEL_ID = fieldSetFlags()[7] ? this.OUTLET_CHANNEL_ID : (java.lang.Long) defaultValue(fields()[7]);
        record.MGD_INVNTRY_IND = fieldSetFlags()[8] ? this.MGD_INVNTRY_IND : (java.lang.Long) defaultValue(fields()[8]);
        record.VLD_FOR_ORDR_IND = fieldSetFlags()[9] ? this.VLD_FOR_ORDR_IND : (java.lang.Long) defaultValue(fields()[9]);
        record.SRC_KEY_VAL = fieldSetFlags()[10] ? this.SRC_KEY_VAL : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.SRC_CDC_OPER_NM = fieldSetFlags()[11] ? this.SRC_CDC_OPER_NM : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.SRC_COMMIT_DT_UTC = fieldSetFlags()[12] ? this.SRC_COMMIT_DT_UTC : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.TRG_CRT_DT_PART_UTC = fieldSetFlags()[13] ? this.TRG_CRT_DT_PART_UTC : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.SRC_SCHEMA_NM = fieldSetFlags()[14] ? this.SRC_SCHEMA_NM : (java.lang.CharSequence) defaultValue(fields()[14]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LNDCDC_ADS_COMMON_OUTLET_EXTENSION>
    WRITER$ = (org.apache.avro.io.DatumWriter<LNDCDC_ADS_COMMON_OUTLET_EXTENSION>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LNDCDC_ADS_COMMON_OUTLET_EXTENSION>
    READER$ = (org.apache.avro.io.DatumReader<LNDCDC_ADS_COMMON_OUTLET_EXTENSION>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.OUTLET_EXTENSION_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.OUTLET_EXTENSION_ID);
    }

    if (this.LAST_MODIFIED_BY == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.LAST_MODIFIED_BY);
    }

    if (this.LAST_MODIFIED_DT == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.LAST_MODIFIED_DT);
    }

    if (this.OUTLET_KEY == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.OUTLET_KEY);
    }

    if (this.DIVISION_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.DIVISION_ID);
    }

    if (this.INACTIVE_DT == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.INACTIVE_DT);
    }

    if (this.REGION_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.REGION_ID);
    }

    if (this.OUTLET_CHANNEL_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.OUTLET_CHANNEL_ID);
    }

    if (this.MGD_INVNTRY_IND == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.MGD_INVNTRY_IND);
    }

    if (this.VLD_FOR_ORDR_IND == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.VLD_FOR_ORDR_IND);
    }

    out.writeString(this.SRC_KEY_VAL);

    out.writeString(this.SRC_CDC_OPER_NM);

    out.writeString(this.SRC_COMMIT_DT_UTC);

    out.writeString(this.TRG_CRT_DT_PART_UTC);

    out.writeString(this.SRC_SCHEMA_NM);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.OUTLET_EXTENSION_ID = null;
      } else {
        this.OUTLET_EXTENSION_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.LAST_MODIFIED_BY = null;
      } else {
        this.LAST_MODIFIED_BY = in.readString(this.LAST_MODIFIED_BY instanceof Utf8 ? (Utf8)this.LAST_MODIFIED_BY : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.LAST_MODIFIED_DT = null;
      } else {
        this.LAST_MODIFIED_DT = in.readString(this.LAST_MODIFIED_DT instanceof Utf8 ? (Utf8)this.LAST_MODIFIED_DT : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.OUTLET_KEY = null;
      } else {
        this.OUTLET_KEY = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.DIVISION_ID = null;
      } else {
        this.DIVISION_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.INACTIVE_DT = null;
      } else {
        this.INACTIVE_DT = in.readString(this.INACTIVE_DT instanceof Utf8 ? (Utf8)this.INACTIVE_DT : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.REGION_ID = null;
      } else {
        this.REGION_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.OUTLET_CHANNEL_ID = null;
      } else {
        this.OUTLET_CHANNEL_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.MGD_INVNTRY_IND = null;
      } else {
        this.MGD_INVNTRY_IND = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.VLD_FOR_ORDR_IND = null;
      } else {
        this.VLD_FOR_ORDR_IND = in.readLong();
      }

      this.SRC_KEY_VAL = in.readString(this.SRC_KEY_VAL instanceof Utf8 ? (Utf8)this.SRC_KEY_VAL : null);

      this.SRC_CDC_OPER_NM = in.readString(this.SRC_CDC_OPER_NM instanceof Utf8 ? (Utf8)this.SRC_CDC_OPER_NM : null);

      this.SRC_COMMIT_DT_UTC = in.readString(this.SRC_COMMIT_DT_UTC instanceof Utf8 ? (Utf8)this.SRC_COMMIT_DT_UTC : null);

      this.TRG_CRT_DT_PART_UTC = in.readString(this.TRG_CRT_DT_PART_UTC instanceof Utf8 ? (Utf8)this.TRG_CRT_DT_PART_UTC : null);

      this.SRC_SCHEMA_NM = in.readString(this.SRC_SCHEMA_NM instanceof Utf8 ? (Utf8)this.SRC_SCHEMA_NM : null);

    } else {
      for (int i = 0; i < 15; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.OUTLET_EXTENSION_ID = null;
          } else {
            this.OUTLET_EXTENSION_ID = in.readLong();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.LAST_MODIFIED_BY = null;
          } else {
            this.LAST_MODIFIED_BY = in.readString(this.LAST_MODIFIED_BY instanceof Utf8 ? (Utf8)this.LAST_MODIFIED_BY : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.LAST_MODIFIED_DT = null;
          } else {
            this.LAST_MODIFIED_DT = in.readString(this.LAST_MODIFIED_DT instanceof Utf8 ? (Utf8)this.LAST_MODIFIED_DT : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.OUTLET_KEY = null;
          } else {
            this.OUTLET_KEY = in.readDouble();
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.DIVISION_ID = null;
          } else {
            this.DIVISION_ID = in.readLong();
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.INACTIVE_DT = null;
          } else {
            this.INACTIVE_DT = in.readString(this.INACTIVE_DT instanceof Utf8 ? (Utf8)this.INACTIVE_DT : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.REGION_ID = null;
          } else {
            this.REGION_ID = in.readLong();
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.OUTLET_CHANNEL_ID = null;
          } else {
            this.OUTLET_CHANNEL_ID = in.readLong();
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.MGD_INVNTRY_IND = null;
          } else {
            this.MGD_INVNTRY_IND = in.readLong();
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.VLD_FOR_ORDR_IND = null;
          } else {
            this.VLD_FOR_ORDR_IND = in.readLong();
          }
          break;

        case 10:
          this.SRC_KEY_VAL = in.readString(this.SRC_KEY_VAL instanceof Utf8 ? (Utf8)this.SRC_KEY_VAL : null);
          break;

        case 11:
          this.SRC_CDC_OPER_NM = in.readString(this.SRC_CDC_OPER_NM instanceof Utf8 ? (Utf8)this.SRC_CDC_OPER_NM : null);
          break;

        case 12:
          this.SRC_COMMIT_DT_UTC = in.readString(this.SRC_COMMIT_DT_UTC instanceof Utf8 ? (Utf8)this.SRC_COMMIT_DT_UTC : null);
          break;

        case 13:
          this.TRG_CRT_DT_PART_UTC = in.readString(this.TRG_CRT_DT_PART_UTC instanceof Utf8 ? (Utf8)this.TRG_CRT_DT_PART_UTC : null);
          break;

        case 14:
          this.SRC_SCHEMA_NM = in.readString(this.SRC_SCHEMA_NM instanceof Utf8 ? (Utf8)this.SRC_SCHEMA_NM : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










