/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LNDCDC_NCS_TCS_DAYPARTS_TAB extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8493130052117799796L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LNDCDC_NCS_TCS_DAYPARTS_TAB\",\"namespace\":\"org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi\",\"fields\":[{\"name\":\"DP_CODE\",\"type\":[\"null\",\"string\"]},{\"name\":\"DP_NIEL_OR_ESPN_IND\",\"type\":[\"null\",\"string\"]},{\"name\":\"DP_PNT_CODE\",\"type\":[\"null\",\"string\"]},{\"name\":\"DP_PNT_NIEL_OR_ESPN_IND\",\"type\":[\"null\",\"string\"]},{\"name\":\"DP_NAME\",\"type\":[\"null\",\"string\"]},{\"name\":\"DP_BARTER_UNIT_AMT\",\"type\":[\"null\",\"long\"]},{\"name\":\"DP_LOG_NUMBER\",\"type\":[\"null\",\"long\"]},{\"name\":\"DP_LOG_NETWORK\",\"type\":[\"null\",\"string\"]},{\"name\":\"DP_TYPE\",\"type\":[\"null\",\"string\"]},{\"name\":\"DP_BUD_USE\",\"type\":[\"null\",\"string\"]},{\"name\":\"DP_BUD_SEQ\",\"type\":[\"null\",\"long\"]},{\"name\":\"DP_DESC\",\"type\":[\"null\",\"string\"]},{\"name\":\"DP_APPL\",\"type\":[\"null\",\"string\"]},{\"name\":\"DP_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"CDC_KEY\",\"type\":[\"null\",\"double\"]},{\"name\":\"SRC_KEY_VAL\",\"type\":\"string\"},{\"name\":\"SRC_CDC_OPER_NM\",\"type\":\"string\"},{\"name\":\"SRC_COMMIT_DT_UTC\",\"type\":\"string\"},{\"name\":\"TRG_CRT_DT_PART_UTC\",\"type\":\"string\"},{\"name\":\"SRC_SCHEMA_NM\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LNDCDC_NCS_TCS_DAYPARTS_TAB> ENCODER =
      new BinaryMessageEncoder<LNDCDC_NCS_TCS_DAYPARTS_TAB>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LNDCDC_NCS_TCS_DAYPARTS_TAB> DECODER =
      new BinaryMessageDecoder<LNDCDC_NCS_TCS_DAYPARTS_TAB>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LNDCDC_NCS_TCS_DAYPARTS_TAB> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LNDCDC_NCS_TCS_DAYPARTS_TAB> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LNDCDC_NCS_TCS_DAYPARTS_TAB> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LNDCDC_NCS_TCS_DAYPARTS_TAB>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LNDCDC_NCS_TCS_DAYPARTS_TAB to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LNDCDC_NCS_TCS_DAYPARTS_TAB from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LNDCDC_NCS_TCS_DAYPARTS_TAB instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LNDCDC_NCS_TCS_DAYPARTS_TAB fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence DP_CODE;
   private java.lang.CharSequence DP_NIEL_OR_ESPN_IND;
   private java.lang.CharSequence DP_PNT_CODE;
   private java.lang.CharSequence DP_PNT_NIEL_OR_ESPN_IND;
   private java.lang.CharSequence DP_NAME;
   private java.lang.Long DP_BARTER_UNIT_AMT;
   private java.lang.Long DP_LOG_NUMBER;
   private java.lang.CharSequence DP_LOG_NETWORK;
   private java.lang.CharSequence DP_TYPE;
   private java.lang.CharSequence DP_BUD_USE;
   private java.lang.Long DP_BUD_SEQ;
   private java.lang.CharSequence DP_DESC;
   private java.lang.CharSequence DP_APPL;
   private java.lang.Long DP_ID;
   private java.lang.Double CDC_KEY;
   private java.lang.CharSequence SRC_KEY_VAL;
   private java.lang.CharSequence SRC_CDC_OPER_NM;
   private java.lang.CharSequence SRC_COMMIT_DT_UTC;
   private java.lang.CharSequence TRG_CRT_DT_PART_UTC;
   private java.lang.CharSequence SRC_SCHEMA_NM;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LNDCDC_NCS_TCS_DAYPARTS_TAB() {}

  /**
   * All-args constructor.
   * @param DP_CODE The new value for DP_CODE
   * @param DP_NIEL_OR_ESPN_IND The new value for DP_NIEL_OR_ESPN_IND
   * @param DP_PNT_CODE The new value for DP_PNT_CODE
   * @param DP_PNT_NIEL_OR_ESPN_IND The new value for DP_PNT_NIEL_OR_ESPN_IND
   * @param DP_NAME The new value for DP_NAME
   * @param DP_BARTER_UNIT_AMT The new value for DP_BARTER_UNIT_AMT
   * @param DP_LOG_NUMBER The new value for DP_LOG_NUMBER
   * @param DP_LOG_NETWORK The new value for DP_LOG_NETWORK
   * @param DP_TYPE The new value for DP_TYPE
   * @param DP_BUD_USE The new value for DP_BUD_USE
   * @param DP_BUD_SEQ The new value for DP_BUD_SEQ
   * @param DP_DESC The new value for DP_DESC
   * @param DP_APPL The new value for DP_APPL
   * @param DP_ID The new value for DP_ID
   * @param CDC_KEY The new value for CDC_KEY
   * @param SRC_KEY_VAL The new value for SRC_KEY_VAL
   * @param SRC_CDC_OPER_NM The new value for SRC_CDC_OPER_NM
   * @param SRC_COMMIT_DT_UTC The new value for SRC_COMMIT_DT_UTC
   * @param TRG_CRT_DT_PART_UTC The new value for TRG_CRT_DT_PART_UTC
   * @param SRC_SCHEMA_NM The new value for SRC_SCHEMA_NM
   */
  public LNDCDC_NCS_TCS_DAYPARTS_TAB(java.lang.CharSequence DP_CODE, java.lang.CharSequence DP_NIEL_OR_ESPN_IND, java.lang.CharSequence DP_PNT_CODE, java.lang.CharSequence DP_PNT_NIEL_OR_ESPN_IND, java.lang.CharSequence DP_NAME, java.lang.Long DP_BARTER_UNIT_AMT, java.lang.Long DP_LOG_NUMBER, java.lang.CharSequence DP_LOG_NETWORK, java.lang.CharSequence DP_TYPE, java.lang.CharSequence DP_BUD_USE, java.lang.Long DP_BUD_SEQ, java.lang.CharSequence DP_DESC, java.lang.CharSequence DP_APPL, java.lang.Long DP_ID, java.lang.Double CDC_KEY, java.lang.CharSequence SRC_KEY_VAL, java.lang.CharSequence SRC_CDC_OPER_NM, java.lang.CharSequence SRC_COMMIT_DT_UTC, java.lang.CharSequence TRG_CRT_DT_PART_UTC, java.lang.CharSequence SRC_SCHEMA_NM) {
    this.DP_CODE = DP_CODE;
    this.DP_NIEL_OR_ESPN_IND = DP_NIEL_OR_ESPN_IND;
    this.DP_PNT_CODE = DP_PNT_CODE;
    this.DP_PNT_NIEL_OR_ESPN_IND = DP_PNT_NIEL_OR_ESPN_IND;
    this.DP_NAME = DP_NAME;
    this.DP_BARTER_UNIT_AMT = DP_BARTER_UNIT_AMT;
    this.DP_LOG_NUMBER = DP_LOG_NUMBER;
    this.DP_LOG_NETWORK = DP_LOG_NETWORK;
    this.DP_TYPE = DP_TYPE;
    this.DP_BUD_USE = DP_BUD_USE;
    this.DP_BUD_SEQ = DP_BUD_SEQ;
    this.DP_DESC = DP_DESC;
    this.DP_APPL = DP_APPL;
    this.DP_ID = DP_ID;
    this.CDC_KEY = CDC_KEY;
    this.SRC_KEY_VAL = SRC_KEY_VAL;
    this.SRC_CDC_OPER_NM = SRC_CDC_OPER_NM;
    this.SRC_COMMIT_DT_UTC = SRC_COMMIT_DT_UTC;
    this.TRG_CRT_DT_PART_UTC = TRG_CRT_DT_PART_UTC;
    this.SRC_SCHEMA_NM = SRC_SCHEMA_NM;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return DP_CODE;
    case 1: return DP_NIEL_OR_ESPN_IND;
    case 2: return DP_PNT_CODE;
    case 3: return DP_PNT_NIEL_OR_ESPN_IND;
    case 4: return DP_NAME;
    case 5: return DP_BARTER_UNIT_AMT;
    case 6: return DP_LOG_NUMBER;
    case 7: return DP_LOG_NETWORK;
    case 8: return DP_TYPE;
    case 9: return DP_BUD_USE;
    case 10: return DP_BUD_SEQ;
    case 11: return DP_DESC;
    case 12: return DP_APPL;
    case 13: return DP_ID;
    case 14: return CDC_KEY;
    case 15: return SRC_KEY_VAL;
    case 16: return SRC_CDC_OPER_NM;
    case 17: return SRC_COMMIT_DT_UTC;
    case 18: return TRG_CRT_DT_PART_UTC;
    case 19: return SRC_SCHEMA_NM;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: DP_CODE = (java.lang.CharSequence)value$; break;
    case 1: DP_NIEL_OR_ESPN_IND = (java.lang.CharSequence)value$; break;
    case 2: DP_PNT_CODE = (java.lang.CharSequence)value$; break;
    case 3: DP_PNT_NIEL_OR_ESPN_IND = (java.lang.CharSequence)value$; break;
    case 4: DP_NAME = (java.lang.CharSequence)value$; break;
    case 5: DP_BARTER_UNIT_AMT = (java.lang.Long)value$; break;
    case 6: DP_LOG_NUMBER = (java.lang.Long)value$; break;
    case 7: DP_LOG_NETWORK = (java.lang.CharSequence)value$; break;
    case 8: DP_TYPE = (java.lang.CharSequence)value$; break;
    case 9: DP_BUD_USE = (java.lang.CharSequence)value$; break;
    case 10: DP_BUD_SEQ = (java.lang.Long)value$; break;
    case 11: DP_DESC = (java.lang.CharSequence)value$; break;
    case 12: DP_APPL = (java.lang.CharSequence)value$; break;
    case 13: DP_ID = (java.lang.Long)value$; break;
    case 14: CDC_KEY = (java.lang.Double)value$; break;
    case 15: SRC_KEY_VAL = (java.lang.CharSequence)value$; break;
    case 16: SRC_CDC_OPER_NM = (java.lang.CharSequence)value$; break;
    case 17: SRC_COMMIT_DT_UTC = (java.lang.CharSequence)value$; break;
    case 18: TRG_CRT_DT_PART_UTC = (java.lang.CharSequence)value$; break;
    case 19: SRC_SCHEMA_NM = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'DP_CODE' field.
   * @return The value of the 'DP_CODE' field.
   */
  public java.lang.CharSequence getDPCODE() {
    return DP_CODE;
  }


  /**
   * Sets the value of the 'DP_CODE' field.
   * @param value the value to set.
   */
  public void setDPCODE(java.lang.CharSequence value) {
    this.DP_CODE = value;
  }

  /**
   * Gets the value of the 'DP_NIEL_OR_ESPN_IND' field.
   * @return The value of the 'DP_NIEL_OR_ESPN_IND' field.
   */
  public java.lang.CharSequence getDPNIELORESPNIND() {
    return DP_NIEL_OR_ESPN_IND;
  }


  /**
   * Sets the value of the 'DP_NIEL_OR_ESPN_IND' field.
   * @param value the value to set.
   */
  public void setDPNIELORESPNIND(java.lang.CharSequence value) {
    this.DP_NIEL_OR_ESPN_IND = value;
  }

  /**
   * Gets the value of the 'DP_PNT_CODE' field.
   * @return The value of the 'DP_PNT_CODE' field.
   */
  public java.lang.CharSequence getDPPNTCODE() {
    return DP_PNT_CODE;
  }


  /**
   * Sets the value of the 'DP_PNT_CODE' field.
   * @param value the value to set.
   */
  public void setDPPNTCODE(java.lang.CharSequence value) {
    this.DP_PNT_CODE = value;
  }

  /**
   * Gets the value of the 'DP_PNT_NIEL_OR_ESPN_IND' field.
   * @return The value of the 'DP_PNT_NIEL_OR_ESPN_IND' field.
   */
  public java.lang.CharSequence getDPPNTNIELORESPNIND() {
    return DP_PNT_NIEL_OR_ESPN_IND;
  }


  /**
   * Sets the value of the 'DP_PNT_NIEL_OR_ESPN_IND' field.
   * @param value the value to set.
   */
  public void setDPPNTNIELORESPNIND(java.lang.CharSequence value) {
    this.DP_PNT_NIEL_OR_ESPN_IND = value;
  }

  /**
   * Gets the value of the 'DP_NAME' field.
   * @return The value of the 'DP_NAME' field.
   */
  public java.lang.CharSequence getDPNAME() {
    return DP_NAME;
  }


  /**
   * Sets the value of the 'DP_NAME' field.
   * @param value the value to set.
   */
  public void setDPNAME(java.lang.CharSequence value) {
    this.DP_NAME = value;
  }

  /**
   * Gets the value of the 'DP_BARTER_UNIT_AMT' field.
   * @return The value of the 'DP_BARTER_UNIT_AMT' field.
   */
  public java.lang.Long getDPBARTERUNITAMT() {
    return DP_BARTER_UNIT_AMT;
  }


  /**
   * Sets the value of the 'DP_BARTER_UNIT_AMT' field.
   * @param value the value to set.
   */
  public void setDPBARTERUNITAMT(java.lang.Long value) {
    this.DP_BARTER_UNIT_AMT = value;
  }

  /**
   * Gets the value of the 'DP_LOG_NUMBER' field.
   * @return The value of the 'DP_LOG_NUMBER' field.
   */
  public java.lang.Long getDPLOGNUMBER() {
    return DP_LOG_NUMBER;
  }


  /**
   * Sets the value of the 'DP_LOG_NUMBER' field.
   * @param value the value to set.
   */
  public void setDPLOGNUMBER(java.lang.Long value) {
    this.DP_LOG_NUMBER = value;
  }

  /**
   * Gets the value of the 'DP_LOG_NETWORK' field.
   * @return The value of the 'DP_LOG_NETWORK' field.
   */
  public java.lang.CharSequence getDPLOGNETWORK() {
    return DP_LOG_NETWORK;
  }


  /**
   * Sets the value of the 'DP_LOG_NETWORK' field.
   * @param value the value to set.
   */
  public void setDPLOGNETWORK(java.lang.CharSequence value) {
    this.DP_LOG_NETWORK = value;
  }

  /**
   * Gets the value of the 'DP_TYPE' field.
   * @return The value of the 'DP_TYPE' field.
   */
  public java.lang.CharSequence getDPTYPE() {
    return DP_TYPE;
  }


  /**
   * Sets the value of the 'DP_TYPE' field.
   * @param value the value to set.
   */
  public void setDPTYPE(java.lang.CharSequence value) {
    this.DP_TYPE = value;
  }

  /**
   * Gets the value of the 'DP_BUD_USE' field.
   * @return The value of the 'DP_BUD_USE' field.
   */
  public java.lang.CharSequence getDPBUDUSE() {
    return DP_BUD_USE;
  }


  /**
   * Sets the value of the 'DP_BUD_USE' field.
   * @param value the value to set.
   */
  public void setDPBUDUSE(java.lang.CharSequence value) {
    this.DP_BUD_USE = value;
  }

  /**
   * Gets the value of the 'DP_BUD_SEQ' field.
   * @return The value of the 'DP_BUD_SEQ' field.
   */
  public java.lang.Long getDPBUDSEQ() {
    return DP_BUD_SEQ;
  }


  /**
   * Sets the value of the 'DP_BUD_SEQ' field.
   * @param value the value to set.
   */
  public void setDPBUDSEQ(java.lang.Long value) {
    this.DP_BUD_SEQ = value;
  }

  /**
   * Gets the value of the 'DP_DESC' field.
   * @return The value of the 'DP_DESC' field.
   */
  public java.lang.CharSequence getDPDESC() {
    return DP_DESC;
  }


  /**
   * Sets the value of the 'DP_DESC' field.
   * @param value the value to set.
   */
  public void setDPDESC(java.lang.CharSequence value) {
    this.DP_DESC = value;
  }

  /**
   * Gets the value of the 'DP_APPL' field.
   * @return The value of the 'DP_APPL' field.
   */
  public java.lang.CharSequence getDPAPPL() {
    return DP_APPL;
  }


  /**
   * Sets the value of the 'DP_APPL' field.
   * @param value the value to set.
   */
  public void setDPAPPL(java.lang.CharSequence value) {
    this.DP_APPL = value;
  }

  /**
   * Gets the value of the 'DP_ID' field.
   * @return The value of the 'DP_ID' field.
   */
  public java.lang.Long getDPID() {
    return DP_ID;
  }


  /**
   * Sets the value of the 'DP_ID' field.
   * @param value the value to set.
   */
  public void setDPID(java.lang.Long value) {
    this.DP_ID = value;
  }

  /**
   * Gets the value of the 'CDC_KEY' field.
   * @return The value of the 'CDC_KEY' field.
   */
  public java.lang.Double getCDCKEY() {
    return CDC_KEY;
  }


  /**
   * Sets the value of the 'CDC_KEY' field.
   * @param value the value to set.
   */
  public void setCDCKEY(java.lang.Double value) {
    this.CDC_KEY = value;
  }

  /**
   * Gets the value of the 'SRC_KEY_VAL' field.
   * @return The value of the 'SRC_KEY_VAL' field.
   */
  public java.lang.CharSequence getSRCKEYVAL() {
    return SRC_KEY_VAL;
  }


  /**
   * Sets the value of the 'SRC_KEY_VAL' field.
   * @param value the value to set.
   */
  public void setSRCKEYVAL(java.lang.CharSequence value) {
    this.SRC_KEY_VAL = value;
  }

  /**
   * Gets the value of the 'SRC_CDC_OPER_NM' field.
   * @return The value of the 'SRC_CDC_OPER_NM' field.
   */
  public java.lang.CharSequence getSRCCDCOPERNM() {
    return SRC_CDC_OPER_NM;
  }


  /**
   * Sets the value of the 'SRC_CDC_OPER_NM' field.
   * @param value the value to set.
   */
  public void setSRCCDCOPERNM(java.lang.CharSequence value) {
    this.SRC_CDC_OPER_NM = value;
  }

  /**
   * Gets the value of the 'SRC_COMMIT_DT_UTC' field.
   * @return The value of the 'SRC_COMMIT_DT_UTC' field.
   */
  public java.lang.CharSequence getSRCCOMMITDTUTC() {
    return SRC_COMMIT_DT_UTC;
  }


  /**
   * Sets the value of the 'SRC_COMMIT_DT_UTC' field.
   * @param value the value to set.
   */
  public void setSRCCOMMITDTUTC(java.lang.CharSequence value) {
    this.SRC_COMMIT_DT_UTC = value;
  }

  /**
   * Gets the value of the 'TRG_CRT_DT_PART_UTC' field.
   * @return The value of the 'TRG_CRT_DT_PART_UTC' field.
   */
  public java.lang.CharSequence getTRGCRTDTPARTUTC() {
    return TRG_CRT_DT_PART_UTC;
  }


  /**
   * Sets the value of the 'TRG_CRT_DT_PART_UTC' field.
   * @param value the value to set.
   */
  public void setTRGCRTDTPARTUTC(java.lang.CharSequence value) {
    this.TRG_CRT_DT_PART_UTC = value;
  }

  /**
   * Gets the value of the 'SRC_SCHEMA_NM' field.
   * @return The value of the 'SRC_SCHEMA_NM' field.
   */
  public java.lang.CharSequence getSRCSCHEMANM() {
    return SRC_SCHEMA_NM;
  }


  /**
   * Sets the value of the 'SRC_SCHEMA_NM' field.
   * @param value the value to set.
   */
  public void setSRCSCHEMANM(java.lang.CharSequence value) {
    this.SRC_SCHEMA_NM = value;
  }

  /**
   * Creates a new LNDCDC_NCS_TCS_DAYPARTS_TAB RecordBuilder.
   * @return A new LNDCDC_NCS_TCS_DAYPARTS_TAB RecordBuilder
   */
  public static org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder newBuilder() {
    return new org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder();
  }

  /**
   * Creates a new LNDCDC_NCS_TCS_DAYPARTS_TAB RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LNDCDC_NCS_TCS_DAYPARTS_TAB RecordBuilder
   */
  public static org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder newBuilder(org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder other) {
    if (other == null) {
      return new org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder();
    } else {
      return new org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder(other);
    }
  }

  /**
   * Creates a new LNDCDC_NCS_TCS_DAYPARTS_TAB RecordBuilder by copying an existing LNDCDC_NCS_TCS_DAYPARTS_TAB instance.
   * @param other The existing instance to copy.
   * @return A new LNDCDC_NCS_TCS_DAYPARTS_TAB RecordBuilder
   */
  public static org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder newBuilder(org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB other) {
    if (other == null) {
      return new org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder();
    } else {
      return new org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder(other);
    }
  }

  /**
   * RecordBuilder for LNDCDC_NCS_TCS_DAYPARTS_TAB instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LNDCDC_NCS_TCS_DAYPARTS_TAB>
    implements org.apache.avro.data.RecordBuilder<LNDCDC_NCS_TCS_DAYPARTS_TAB> {

    private java.lang.CharSequence DP_CODE;
    private java.lang.CharSequence DP_NIEL_OR_ESPN_IND;
    private java.lang.CharSequence DP_PNT_CODE;
    private java.lang.CharSequence DP_PNT_NIEL_OR_ESPN_IND;
    private java.lang.CharSequence DP_NAME;
    private java.lang.Long DP_BARTER_UNIT_AMT;
    private java.lang.Long DP_LOG_NUMBER;
    private java.lang.CharSequence DP_LOG_NETWORK;
    private java.lang.CharSequence DP_TYPE;
    private java.lang.CharSequence DP_BUD_USE;
    private java.lang.Long DP_BUD_SEQ;
    private java.lang.CharSequence DP_DESC;
    private java.lang.CharSequence DP_APPL;
    private java.lang.Long DP_ID;
    private java.lang.Double CDC_KEY;
    private java.lang.CharSequence SRC_KEY_VAL;
    private java.lang.CharSequence SRC_CDC_OPER_NM;
    private java.lang.CharSequence SRC_COMMIT_DT_UTC;
    private java.lang.CharSequence TRG_CRT_DT_PART_UTC;
    private java.lang.CharSequence SRC_SCHEMA_NM;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.DP_CODE)) {
        this.DP_CODE = data().deepCopy(fields()[0].schema(), other.DP_CODE);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.DP_NIEL_OR_ESPN_IND)) {
        this.DP_NIEL_OR_ESPN_IND = data().deepCopy(fields()[1].schema(), other.DP_NIEL_OR_ESPN_IND);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.DP_PNT_CODE)) {
        this.DP_PNT_CODE = data().deepCopy(fields()[2].schema(), other.DP_PNT_CODE);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.DP_PNT_NIEL_OR_ESPN_IND)) {
        this.DP_PNT_NIEL_OR_ESPN_IND = data().deepCopy(fields()[3].schema(), other.DP_PNT_NIEL_OR_ESPN_IND);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.DP_NAME)) {
        this.DP_NAME = data().deepCopy(fields()[4].schema(), other.DP_NAME);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.DP_BARTER_UNIT_AMT)) {
        this.DP_BARTER_UNIT_AMT = data().deepCopy(fields()[5].schema(), other.DP_BARTER_UNIT_AMT);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.DP_LOG_NUMBER)) {
        this.DP_LOG_NUMBER = data().deepCopy(fields()[6].schema(), other.DP_LOG_NUMBER);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.DP_LOG_NETWORK)) {
        this.DP_LOG_NETWORK = data().deepCopy(fields()[7].schema(), other.DP_LOG_NETWORK);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.DP_TYPE)) {
        this.DP_TYPE = data().deepCopy(fields()[8].schema(), other.DP_TYPE);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.DP_BUD_USE)) {
        this.DP_BUD_USE = data().deepCopy(fields()[9].schema(), other.DP_BUD_USE);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.DP_BUD_SEQ)) {
        this.DP_BUD_SEQ = data().deepCopy(fields()[10].schema(), other.DP_BUD_SEQ);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.DP_DESC)) {
        this.DP_DESC = data().deepCopy(fields()[11].schema(), other.DP_DESC);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.DP_APPL)) {
        this.DP_APPL = data().deepCopy(fields()[12].schema(), other.DP_APPL);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.DP_ID)) {
        this.DP_ID = data().deepCopy(fields()[13].schema(), other.DP_ID);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.CDC_KEY)) {
        this.CDC_KEY = data().deepCopy(fields()[14].schema(), other.CDC_KEY);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.SRC_KEY_VAL)) {
        this.SRC_KEY_VAL = data().deepCopy(fields()[15].schema(), other.SRC_KEY_VAL);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
      if (isValidValue(fields()[16], other.SRC_CDC_OPER_NM)) {
        this.SRC_CDC_OPER_NM = data().deepCopy(fields()[16].schema(), other.SRC_CDC_OPER_NM);
        fieldSetFlags()[16] = other.fieldSetFlags()[16];
      }
      if (isValidValue(fields()[17], other.SRC_COMMIT_DT_UTC)) {
        this.SRC_COMMIT_DT_UTC = data().deepCopy(fields()[17].schema(), other.SRC_COMMIT_DT_UTC);
        fieldSetFlags()[17] = other.fieldSetFlags()[17];
      }
      if (isValidValue(fields()[18], other.TRG_CRT_DT_PART_UTC)) {
        this.TRG_CRT_DT_PART_UTC = data().deepCopy(fields()[18].schema(), other.TRG_CRT_DT_PART_UTC);
        fieldSetFlags()[18] = other.fieldSetFlags()[18];
      }
      if (isValidValue(fields()[19], other.SRC_SCHEMA_NM)) {
        this.SRC_SCHEMA_NM = data().deepCopy(fields()[19].schema(), other.SRC_SCHEMA_NM);
        fieldSetFlags()[19] = other.fieldSetFlags()[19];
      }
    }

    /**
     * Creates a Builder by copying an existing LNDCDC_NCS_TCS_DAYPARTS_TAB instance
     * @param other The existing instance to copy.
     */
    private Builder(org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.DP_CODE)) {
        this.DP_CODE = data().deepCopy(fields()[0].schema(), other.DP_CODE);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.DP_NIEL_OR_ESPN_IND)) {
        this.DP_NIEL_OR_ESPN_IND = data().deepCopy(fields()[1].schema(), other.DP_NIEL_OR_ESPN_IND);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.DP_PNT_CODE)) {
        this.DP_PNT_CODE = data().deepCopy(fields()[2].schema(), other.DP_PNT_CODE);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.DP_PNT_NIEL_OR_ESPN_IND)) {
        this.DP_PNT_NIEL_OR_ESPN_IND = data().deepCopy(fields()[3].schema(), other.DP_PNT_NIEL_OR_ESPN_IND);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.DP_NAME)) {
        this.DP_NAME = data().deepCopy(fields()[4].schema(), other.DP_NAME);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.DP_BARTER_UNIT_AMT)) {
        this.DP_BARTER_UNIT_AMT = data().deepCopy(fields()[5].schema(), other.DP_BARTER_UNIT_AMT);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.DP_LOG_NUMBER)) {
        this.DP_LOG_NUMBER = data().deepCopy(fields()[6].schema(), other.DP_LOG_NUMBER);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.DP_LOG_NETWORK)) {
        this.DP_LOG_NETWORK = data().deepCopy(fields()[7].schema(), other.DP_LOG_NETWORK);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.DP_TYPE)) {
        this.DP_TYPE = data().deepCopy(fields()[8].schema(), other.DP_TYPE);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.DP_BUD_USE)) {
        this.DP_BUD_USE = data().deepCopy(fields()[9].schema(), other.DP_BUD_USE);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.DP_BUD_SEQ)) {
        this.DP_BUD_SEQ = data().deepCopy(fields()[10].schema(), other.DP_BUD_SEQ);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.DP_DESC)) {
        this.DP_DESC = data().deepCopy(fields()[11].schema(), other.DP_DESC);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.DP_APPL)) {
        this.DP_APPL = data().deepCopy(fields()[12].schema(), other.DP_APPL);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.DP_ID)) {
        this.DP_ID = data().deepCopy(fields()[13].schema(), other.DP_ID);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.CDC_KEY)) {
        this.CDC_KEY = data().deepCopy(fields()[14].schema(), other.CDC_KEY);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.SRC_KEY_VAL)) {
        this.SRC_KEY_VAL = data().deepCopy(fields()[15].schema(), other.SRC_KEY_VAL);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.SRC_CDC_OPER_NM)) {
        this.SRC_CDC_OPER_NM = data().deepCopy(fields()[16].schema(), other.SRC_CDC_OPER_NM);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.SRC_COMMIT_DT_UTC)) {
        this.SRC_COMMIT_DT_UTC = data().deepCopy(fields()[17].schema(), other.SRC_COMMIT_DT_UTC);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.TRG_CRT_DT_PART_UTC)) {
        this.TRG_CRT_DT_PART_UTC = data().deepCopy(fields()[18].schema(), other.TRG_CRT_DT_PART_UTC);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.SRC_SCHEMA_NM)) {
        this.SRC_SCHEMA_NM = data().deepCopy(fields()[19].schema(), other.SRC_SCHEMA_NM);
        fieldSetFlags()[19] = true;
      }
    }

    /**
      * Gets the value of the 'DP_CODE' field.
      * @return The value.
      */
    public java.lang.CharSequence getDPCODE() {
      return DP_CODE;
    }


    /**
      * Sets the value of the 'DP_CODE' field.
      * @param value The value of 'DP_CODE'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setDPCODE(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.DP_CODE = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'DP_CODE' field has been set.
      * @return True if the 'DP_CODE' field has been set, false otherwise.
      */
    public boolean hasDPCODE() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'DP_CODE' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearDPCODE() {
      DP_CODE = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'DP_NIEL_OR_ESPN_IND' field.
      * @return The value.
      */
    public java.lang.CharSequence getDPNIELORESPNIND() {
      return DP_NIEL_OR_ESPN_IND;
    }


    /**
      * Sets the value of the 'DP_NIEL_OR_ESPN_IND' field.
      * @param value The value of 'DP_NIEL_OR_ESPN_IND'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setDPNIELORESPNIND(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.DP_NIEL_OR_ESPN_IND = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'DP_NIEL_OR_ESPN_IND' field has been set.
      * @return True if the 'DP_NIEL_OR_ESPN_IND' field has been set, false otherwise.
      */
    public boolean hasDPNIELORESPNIND() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'DP_NIEL_OR_ESPN_IND' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearDPNIELORESPNIND() {
      DP_NIEL_OR_ESPN_IND = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'DP_PNT_CODE' field.
      * @return The value.
      */
    public java.lang.CharSequence getDPPNTCODE() {
      return DP_PNT_CODE;
    }


    /**
      * Sets the value of the 'DP_PNT_CODE' field.
      * @param value The value of 'DP_PNT_CODE'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setDPPNTCODE(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.DP_PNT_CODE = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'DP_PNT_CODE' field has been set.
      * @return True if the 'DP_PNT_CODE' field has been set, false otherwise.
      */
    public boolean hasDPPNTCODE() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'DP_PNT_CODE' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearDPPNTCODE() {
      DP_PNT_CODE = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'DP_PNT_NIEL_OR_ESPN_IND' field.
      * @return The value.
      */
    public java.lang.CharSequence getDPPNTNIELORESPNIND() {
      return DP_PNT_NIEL_OR_ESPN_IND;
    }


    /**
      * Sets the value of the 'DP_PNT_NIEL_OR_ESPN_IND' field.
      * @param value The value of 'DP_PNT_NIEL_OR_ESPN_IND'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setDPPNTNIELORESPNIND(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.DP_PNT_NIEL_OR_ESPN_IND = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'DP_PNT_NIEL_OR_ESPN_IND' field has been set.
      * @return True if the 'DP_PNT_NIEL_OR_ESPN_IND' field has been set, false otherwise.
      */
    public boolean hasDPPNTNIELORESPNIND() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'DP_PNT_NIEL_OR_ESPN_IND' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearDPPNTNIELORESPNIND() {
      DP_PNT_NIEL_OR_ESPN_IND = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'DP_NAME' field.
      * @return The value.
      */
    public java.lang.CharSequence getDPNAME() {
      return DP_NAME;
    }


    /**
      * Sets the value of the 'DP_NAME' field.
      * @param value The value of 'DP_NAME'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setDPNAME(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.DP_NAME = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'DP_NAME' field has been set.
      * @return True if the 'DP_NAME' field has been set, false otherwise.
      */
    public boolean hasDPNAME() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'DP_NAME' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearDPNAME() {
      DP_NAME = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'DP_BARTER_UNIT_AMT' field.
      * @return The value.
      */
    public java.lang.Long getDPBARTERUNITAMT() {
      return DP_BARTER_UNIT_AMT;
    }


    /**
      * Sets the value of the 'DP_BARTER_UNIT_AMT' field.
      * @param value The value of 'DP_BARTER_UNIT_AMT'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setDPBARTERUNITAMT(java.lang.Long value) {
      validate(fields()[5], value);
      this.DP_BARTER_UNIT_AMT = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'DP_BARTER_UNIT_AMT' field has been set.
      * @return True if the 'DP_BARTER_UNIT_AMT' field has been set, false otherwise.
      */
    public boolean hasDPBARTERUNITAMT() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'DP_BARTER_UNIT_AMT' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearDPBARTERUNITAMT() {
      DP_BARTER_UNIT_AMT = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'DP_LOG_NUMBER' field.
      * @return The value.
      */
    public java.lang.Long getDPLOGNUMBER() {
      return DP_LOG_NUMBER;
    }


    /**
      * Sets the value of the 'DP_LOG_NUMBER' field.
      * @param value The value of 'DP_LOG_NUMBER'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setDPLOGNUMBER(java.lang.Long value) {
      validate(fields()[6], value);
      this.DP_LOG_NUMBER = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'DP_LOG_NUMBER' field has been set.
      * @return True if the 'DP_LOG_NUMBER' field has been set, false otherwise.
      */
    public boolean hasDPLOGNUMBER() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'DP_LOG_NUMBER' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearDPLOGNUMBER() {
      DP_LOG_NUMBER = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'DP_LOG_NETWORK' field.
      * @return The value.
      */
    public java.lang.CharSequence getDPLOGNETWORK() {
      return DP_LOG_NETWORK;
    }


    /**
      * Sets the value of the 'DP_LOG_NETWORK' field.
      * @param value The value of 'DP_LOG_NETWORK'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setDPLOGNETWORK(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.DP_LOG_NETWORK = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'DP_LOG_NETWORK' field has been set.
      * @return True if the 'DP_LOG_NETWORK' field has been set, false otherwise.
      */
    public boolean hasDPLOGNETWORK() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'DP_LOG_NETWORK' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearDPLOGNETWORK() {
      DP_LOG_NETWORK = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'DP_TYPE' field.
      * @return The value.
      */
    public java.lang.CharSequence getDPTYPE() {
      return DP_TYPE;
    }


    /**
      * Sets the value of the 'DP_TYPE' field.
      * @param value The value of 'DP_TYPE'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setDPTYPE(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.DP_TYPE = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'DP_TYPE' field has been set.
      * @return True if the 'DP_TYPE' field has been set, false otherwise.
      */
    public boolean hasDPTYPE() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'DP_TYPE' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearDPTYPE() {
      DP_TYPE = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'DP_BUD_USE' field.
      * @return The value.
      */
    public java.lang.CharSequence getDPBUDUSE() {
      return DP_BUD_USE;
    }


    /**
      * Sets the value of the 'DP_BUD_USE' field.
      * @param value The value of 'DP_BUD_USE'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setDPBUDUSE(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.DP_BUD_USE = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'DP_BUD_USE' field has been set.
      * @return True if the 'DP_BUD_USE' field has been set, false otherwise.
      */
    public boolean hasDPBUDUSE() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'DP_BUD_USE' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearDPBUDUSE() {
      DP_BUD_USE = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'DP_BUD_SEQ' field.
      * @return The value.
      */
    public java.lang.Long getDPBUDSEQ() {
      return DP_BUD_SEQ;
    }


    /**
      * Sets the value of the 'DP_BUD_SEQ' field.
      * @param value The value of 'DP_BUD_SEQ'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setDPBUDSEQ(java.lang.Long value) {
      validate(fields()[10], value);
      this.DP_BUD_SEQ = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'DP_BUD_SEQ' field has been set.
      * @return True if the 'DP_BUD_SEQ' field has been set, false otherwise.
      */
    public boolean hasDPBUDSEQ() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'DP_BUD_SEQ' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearDPBUDSEQ() {
      DP_BUD_SEQ = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'DP_DESC' field.
      * @return The value.
      */
    public java.lang.CharSequence getDPDESC() {
      return DP_DESC;
    }


    /**
      * Sets the value of the 'DP_DESC' field.
      * @param value The value of 'DP_DESC'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setDPDESC(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.DP_DESC = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'DP_DESC' field has been set.
      * @return True if the 'DP_DESC' field has been set, false otherwise.
      */
    public boolean hasDPDESC() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'DP_DESC' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearDPDESC() {
      DP_DESC = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'DP_APPL' field.
      * @return The value.
      */
    public java.lang.CharSequence getDPAPPL() {
      return DP_APPL;
    }


    /**
      * Sets the value of the 'DP_APPL' field.
      * @param value The value of 'DP_APPL'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setDPAPPL(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.DP_APPL = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'DP_APPL' field has been set.
      * @return True if the 'DP_APPL' field has been set, false otherwise.
      */
    public boolean hasDPAPPL() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'DP_APPL' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearDPAPPL() {
      DP_APPL = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'DP_ID' field.
      * @return The value.
      */
    public java.lang.Long getDPID() {
      return DP_ID;
    }


    /**
      * Sets the value of the 'DP_ID' field.
      * @param value The value of 'DP_ID'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setDPID(java.lang.Long value) {
      validate(fields()[13], value);
      this.DP_ID = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'DP_ID' field has been set.
      * @return True if the 'DP_ID' field has been set, false otherwise.
      */
    public boolean hasDPID() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'DP_ID' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearDPID() {
      DP_ID = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'CDC_KEY' field.
      * @return The value.
      */
    public java.lang.Double getCDCKEY() {
      return CDC_KEY;
    }


    /**
      * Sets the value of the 'CDC_KEY' field.
      * @param value The value of 'CDC_KEY'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setCDCKEY(java.lang.Double value) {
      validate(fields()[14], value);
      this.CDC_KEY = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'CDC_KEY' field has been set.
      * @return True if the 'CDC_KEY' field has been set, false otherwise.
      */
    public boolean hasCDCKEY() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'CDC_KEY' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearCDCKEY() {
      CDC_KEY = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'SRC_KEY_VAL' field.
      * @return The value.
      */
    public java.lang.CharSequence getSRCKEYVAL() {
      return SRC_KEY_VAL;
    }


    /**
      * Sets the value of the 'SRC_KEY_VAL' field.
      * @param value The value of 'SRC_KEY_VAL'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setSRCKEYVAL(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.SRC_KEY_VAL = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'SRC_KEY_VAL' field has been set.
      * @return True if the 'SRC_KEY_VAL' field has been set, false otherwise.
      */
    public boolean hasSRCKEYVAL() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'SRC_KEY_VAL' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearSRCKEYVAL() {
      SRC_KEY_VAL = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'SRC_CDC_OPER_NM' field.
      * @return The value.
      */
    public java.lang.CharSequence getSRCCDCOPERNM() {
      return SRC_CDC_OPER_NM;
    }


    /**
      * Sets the value of the 'SRC_CDC_OPER_NM' field.
      * @param value The value of 'SRC_CDC_OPER_NM'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setSRCCDCOPERNM(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.SRC_CDC_OPER_NM = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'SRC_CDC_OPER_NM' field has been set.
      * @return True if the 'SRC_CDC_OPER_NM' field has been set, false otherwise.
      */
    public boolean hasSRCCDCOPERNM() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'SRC_CDC_OPER_NM' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearSRCCDCOPERNM() {
      SRC_CDC_OPER_NM = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'SRC_COMMIT_DT_UTC' field.
      * @return The value.
      */
    public java.lang.CharSequence getSRCCOMMITDTUTC() {
      return SRC_COMMIT_DT_UTC;
    }


    /**
      * Sets the value of the 'SRC_COMMIT_DT_UTC' field.
      * @param value The value of 'SRC_COMMIT_DT_UTC'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setSRCCOMMITDTUTC(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.SRC_COMMIT_DT_UTC = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'SRC_COMMIT_DT_UTC' field has been set.
      * @return True if the 'SRC_COMMIT_DT_UTC' field has been set, false otherwise.
      */
    public boolean hasSRCCOMMITDTUTC() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'SRC_COMMIT_DT_UTC' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearSRCCOMMITDTUTC() {
      SRC_COMMIT_DT_UTC = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'TRG_CRT_DT_PART_UTC' field.
      * @return The value.
      */
    public java.lang.CharSequence getTRGCRTDTPARTUTC() {
      return TRG_CRT_DT_PART_UTC;
    }


    /**
      * Sets the value of the 'TRG_CRT_DT_PART_UTC' field.
      * @param value The value of 'TRG_CRT_DT_PART_UTC'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setTRGCRTDTPARTUTC(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.TRG_CRT_DT_PART_UTC = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'TRG_CRT_DT_PART_UTC' field has been set.
      * @return True if the 'TRG_CRT_DT_PART_UTC' field has been set, false otherwise.
      */
    public boolean hasTRGCRTDTPARTUTC() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'TRG_CRT_DT_PART_UTC' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearTRGCRTDTPARTUTC() {
      TRG_CRT_DT_PART_UTC = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'SRC_SCHEMA_NM' field.
      * @return The value.
      */
    public java.lang.CharSequence getSRCSCHEMANM() {
      return SRC_SCHEMA_NM;
    }


    /**
      * Sets the value of the 'SRC_SCHEMA_NM' field.
      * @param value The value of 'SRC_SCHEMA_NM'.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder setSRCSCHEMANM(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.SRC_SCHEMA_NM = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'SRC_SCHEMA_NM' field has been set.
      * @return True if the 'SRC_SCHEMA_NM' field has been set, false otherwise.
      */
    public boolean hasSRCSCHEMANM() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'SRC_SCHEMA_NM' field.
      * @return This builder.
      */
    public org.LNDCDC_NCS_TCS.DAYPARTS_TAB.apache.nifi.LNDCDC_NCS_TCS_DAYPARTS_TAB.Builder clearSRCSCHEMANM() {
      SRC_SCHEMA_NM = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LNDCDC_NCS_TCS_DAYPARTS_TAB build() {
      try {
        LNDCDC_NCS_TCS_DAYPARTS_TAB record = new LNDCDC_NCS_TCS_DAYPARTS_TAB();
        record.DP_CODE = fieldSetFlags()[0] ? this.DP_CODE : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.DP_NIEL_OR_ESPN_IND = fieldSetFlags()[1] ? this.DP_NIEL_OR_ESPN_IND : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.DP_PNT_CODE = fieldSetFlags()[2] ? this.DP_PNT_CODE : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.DP_PNT_NIEL_OR_ESPN_IND = fieldSetFlags()[3] ? this.DP_PNT_NIEL_OR_ESPN_IND : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.DP_NAME = fieldSetFlags()[4] ? this.DP_NAME : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.DP_BARTER_UNIT_AMT = fieldSetFlags()[5] ? this.DP_BARTER_UNIT_AMT : (java.lang.Long) defaultValue(fields()[5]);
        record.DP_LOG_NUMBER = fieldSetFlags()[6] ? this.DP_LOG_NUMBER : (java.lang.Long) defaultValue(fields()[6]);
        record.DP_LOG_NETWORK = fieldSetFlags()[7] ? this.DP_LOG_NETWORK : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.DP_TYPE = fieldSetFlags()[8] ? this.DP_TYPE : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.DP_BUD_USE = fieldSetFlags()[9] ? this.DP_BUD_USE : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.DP_BUD_SEQ = fieldSetFlags()[10] ? this.DP_BUD_SEQ : (java.lang.Long) defaultValue(fields()[10]);
        record.DP_DESC = fieldSetFlags()[11] ? this.DP_DESC : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.DP_APPL = fieldSetFlags()[12] ? this.DP_APPL : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.DP_ID = fieldSetFlags()[13] ? this.DP_ID : (java.lang.Long) defaultValue(fields()[13]);
        record.CDC_KEY = fieldSetFlags()[14] ? this.CDC_KEY : (java.lang.Double) defaultValue(fields()[14]);
        record.SRC_KEY_VAL = fieldSetFlags()[15] ? this.SRC_KEY_VAL : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.SRC_CDC_OPER_NM = fieldSetFlags()[16] ? this.SRC_CDC_OPER_NM : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.SRC_COMMIT_DT_UTC = fieldSetFlags()[17] ? this.SRC_COMMIT_DT_UTC : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.TRG_CRT_DT_PART_UTC = fieldSetFlags()[18] ? this.TRG_CRT_DT_PART_UTC : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.SRC_SCHEMA_NM = fieldSetFlags()[19] ? this.SRC_SCHEMA_NM : (java.lang.CharSequence) defaultValue(fields()[19]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LNDCDC_NCS_TCS_DAYPARTS_TAB>
    WRITER$ = (org.apache.avro.io.DatumWriter<LNDCDC_NCS_TCS_DAYPARTS_TAB>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LNDCDC_NCS_TCS_DAYPARTS_TAB>
    READER$ = (org.apache.avro.io.DatumReader<LNDCDC_NCS_TCS_DAYPARTS_TAB>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.DP_CODE == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.DP_CODE);
    }

    if (this.DP_NIEL_OR_ESPN_IND == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.DP_NIEL_OR_ESPN_IND);
    }

    if (this.DP_PNT_CODE == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.DP_PNT_CODE);
    }

    if (this.DP_PNT_NIEL_OR_ESPN_IND == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.DP_PNT_NIEL_OR_ESPN_IND);
    }

    if (this.DP_NAME == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.DP_NAME);
    }

    if (this.DP_BARTER_UNIT_AMT == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.DP_BARTER_UNIT_AMT);
    }

    if (this.DP_LOG_NUMBER == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.DP_LOG_NUMBER);
    }

    if (this.DP_LOG_NETWORK == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.DP_LOG_NETWORK);
    }

    if (this.DP_TYPE == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.DP_TYPE);
    }

    if (this.DP_BUD_USE == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.DP_BUD_USE);
    }

    if (this.DP_BUD_SEQ == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.DP_BUD_SEQ);
    }

    if (this.DP_DESC == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.DP_DESC);
    }

    if (this.DP_APPL == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.DP_APPL);
    }

    if (this.DP_ID == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.DP_ID);
    }

    if (this.CDC_KEY == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.CDC_KEY);
    }

    out.writeString(this.SRC_KEY_VAL);

    out.writeString(this.SRC_CDC_OPER_NM);

    out.writeString(this.SRC_COMMIT_DT_UTC);

    out.writeString(this.TRG_CRT_DT_PART_UTC);

    out.writeString(this.SRC_SCHEMA_NM);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.DP_CODE = null;
      } else {
        this.DP_CODE = in.readString(this.DP_CODE instanceof Utf8 ? (Utf8)this.DP_CODE : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.DP_NIEL_OR_ESPN_IND = null;
      } else {
        this.DP_NIEL_OR_ESPN_IND = in.readString(this.DP_NIEL_OR_ESPN_IND instanceof Utf8 ? (Utf8)this.DP_NIEL_OR_ESPN_IND : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.DP_PNT_CODE = null;
      } else {
        this.DP_PNT_CODE = in.readString(this.DP_PNT_CODE instanceof Utf8 ? (Utf8)this.DP_PNT_CODE : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.DP_PNT_NIEL_OR_ESPN_IND = null;
      } else {
        this.DP_PNT_NIEL_OR_ESPN_IND = in.readString(this.DP_PNT_NIEL_OR_ESPN_IND instanceof Utf8 ? (Utf8)this.DP_PNT_NIEL_OR_ESPN_IND : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.DP_NAME = null;
      } else {
        this.DP_NAME = in.readString(this.DP_NAME instanceof Utf8 ? (Utf8)this.DP_NAME : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.DP_BARTER_UNIT_AMT = null;
      } else {
        this.DP_BARTER_UNIT_AMT = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.DP_LOG_NUMBER = null;
      } else {
        this.DP_LOG_NUMBER = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.DP_LOG_NETWORK = null;
      } else {
        this.DP_LOG_NETWORK = in.readString(this.DP_LOG_NETWORK instanceof Utf8 ? (Utf8)this.DP_LOG_NETWORK : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.DP_TYPE = null;
      } else {
        this.DP_TYPE = in.readString(this.DP_TYPE instanceof Utf8 ? (Utf8)this.DP_TYPE : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.DP_BUD_USE = null;
      } else {
        this.DP_BUD_USE = in.readString(this.DP_BUD_USE instanceof Utf8 ? (Utf8)this.DP_BUD_USE : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.DP_BUD_SEQ = null;
      } else {
        this.DP_BUD_SEQ = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.DP_DESC = null;
      } else {
        this.DP_DESC = in.readString(this.DP_DESC instanceof Utf8 ? (Utf8)this.DP_DESC : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.DP_APPL = null;
      } else {
        this.DP_APPL = in.readString(this.DP_APPL instanceof Utf8 ? (Utf8)this.DP_APPL : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.DP_ID = null;
      } else {
        this.DP_ID = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.CDC_KEY = null;
      } else {
        this.CDC_KEY = in.readDouble();
      }

      this.SRC_KEY_VAL = in.readString(this.SRC_KEY_VAL instanceof Utf8 ? (Utf8)this.SRC_KEY_VAL : null);

      this.SRC_CDC_OPER_NM = in.readString(this.SRC_CDC_OPER_NM instanceof Utf8 ? (Utf8)this.SRC_CDC_OPER_NM : null);

      this.SRC_COMMIT_DT_UTC = in.readString(this.SRC_COMMIT_DT_UTC instanceof Utf8 ? (Utf8)this.SRC_COMMIT_DT_UTC : null);

      this.TRG_CRT_DT_PART_UTC = in.readString(this.TRG_CRT_DT_PART_UTC instanceof Utf8 ? (Utf8)this.TRG_CRT_DT_PART_UTC : null);

      this.SRC_SCHEMA_NM = in.readString(this.SRC_SCHEMA_NM instanceof Utf8 ? (Utf8)this.SRC_SCHEMA_NM : null);

    } else {
      for (int i = 0; i < 20; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.DP_CODE = null;
          } else {
            this.DP_CODE = in.readString(this.DP_CODE instanceof Utf8 ? (Utf8)this.DP_CODE : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.DP_NIEL_OR_ESPN_IND = null;
          } else {
            this.DP_NIEL_OR_ESPN_IND = in.readString(this.DP_NIEL_OR_ESPN_IND instanceof Utf8 ? (Utf8)this.DP_NIEL_OR_ESPN_IND : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.DP_PNT_CODE = null;
          } else {
            this.DP_PNT_CODE = in.readString(this.DP_PNT_CODE instanceof Utf8 ? (Utf8)this.DP_PNT_CODE : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.DP_PNT_NIEL_OR_ESPN_IND = null;
          } else {
            this.DP_PNT_NIEL_OR_ESPN_IND = in.readString(this.DP_PNT_NIEL_OR_ESPN_IND instanceof Utf8 ? (Utf8)this.DP_PNT_NIEL_OR_ESPN_IND : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.DP_NAME = null;
          } else {
            this.DP_NAME = in.readString(this.DP_NAME instanceof Utf8 ? (Utf8)this.DP_NAME : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.DP_BARTER_UNIT_AMT = null;
          } else {
            this.DP_BARTER_UNIT_AMT = in.readLong();
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.DP_LOG_NUMBER = null;
          } else {
            this.DP_LOG_NUMBER = in.readLong();
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.DP_LOG_NETWORK = null;
          } else {
            this.DP_LOG_NETWORK = in.readString(this.DP_LOG_NETWORK instanceof Utf8 ? (Utf8)this.DP_LOG_NETWORK : null);
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.DP_TYPE = null;
          } else {
            this.DP_TYPE = in.readString(this.DP_TYPE instanceof Utf8 ? (Utf8)this.DP_TYPE : null);
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.DP_BUD_USE = null;
          } else {
            this.DP_BUD_USE = in.readString(this.DP_BUD_USE instanceof Utf8 ? (Utf8)this.DP_BUD_USE : null);
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.DP_BUD_SEQ = null;
          } else {
            this.DP_BUD_SEQ = in.readLong();
          }
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.DP_DESC = null;
          } else {
            this.DP_DESC = in.readString(this.DP_DESC instanceof Utf8 ? (Utf8)this.DP_DESC : null);
          }
          break;

        case 12:
          if (in.readIndex() != 1) {
            in.readNull();
            this.DP_APPL = null;
          } else {
            this.DP_APPL = in.readString(this.DP_APPL instanceof Utf8 ? (Utf8)this.DP_APPL : null);
          }
          break;

        case 13:
          if (in.readIndex() != 1) {
            in.readNull();
            this.DP_ID = null;
          } else {
            this.DP_ID = in.readLong();
          }
          break;

        case 14:
          if (in.readIndex() != 1) {
            in.readNull();
            this.CDC_KEY = null;
          } else {
            this.CDC_KEY = in.readDouble();
          }
          break;

        case 15:
          this.SRC_KEY_VAL = in.readString(this.SRC_KEY_VAL instanceof Utf8 ? (Utf8)this.SRC_KEY_VAL : null);
          break;

        case 16:
          this.SRC_CDC_OPER_NM = in.readString(this.SRC_CDC_OPER_NM instanceof Utf8 ? (Utf8)this.SRC_CDC_OPER_NM : null);
          break;

        case 17:
          this.SRC_COMMIT_DT_UTC = in.readString(this.SRC_COMMIT_DT_UTC instanceof Utf8 ? (Utf8)this.SRC_COMMIT_DT_UTC : null);
          break;

        case 18:
          this.TRG_CRT_DT_PART_UTC = in.readString(this.TRG_CRT_DT_PART_UTC instanceof Utf8 ? (Utf8)this.TRG_CRT_DT_PART_UTC : null);
          break;

        case 19:
          this.SRC_SCHEMA_NM = in.readString(this.SRC_SCHEMA_NM instanceof Utf8 ? (Utf8)this.SRC_SCHEMA_NM : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










